- src/verify.c
During a swupd verify --install, files are expected to be missing and must
be "fixed," so do not print out that it is missing/fixed in this case.
> Fix massive output spam

- src/curl.c
- src/search.c
Adding some return code checks and cleaning up one valid lock_fd leak
Signed-off-by: Brad T. Peters <brad.t.peters@intel.com>
> Clean up coverity-reported errors

- Makefile.am
Building on Yocto install phase certificate files are being installed twice as included in
_DATA twice. We can use EXTRA_DIST than dist_.
> Fix build failure on Yocto

- include/swupd.h
- src/check_update.c
- src/clr_bundle_add.c
- src/clr_bundle_rm.c
- src/curl.c
- src/download.c
- src/globals.c
- src/helpers.c
- src/main.c
- src/search.c
- src/verify.c
To support swupd-client testing without connecting to a web server, it's
convenient to use libcurl's FILE protocol, which will query files on the
local filesystem instead.
Because the libcurl-multi download path for fullfiles has treated the
"0" response code as an error, but it has the opposite meaning when
using the FILE protocol, only set the error when connecting to a web
server.
Also, the libcurl-easy code for synchronous downloads didn't treat "0"
specially, so this commit ensures the proper handling, as well as
setting a generic download error for the FILE protocol specific
CURLE_FILE_COULDNT_READ_FILE.
> Add support for libcurl's FILE protocol

- src/verify.c
This patch modifies success/failure reporting to ensure when the MoM manifest
cannot be downloaded, we report failure. 
Signed-off-by: Brad T. Peters <brad.t.peters@intel.com>
> Fix --fix successful report

- src/bundle.c
- src/verify.c
- test/functional/bundleremove/boot-file/setup.sh
Some call sites of recurse_manifest() did not handle return codes. Add handling for those, and also fix a functional test that was broken after adding the proper error handling.
> Always handle errors from recurse_manifest()

- src/bundle.c
When trying to remove a bundle that has not
valid name contained into /usr/share/clear/bundles
a segfault arise. This patch solves that by
properly validating the bundle name is valid
within MoM.
Signed-off-by: Jaime A. Garcia <jaime.garcia.naranjo@intel.com>
> fix segfault in bundle-remove on invalid bundle

- Makefile.am
- src/curl.c
- src/version.c
- test/functional/checkupdate/slow-server/server.py
- test/functional/checkupdate/slow-server/target-dir/usr/lib/os-release
- test/functional/checkupdate/slow-server/test.bats
Contains whites pace fix from #60.
In the case where the swupd_download_version_to_memory callback was run
multiple times, it would overwrite previous data instead of appending.
Correct this behavior by keeping track of data written so far in the
struct passed to the callback.
Resolves issue #45.
> Fix version to memory download

- src/subscriptions.c
When creating #58, some tests were observed to fail due to the subs list having a different order between systems. This change should prevent the behavior but needs tested on a system which saw the failing tests in the first place.
In order to avoid non deterministic behavior when processing the subs
list, sort it after running read_subscription_alt as it may add items to
the list in a different order between runs.
> Always sort subs after read_subscriptions_alt

- Makefile.am
- src/clr_bundle_rm.c
- test/functional/bundleremove/parse-args/target-dir/usr/lib/os-release
- test/functional/bundleremove/parse-args/test.bats
Instead of only checking if bundle-remove has at least one bundle
argument and ignoring additional ones, check that there is exactly one
argument passed to bundle-remove instead.
> Ensure bundle-remove gets one bundle argument

- src/check_update.c
- src/clr_bundle_add.c
- src/clr_bundle_rm.c
- src/main.c
- src/search.c
- src/verify.c
When set_path_prefix returns false, a message "cannot continue"
appears but swupd continues its execution, this patch goes to
err when a false is returned by set_path_prefix.
Signed-off-by: Jesus Ornelas Aguayo <jesus.ornelas.aguayo@intel.com>
> Fix the swupd resume when set_path_prefix returns false 

- src/bundle.c
Call free_manifest instead of plain free on allocated manifests.
> Correctly free manifest data

- src/manifest.c
The recently added call to verify_file(), used to skip files that are
already installed and have correct hashes, is a nice optimization for
the case when an update crosses a build where a new minversion was
applied to the server content.
However, I ran into a case where calling verify_file() like this results
in an incomplete update: If the corresponding hash calculation of a file
in the latest version *follows a symlink" for the path in the current
version, the hashes will match (assuming the same file content).
This issue is avoidable by checking for the file's presence in the
current version's manifest first, because manifests only contain real
paths (no non-leaf path components are symlinks).
> Improvements for update list creation

- Makefile.am
- configure.ac
- include/signature.h
- include/swupd.h
- src/bundle.c
- src/helpers.c
- src/manifest.c
- src/packs.c
- src/search.c
- src/signature.c
- src/update.c
- src/verify.c
- test/signature_verify_test.c
This PR represents the final working state of Tudor and I as we went through OpenSSL's poor documentation and addressed review comments from PR #85 .  The src/signature.c:verify_signature() function is an abomination, but we think we doesn't leak openssl state and valgrind is agreeing.  The code is focused now on just the MoM signature verification flow, which means some functions are now static.  The cert and cert path are now autoconf configurable.
> Signature verification

- src/search.c
If the MoM is not found on the server to match the os version on which
you're running, swupd search's MoM downloader returns 0 instead of an
error.  EMOM_NOTFOUND is a natural value to return.
When 0 is returned, the null MoM pointer is later derferenced leading to a
segfault.
Signed-off-by: Tim Pepper <timothy.c.pepper@linux.intel.com>
> don't segfault on not found MoM

- scripts/assert-certificate-validity.sh
This script checks that a give data file and signature verify correctly against
a certificate. Without introducing fuzzing, this covers all (8) combinations of
valid and invalid files that may occur, and corrupts them in the more often
seen ways, such as a partially downloaded Manifest, or a wrong signature file.
> Add certificate signature validation script

- src/curl.c
To support running swupd on distros without an HTTP2-enabled curl
package, explicitly check for the "unsupported protocol" error, returned
by libcurl in this event.
> Fix swupd operations when curl is not HTTP2-enabled

- src/helpers.c
A recent commit removed the declaration for this function in swupd.h,
and now the compiler warns about it being unused, so the function can be
removed entirely now.
> Remove unused function

- .gitignore
Ignore GPATH, GRTAGS and GTAGS files created by the gtags tool.
> Update gitignore for gtags metadata

- src/signature.c
Because swupd-client on Clear Linux may fork/exec clr-boot-manager near
the end of its operation, which itself checks for file descriptor leaks
before exiting, it will report leaks for files it did not open (i.e.
inherited from the parent process, swupd).
To resolve this, set O_CLOEXEC when opening the cert file using the "e"
flag (glibc extension).
> Set O_CLOEXEC when opening the certificate file

- src/helpers.c
When a file doesn't verify as part of verify_fix_path, prior to
downloading and staging the new file, first remove the old file staging
content.
This change was required due to a failure with swupd-client when run
inside Docker due to /var/lib/swupd being layered under multiple mount
points because of separate Docker Run commands. This caused rename(2) to
fail when the expected layout of /var/lib/swupd is to be the same mount
point.
With this change in place, the rename source content that would be from
a different mount is removed and redownloaded into the same mount as the
rename target.
> Remove staging content during verify_fix_path

- src/main.c
Besides being a better clock source, this clock source does not
change with time skew. We also don't print the time taken unless
we actually do something significant.
> Time: Display time spent using the raw monotonic clock.

- configure.ac
- include/swupd-build-variant.h
- include/xattrs.h
- src/xattrs.c
Swupd used to use a sorted blob of extended file attributes as part of
the data that was used to verify the contents. This caused problems if
extra attributes were added. In particular if a clearlinux system was
being run in a container that had selinux enabled in the base OS.
Add a configure option to allow the attributes to be considered or
not. Based on advice, the default is to ignore them, as this is what
everyone expects.
Tidied up passing a --selinux flag to tar, this is also handled by a new
config option.
> Add options to handle xattr at compile time.

- src/curl.c
Certain types of network-connectivity problems hit this curl error, so
print a diagnostic message when it occurs.
> Print error message for CURLE_COULDNT_CONNECT

- .gitignore
When running 'autoreconf', aclocal warns that the "m4" directory does
not exist, even though AC_CONFIG_MACRO_DIR in configure.ac declares that
it should exist.
To avoid the warning, track the directory in the git tree.
> build: track m4 directory to avoid aclocal warning

- include/swupd.h
- src/curl.c
- src/download.c
This fixes https://github.com/clearlinux/swupd-client/issues/41
Beware that I have only tested a slightly different patch against
2.87. Porting it to the current master code required some manual
conflict resolution and I haven't had the time to try the result.
> downloads: minimize syscalls to improve performance

- src/check_update.c
- src/main.c
- test/functional/checkupdate/new-version/lines-checked
- test/functional/checkupdate/new-version/test.bats
- test/functional/checkupdate/no-server-content/test.bats
- test/functional/checkupdate/no-target-content/test.bats
- test/functional/checkupdate/slow-server/lines-checked
- test/functional/checkupdate/slow-server/test.bats
- test/functional/checkupdate/version-match/lines-checked
- test/functional/checkupdate/version-match/test.bats
make the return code for swupd-client be 1 if there is no update
available. This follows in the tradition of grep, which returns 0 if
there are matches, 1 if there are not, and 2 for errors.
> swupd-client check-update return 1 if none available

- Makefile.am
When doing out-of-tree builds, the distributed
scripts are in different directory than where
the build is happening. This doesn't work:
make  install-exec-hook
make[2]: Entering directory '<builddir>'
perl scripts/findstatic.pl */*.o | grep -v Checking ||:
Can't open perl script "scripts/findstatic.pl": No such file or directory
make[2]: Leaving directory '<builddir>'
We therefore need to give perl the full path
of the perl-script to run using the standard
automake variable top_srcdir:
make  install-exec-hook
make[2]: Entering directory '<builddir>'
perl ../../../../../../../../tmp/swupd-client.git/scripts/findstatic.pl */*.o | grep -v Checking ||:
'bin_paths' is unique to src/search.o, should be static?  (initialised variable)
'do_search' is unique to src/search.o, should be static? …
> build: allow out of tree builds

- configure.ac
- include/swupd-build-variant.h
- src/xattrs.c
Commit fc0f570d added a check that prevents using --enable-xattr
together with --enable-bsdtar, perhaps because it was assumed that this
wouldn't work because there is no special tar option as in the GNU tar
case.
But bsdtar worked fined in combination with IMA and Smack xattrs in
Ostro OS. Xattrs are set accordingly there on the server side, so the
check needs to be removed to allow the combination.
Besides that, enabling xattrs also had no effect because xattrs.c
never got to see the SWUPD_WITH_XATTRS define due to not including
config.h.
@icarus-sparry this is the fix I mentioned on IRC.
> fix --enable-xattr

- configure.ac
- src/heuristics.c
This is required by distros which ship configuration files under
/etc. Those files then are considered read-only and must be updated as
part of OS updates.
> Add configure option to re-enable updating of config files

- Makefile.am
The backslash for the second-to-last entry in EXTRA_DIST was omitted,
leading to a dist issue.
> Fix typo in Makefile.am

- src/scripts.c
We call systemctl to update triggers once an update finishes, which enqueues a
task and then waits to finish by default thus blocking the system() call. This
adds unnecessary time to the update, so set --no-block and move on since we
already reached the end of the update.
> Do not block on systemctl post-update triggers

- src/hash.c
When IMA or Smack are active on the client, the downloaded Manifest
files will be assigned certain xattrs (security.ima
resp. security.SMACK64). Those xattrs did not exist on the server side
(because it is most likely not having those kernel features enabled)
and besides, the swupd-server code wouldn't include them in the
Manifest hashes even if they existed (see write_manifest_plain() in
src/manifest.c).
Therefore the client must ignore xattrs when verifying Manifest files.
This is the only place where verification gets relaxed. All other locations
still use xattrs, just as before.
This is the solution that was agree upon when discussing https://github.com/clearlinux/swupd-server/pull/34
> ignore xattrs when verifying Manifest files

- Makefile.am
- include/swupd.h
- src/helpers.c
- src/main.c
- src/telemetry.c
- src/update.c
- src/verify.c
This is a new telemetry framework for swupd-client. The patch is split up in a few changes:
- clean out some old telemetry stuff that was left around and is unused.
- Separate patch to always create new telemetry drop folder
- introduce new telemetry() function and use it in 3 locations (check, update, and verify paths) to create a telemetry record at completion of those actions.
This won't actually deliver records to the telemetry service. For that, a separate telemetry agent will be created that runs as a separate process and does not affect swupd operation. That "probe" will have its own repository.
> Telemetry - re-introduce telemetry.

- Makefile.am
- configure.ac
- include/swupd.h
- src/clr_bundle_add.c
- src/clr_bundle_rm.c
- src/globals.c
- src/main.c
- src/search.c
- src/signature.c
- src/verify.c
To better support running the functional test suite with signature
verification enabled, make the certificate location configurable. Note
that the basename of the certificate used for verification can be
configured separately with the --with-swupdcert=NAME option.
> Cleanups for the configure.ac; make the certificate location configurable

- Makefile.am
To simplify the discovery of C code style issues and enforce the rules
specified in .clang-format, I've added a new 'compliant' target for
running the appropriate clang-format command.
In case code style issues are found, source files are modified in place,
and the resulting diff can be viewed. The exit code in this case will be
1, so make will exit with an error. This helps to automate testing for
code style issues.
> build: add 'compliant' target for fixing code style issues

- Makefile.am
- docs/swupd.1
- docs/swupd.1.md
- include/swupd-internal.h
- include/swupd.h
- src/bundle.c
- src/clr_bundle_ls.c
- src/swupd.c
This group of patches add a new sub-command to swupd "bundle-list", this sub-command allows to show which bundles are installed in the local system.
> Add new bundle-list sub-command

- .gitignore
- src/bundle.c
- src/check_update.c
- src/clr_bundle_add.c
- src/helpers.c
- src/main.c
- src/packs.c
- src/search.c
- src/swupd.c
- src/update.c
- src/verify.c
This series is a first pass at some error handling improvements, with the goal of using the same error codes for certain classes of errors, and to make sure the main program always exits with a positive value for errors.
I have not yet addressed the more complex error handling scenarios (e.g. in `src/staging.c`). That will come later.
One behavior change should be noted: for swupd operations that require zero packs, the operation will now fail if the packs fail to extract with `tar`. Previously, pack extraction issues were ignored.
> Some error handling improvements; miscellaneous cleanups

- src/clr_bundle_ls.c
- test/functional/bundlelist/all/list/test.bats
- test/functional/bundlelist/all/test.bats
The swupd unit tests need a group of
options for execution environment, this
var was missed.
Signed-off-by: Mario Alfredo Carrillo Arevalo <mario.alfredo.c.arevalo@intel.com>
> Fix swupd options for bundle-list --all unit test

- src/clr_bundle_add.c
- src/clr_bundle_ls.c
- src/scripts.c
- src/verify.c
- test/functional/ignore-list
This change adds a minor code-styling fix, but more importantly it moves `swupd-client` away from using the legacy compatibility scripts inside `clr-boot-manager`, enforcing direct usage of it.
Note that a potential issue with the previous behaviour is the compatibility scripts do not contain a bin prefix, i.e. `$root/usr/bin/*.sh` invoke `clr-boot-manager update $*`, meaning the host side tool is
employed rather than the rootfs one.
> clr-boot-manager fixes

- continous.sh
- docker/Dockerfile
- docker/dockerrun.sh
This change adds a simple "./continous.sh" script which will allow
developers to test their changes against "clearlinux:latest" within a
clean Docker container.
If the container does not already exist, it will be created on demand.
Future builds will be done near instantly within the container.
Signed-off-by: Ikey Doherty <michael.i.doherty@intel.com>
> Add support for automated building within docker environment.

- src/clr_bundle_ls.c
The swupd_lock is not properly closed
when the work is done with bundle-list
subcommand.
> Fix swupd_lock file descriptor leaking

- src/globals.c
When swupd_init() is called more than once in
the same supwd run, pointer corruption ocurs on
some global variables causing memory corruption
and finally a SIGABRT. This patch fixes that
condition by properly setting all globals to
NULL when swupd_deinit() is called; or more
properly free_globals().
> fix memory corruption on multiple swupd_init call

- configure.ac
- src/signature.c
- test/functional/swupdlib.bash
The mixer and image creator treat the certpath as the full path of the
certificate filename, and swupd should too. If someone is overriding the
certificate with the cert path option, use the supplied string and don't
append a pre-defined name to it.
> Change certpath to be full path of certificate

- src/globals.c
I noticed this printf says something about getwd(), but that's not
actually being called directly there and that's not super useful to a
non-developer human anyway.  So I translated the function name to an
english description.
Signed-off-by: Tim Pepper <timothy.c.pepper@linux.intel.com>
> clarify printf

- src/bundle.c
- test/functional/bundleadd/add-existing/lines-checked
Currently if you try and add a non existent bundle, e.g. "foo" you get
two lines of output
foo bundle name is invalid, skipping it...
bundle(s) already installed, exiting now
This is caused by the add_subscriptions function calling itself
recursivly but failing to pass up results in a meaningful way. This
change makes the return value of add_subscriptions be a bitmask so it
can signal errors and packages added distinctly.
I did think about changing this function to return a struct but
decided this was a step too far.
> Improved error reporting for adding bad bundle

- Makefile.am
- include/swupd-error.h
- include/swupd.h
- src/clr_bundle_add.c
- src/clr_bundle_ls.c
- src/clr_bundle_rm.c
- src/globals.c
- src/helpers.c
- src/main.c
- src/search.c
- src/signature.c
- src/verify.c
- src/verifytime.c
- test/functional/swupdlib.bash
The system clock may be terribly off, especially on new hardware that has not
yet been calibrated. Updates rely on the certificate and system time being
sane to verify validity, so if a mismatch is found the certificate will
be deemed invalid and the update stopped. This patch attempts to fix the
system time to something sane using the time from the versionstamp,
which should not have been touched by any user except root. If the time is
normal and verification fails, the cert cannot be trusted.
> Try to recover from invalid certificate date

- scripts/swupd-completion.sh
Use the correct variable BASH_VERSINFO, rather than BASH_VERSION
> Make the backward compatability check work

- include/swupd.h
- src/bundle.c
- src/clr_bundle_add.c
- src/globals.c
- src/main.c
- src/update.c
- src/verify.c
This introduces a -t/--time option to update, verify, and bundle-add commands, displaying raw elapsed time and CPU process time for integral swupd operations within the given code paths.
> Add verbose timing to swupd operation

- include/swupd.h
- src/hash.c
- src/manifest.c
- src/update.c
- src/verify.c
For various reasons - partial downloads, power failure, user exiting -
the /var/lib/swupd state directory may become corrupt. When this happens,
manifests can be rendered unusable, causing various errors in swupd such as
signature failures, or errors reading the manifest. This patch attempts to
avoid such things causing updates or verifies to fail by cleaning up the
Manifests artifacts of what it could not use, and re-downloading them to
try again.
> Remove bad or unusable Manifest content and retry

- src/download.c
This series addresses a couple of double frees encountered in error paths and also a "hysteresis escape" that was hitting these error paths.
> Error handling fixes for fullfile downloads

- include/swupd.h
- src/globals.c
- src/heuristics.c
- src/scripts.c
We must not run these with --no-block because order must be preserved,
and critical components may need to be reexec'd, making this a core piece
of the swupd update process.
> Need to reexec systemd if it changed

- src/bundle.c
- src/packs.c
- test/functional/bundleadd/add-directory/lines-checked
- test/functional/bundleadd/add-multiple/lines-checked
- test/functional/bundleadd/boot-file/lines-checked
- test/functional/bundleadd/fix-missing-file/lines-checked
- test/functional/bundleadd/include/lines-checked
- test/functional/bundleadd/verify-fix-path/lines-checked
- test/functional/ignore-list
- test/functional/update/apply-full-file-delta/lines-checked
- test/functional/update/boot-file/lines-checked
- test/functional/update/download/lines-checked
- test/functional/update/include-old-bundle-with-tracked-file/lines-checked
- test/functional/update/include-old-bundle/lines-checked
- test/functional/update/include/lines-checked
- test/functional/update/missing-os-core/lines-checked
- test/functional/update/newest-deleted/lines-checked
- test/functional/update/skip-verified-fullfiles/lines-checked
- test/functional/update/use-full-file/lines-checked
- test/functional/update/use-pack/lines-checked
- test/functional/update/verify-fix-path-hash-mismatch/lines-checked
- test/functional/update/verify-fix-path-missing-dir/lines-checked
- test/functional/update/verify-fullfile-hash/lines-checked
- test/functional/verify/install-directory/lines-checked
- test/functional/verify/install-latest-directory/lines-checked
Swupd incorrectly says "Downloading pack <name>..." even if it does not
really download the pack. Fix this by saying downloading packs and only
printing if we downloaded a pack to extract.
> Fix download/extract pack message

- configure.ac
To ensure validity of the format number hardcoded in the binary, check
the supplied input against a regular expression using grep.
Note that the double square brackets are needed for the regex character
classes because square brackets are used for M4 quotation in Autoconf;
an extra pair of square brackets is needed to prevent them from being
stripped in the configure script.
> build: validate --with-formatid input

- include/swupd.h
- src/manifest.c
- src/update.c
- src/verify.c
This patch-set enables delta file application for manifests, decreasing manifest download size by a factor of 150x or more in some cases.
> Delta manifests

- src/bundle.c
- test/functional/bundleadd/fix-missing-file/lines-checked
The download_subscribed_packs() could fail for network issues or other related
problems, and because the only option for getting new packs is by downloading
zero packs or fullfiles, swupd should retry to get the packs before falling
into the verify_fix_path flow which signifies pack downloads errored out.
> Retry pack downloads on bundle-add

- src/manifest.c
Unlike the regular manifest loading code, loading a MoM also requires signature
verification to succeed. We cannot reset the retries after a signature
failed because the manifest may load fine, but still fail verification,
resulting in endlessly loading and verifying the Manifest.MoM
> Fix infinite signature failure loop

- include/swupd.h
- src/bundle.c
- src/globals.c
- src/manifest.c
- src/search.c
- src/update.c
- src/verify.c
The swupd client should support parsing extra data in the case that a format
bump occurred, or other possibly breaking change, so that it can at least
notify the user of more action needing to be taken post update.
> Add support for new manifest header line

- src/bundle.c
- src/check_update.c
- src/clr_bundle_add.c
- src/clr_bundle_ls.c
- src/clr_bundle_rm.c
- src/curl.c
- src/download.c
- src/filedesc.c
- src/globals.c
- src/hash.c
- src/hashdump.c
- src/helpers.c
- src/lock.c
- src/main.c
- src/manifest.c
- src/packs.c
- src/scripts.c
- src/search.c
- src/signature.c
- src/staging.c
- src/swupd.c
- src/update.c
- src/verify.c
- src/verifytime.c
- src/version.c
Write error and informative messages to stderr, only
write data to stdout so it can be piped to other programs.
Make stdout line buffered, rather than introduce race conditions into tests
> Convert printf to fprintf(stderr, almost everywhere

- Makefile.am
- include/swupd.h
- src/extra_files.c
- src/verify.c
Add a "swupd verify --picky" command which lists files under
/usr (modified by the --path option) which are not listed in the
current manifest. Exceptions /usr/local and /usr/lib/modules. The
former to allow for local changes, the latter because the clear boot
manager owns that directory.
> Add verify --picky command

- Makefile.am
- docs/swupd.1
- docs/swupd.1.rst
- include/swupd-internal.h
- src/autoupdate.c
- src/swupd.c
"swupd autoupdate" returns 0 if autoupdates are enabled.
"sudo autoupdate --enable" will unmask swupd-update.service
"sudo autoupdate --disable" will mask swupd-update.service
> PoC of swupd autoupdate command

- include/swupd.h
- src/extra_files.c
- src/verify.c
This is the basic implementation for a "factory reset" type of command.
It will take the functionality of verify --picky and act on the files found
as verify --fix does with files found mismatching in the manifest.
> Add verify --fix --picky functionality

- src/verify.c
--picky option was being recognized by swupd verify but not
its equivalent -Y
Signed-off-by: Alberto Murillo Silva <alberto.murillo.silva@intel.com>
> Add -Y option to parseargs argument

- test/bsdifftests/creatediffs.sh
The --basepath option for hashdump was renamed to --path a while back,
so fix up the creatediffs script accordingly.
> Fix hashdump invocation in bsdiff testsuite

- include/swupd-error.h
- src/check_update.c
- src/update.c
- src/verify.c
- test/functional/checkupdate/no-server-content/lines-checked
We draw a hard line with error codes, such that:
Error code 16 is reserved for failures resulting from the basic
network check. Any call to check_network() that fails will
return this error code. No other error path returns this
error code.
Additionally, check_network() is called in every normal code path.
All other, possibly network related issues, return a different
error code. If the basic network check succeeds, but e.g. pack
downloads fail, we return a new (23) error code so that we
can better establish the conditions through telemetry and
determine whether the error is on the client or the server,
which is highly likely with this new error code 23.
Subsequently, for automated updates, we can choose to ignore
update failures if the automated periodical updates fail
due to no network …
> Differentiate between various early network failures.

- .gitignore
- test/functional/checkupdate/slow-server/test.bats
Check that the simple test server in the checkupdate/slow-server/ test
is available before actually running the swupd command. This check is
done by testing the return status of a curl command on the server up to
ten times until successful.
Since this is an historically touchy test, output an additional
debug.log in the test directory with much more verbose logging (using
set -x).
> Wait for test server to become available before testing

- include/swupd.h
- src/bundle.c
- src/helpers.c
- src/packs.c
- src/staging.c
- src/update.c
- src/verify.c
- test/functional/ignore-list
- test/functional/update/apply-full-file-delta/lines-checked
- test/functional/update/boot-file/lines-checked
- test/functional/update/include-old-bundle-with-tracked-file/lines-checked
- test/functional/update/include-old-bundle/lines-checked
- test/functional/update/include/lines-checked
- test/functional/update/missing-os-core/lines-checked
- test/functional/update/newest-deleted/lines-checked
- test/functional/update/re-update-bad-os-release/lines-checked
- test/functional/update/re-update-required/lines-checked
- test/functional/update/skip-verified-fullfiles/lines-checked
- test/functional/update/use-full-file/lines-checked
- test/functional/update/use-pack/lines-checked
- test/functional/update/verify-fix-path-hash-mismatch/lines-checked
- test/functional/update/verify-fix-path-missing-dir/lines-checked
Add a basic progress indication for a couple potentially long-running
swupd tasks (download_pack and add_missing_files). The progress
indication is displayed as a percentage:
```
...85%
```
It overwrites its own line so the progress will update in place. It may
be interrupted by other swupd output:
```
...45%
Extracting os-core pack for version 10000
...50%
Extracting os-core-update pack for version 9000
...55%
```
The progress indication will then resume updating in place, on the same
line.
This progress is only displayed when outputting to a TTY, and will not
output anything when the output is being redirected. This is nice for
testing and logging, but means that these progress updates will not be
caught by processes that capture swupd output, such as ister.
Signed-off-by: Matthew …
> Add basic progress status for long-running tasks

- src/globals.c
Fixes #142.
Signed-off-by: Caio Marcelo de Oliveira Filho <caio.oliveira@intel.com>
> Don't accept trailing characters when validating numbers for --format

- src/helpers.c
Don't use the return value from swupd_rm, which is poorly defined, but
test directly that the file no longer exists.
> Test a statedir is removed directly

- src/download.c
Add newline so progress updates are printed correctly. Instead of this:
```
...10%File /file was not in a pack
...11%
```
Print a newline before the message:
```
...10%
File /file was not in a pack
...11%
```
> Add newline to informational print

- src/scripts.c
When running swupd in a container systemd is not operable and fails with
a "Failed to connect to bus" error. Instead of printing these errors
directly check if systemd is operable at all and print a warning if not,
then return early from the update_triggers.
swupd is never able to run in a container due to systemd not being present. Is this the right approach, warning and exit? I don't think it is reasonable to say updates failed every time in the container when it is just the post-update scripts that are being run.
However, with those post-update commands never being run in a container can we call the update complete?
> RFC: Print warning when systemd not operable

- src/autoupdate.c
In a container systemctl does not work, and /usr/bin/systemctl fails as
expected with "Failed to connect to bus: No such file or directory."
Because of this, swupd autoupdate will not work either. However,
"systemctl is-enabled ..." will not fail, even though it should.
Add an additional check to make sure /usr/bin/systemctl is working
before checking if swupd-update.service is-enabled. Report that swupd
was "Unable to determine autoupdate status" if this check fails.
I tested this by applying the change in a docker container. It reported that it was unable to determine autoupdate status as expected. If anyone has better ideas for how to test this let me know.
> Add initial systemctl check for autoupdate

- src/manifest.c
glibc marks system() as a function whose return value should not be
ignored, which is generally reasonable. In this case we do want to
ignore the return value. Just casting to vooid is not enough to stop
the gcc warning. So instead we use the value in an if statement with
an empty body, which we trust the optimizer to remove so there is no
run time penalty.
The alternative solution would be to use
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wwarn_unused_result"
system(log_cmd);
#pragma GCC diagnostic pop
but that is rather gcc specific.
> fix for issue 261, compiler warning

- Makefile.am
Use = rather than := on the line. It is only an efficiency gain.
replace patsubst and filter with a new variable and standard
substitution.
Replace %-style pattern with suffix rule.
> Fix for issue 260, make portability

- .travis.yml
Recent outages to sourceforge break Travis CI runs. Use the github
release instead and update to the latest version of libcheck (0.11.0).
> Travis: Use github as upstream for check

- Makefile.am
Without this patch, if the docs are not up to date generating them fails if separate src and build dirs are used.
> Fix (doc) build failure for separate src and build dirs.

- src/xattrs.c
Fixes #262
Define silly little function to get gcc to shut up about unused
parameters.
> compiler warnings in xattrs

- src/check_update.c
- src/clr_bundle_rm.c
- test/functional/checkupdate/no-server-content/lines-checked
- test/functional/checkupdate/slow-server/lines-checked
Fixes compiler warnings in clr_bundle_rm.c and check_update.c.
Also fixes tests and improves error message for check_network()
failure in check_update.c.
> Fix compiler warnings

- src/curl.c
Fixes #200
Because swupd-client uses libcurl, and my guess is that libcurl has
supported IPv6 for a long time, I don't see any reason to restrict
downloads to IPv4 only.
> Support IPv6 in download code

- src/search.c
Fixes #265 
The calls to strstr() and strcasestr() in file_search() from search.c
result in compiler warnings when -Wnonnull is specified, because GCC's
"nonnull" attribute applies to these functions.
The logic from the file_search() call sites prevent NULL pointers from
being passed to these functions, but to protect against future
refactoring introducing this bug, check that the appropriate pointers
are non-NULL before calling the string functions.
> Fix compiler warnings in search.c

- include/swupd.h
- src/curl.c
- src/download.c
- src/globals.c
- src/helpers.c
I need this in the context of the script that implements
https://github.com/clearlinux/swupd-client/issues/249: it works around
the lack of the "-m" parameter for "swupd
update" (https://github.com/clearlinux/swupd-client/issues/257) by
creationg a local directory with "version/format<xxx>/latest" and
using that via file://, while the actual content comes via http://.
> support mixing http and file URLs

- Makefile.am
Fixes #300
Do not use GNU Make 'dir' function, instead use shell dirname command.
> Portability for Makefile

- src/extra_files.c
Add /lib/kernel as the files to skip in addition to /lib/modules as
these are managed by clear-boot-manager.
Fixes #313
> Do not delete /usr/lib/kernel

- test/functional/matcher.awk
- test/functional/swupdlib.bash
- test/functional/update/rename/lines-checked
- test/functional/update/rename/test.bats
The output line checking for functional tests should ensure that lines from `lines-checked` do not match any patterns in `ignore-list`.
Also, fix an issue with the update/rename test and improve check_lines() error reporting to account for `ignore-list`.
> test: implement validation for lines-checked; improve check_lines() error reporting

- include/swupd.h
The check_network() function definition was recently removed, but the
declaration remained. Remove the declaration as well.
> Remove unused check_network() declaration

- include/swupd.h
- src/globals.c
- src/helpers.c
- src/update.c
- test/functional/update/re-update-bad-os-release/web-dir/20/Manifest.MoM
- test/functional/update/re-update-required/web-dir/20/Manifest.MoM
Instead of relying on swupd-server to put the post-update action in the
correct manifest and in the correct format, do the format change
detection on the client.
Fixes #320 
> Fix re-exec capabilities over format bumps

- src/curl.c
This line of code is a recent addition, and I think it is more helpful for the end user to see the pretty-printed curl error message in addition to the error number.
> Pretty print check_network error messages

- .travis.yml
Because rst2man.py is called when the timestamps on *.rst are newer than
their associated man pages, we need to have rst2man.py just in case we
hit this condition for the build.
> travis: install rst2man dependency

- Makefile.am
- scripts/swupd-completion.sh
- test/functional/completion/basic/test.bats
When output was changed to stderr for user output, this broke
automatic generation of the bash completion function.
Add suitable redirection to the generation script to capture stderr.
Add test to check the generated file looks reasonable.
> Fix generation of swupd.bash

- configure.ac
- src/scripts.c
Instead of hardcoding systemctl commands to run post-update triggers,
add the ability to configure an executable path to be used when swupd
completes its update process. Similarly replace the use of a hardcoded
pre-update script path with a configurable executable path.
> Replace systemctl and pre-update commands

- .travis.yml
- Makefile.am
- configure.ac
- include/swupd.h
- src/archives.c
- src/download.c
- src/hash.c
- src/manifest.c
- src/packs.c
Use libarchive in order to make use of its security features and avoid
calling out to tar via a shell. The TAR_COMMAND is still used in
staging.c to complete the copy when a hardlink fails.
> Use libarchive instead of calling out to tar

- include/swupd.h
- src/bundle.c
- src/curl.c
- src/packs.c
- src/update.c
- src/verify.c
Fixes #352
This operation is fragile and can cause errors if a zero pack download
is interrupted resulting in an incomplete tar archive. A user reported
that having the incomplete pack around prevented the pack from being
re-downloaded and the content was incorrect so the bundle-add was not
completing. Instead of trying to resume a bundle-add pack download just
remove the old file and try again.
> Do not try to resume failed bundle-add pack downloads

- src/heuristics.c
Linux kernel sources are shipped in the /usr/src/kernel/<kernel_version>
directory. So, it need to be added as an exception in the is_state()
function.
Fixes #348
Debugged-by: Ornelas Aguayo, Jesus <jesus.ornelas.aguayo@intel.com>
Debugged-by: Mario Alfredo Carrillo Arevalo <mario.alfredo.c.arevalo@intel.com>
Signed-off-by: Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>
> heuristics: do not ignore /usr/src/kernel

- src/manifest.c
In commit e18eb69, retrieve_manifests() was refactored to support the mixer integration feature, but it introduced a double free of the "filename" pointer when following certain code paths.
One code path to reproduce the issue is when a Manifest.MoM is not present in the state directory, and swupd_curl_check_network() fails.  A free(filename) was being called immediately before swupd_curl_check_network(), and then again after jumping to the "out" label for the error condition.
Resolve the issue by resetting the filename pointer to NULL after freeing the memory to prevent a later double free. I also reset the url pointer to NULL at the second call site for similar reasoning.
> Fix double free issue

- test/functional/update/rename-ghosted/test.bats
- test/functional/verify/ghosted/test.bats
- test/functional/verify/picky-ghosted-missing/test.bats
Most of the functional tests properly reverted the chown operations in teardown(), but three of them were missing the reverts.
> Fix tests that are lacking chown reverts

- src/archives.c
Need to pass the same struct used in the operation to the
_archive_check_err helper.
This fixes issue of some Warnings appearing with "(null)" message,
since the writer did not had an error string associated.
Signed-off-by: Caio Marcelo de Oliveira Filho <caio.oliveira@intel.com>
> Fix warning message in archives

- src/scripts.c
See: https://github.com/clearlinux/clr-service-restart
If present, clr-service-restart can be used to dynamically determine
whether running daemons need a restart based on whether they have
been updated, or whether they are holding references to library code
that has been replaced on disk.
This is synchronous - the units that do need restarted are restarted
and their startup status is verified afterwards. Each restart is
printed on the screen to display what is happening. If a failure
happens, and the unit is a unit provided by the OS vendor, a telemetry
record is created.
Right now only whitelisted units are restarted automatically, and
there are no whitelisted units at this time. These will be slowly
added over time as we understand and learn which units are considered
'safe' to …
> Call clr-service-restart.

- include/swupd.h
- src/archives.c
- src/bundle.c
- src/clr_bundle_ls.c
- src/clr_bundle_rm.c
- src/curl.c
- src/delta.c
- src/download.c
- src/extra_files.c
- src/filedesc.c
- src/globals.c
- src/hash.c
- src/hashdump.c
- src/helpers.c
- src/lock.c
- src/manifest.c
- src/packs.c
- src/scripts.c
- src/search.c
- src/signature.c
- src/staging.c
- src/subscriptions.c
- src/telemetry.c
- src/update.c
- src/verify.c
- src/version.c
- src/xattrs.c
Fixes #357
Add free_string() function to insure code is consistently resetting
pointers to NULL after resetting dynamic memory. Use this helper
everywhere strings are being freed.
> Add free_string function and use everywhere

- docs/swupd.1
- docs/swupd.1.rst
The following flags have been added to the man page
--no-scripts
--nosigcheck
--ignore-time
--certpath
--time
--no-boot-update
> Add missing flags to man page

- src/delta.c
The function do_delta() is only called by try_delta() and both were
creating the string with the name of the staged file and performing
the file exists check. Pass the name to do_delta() and remove the
check.
This should not change the behavior.
> Remove redundant check and string creation in try_delta()

- src/curl.c
Loop wasn't taking into account the constant being set but empty. In
that case tok was set to NULL and stat was called with it. Replace
'do-while' with a 'while' to also perform the check the first time.
> Fix invalid call to stat when FALLBACK_CAPATHS is empty

- src/clr_bundle_ls.c
Should have been removed in
2111507a57c4b7ea660ba65e0436f51038c8fbb2 ("Don't show OS version after
the bundles"), but escaped.
> Remove unused variable

- src/globals.c
During initialization swupd may delete the state_dir to ensure it is
in the right shape. That means that by accident, passing "-S /" to any
command is dangerous.
Since neither /, /usr or /var are really useful as state dirs, let's
prevent some damage by not allowing them.
> Forbid certain state_dir values to prevent disasters

- Makefile.am
Now that all the commands are together in a single binary there's no
much reason to keep various different variables for each. Just
enumerate all the sources as part of swupd_SOURCES.
> Remove now unnecessary variables from Makefile.am

- swupd-add-pkg
The script should be calling init-mix to fully and correctly setup the mix
directory. Without this, the upstream url was never being recorded, and the
yum-mix.conf did not get the URL substituted during chroots phase.
> swupd-add-pkg: Fix upstream url not being filled in

- src/bundle.c
Just because /usr/share/mix exists, don't assume that it has good
content. Check that there is content _and_ we successfully moved to a mix
before trying to use any content out of it.
> bundle.c: Fix bundle-add/remove

- src/archives.c
In some cases packs may include files with entries of type "hard
link", that refer to previous files in the pack. Libarchive was
failing since it couldn't find the previous file in disk to archive,
because we change its output path.
Adjusting the hardlink target path (when it exists) fix the
issue. This is also what bsdtar does.
This patch was tested by simulating the update that goes from 19460 to
19580 with the desktop pack installed (that contains one hardlink in
the pack used by this update).
Fixes #351.
> Fix "Hardlink target error" when extracting

- src/search.c
- Show indication that bundle is installed.
When displaying a search result for a bundle display "installed" next to bundles that have been added to the system.
- ~~Reduce score for installed bundles.~~
~~The assumption here is that users use the search feature when they are looking for a bundle to install a certain file. For this case already installed bundles are not what the user is looking for so reduce the score by half.~~
~~@icarus-sparry has already expressed concern with the second patch. Anyone else use the search functionality to figure out which installed bundles they should remove?~~
Fixes #390
> search: special handling for installed bundles

- Makefile.am
- include/swupd-internal.h
- src/clean.c
- src/swupd.c
This command removes old files from statedir. The interface is a bit
opaque so there will be room to modify the policy later.
By default it will delete staged files that are older than
DAYS_TO_KEEP_FILES. For manifests this heuristic is not good as older
manifests might still be used for the current OS version being run, so
also ensure that those do not get deleted. This prevents 'swupd
search' to redownload files.
The default behavior should be suitable to use in combination with
automatic updates, to control the size of state dir. There is also an
--all option to remove all the state files regardless of dates and
usage.
To avoid "disasters" in case some paths are set wrong, the command
explicitly delete patterns of files create by swupd.
> Add 'swupd clean' command

- include/list.h
- src/list.c
- src/search.c
When reporting bundles for swupd search include their included bundles'
contentsizes as well for more accurate size reporting. For bundles that
are not installed on the client system, this skips any installed
includes and only reports contentsize for uninstalled includes. For
bundles that are installed on the system calculate the entire
contentsize for all includes and report this as the "installed size" of
the bundle.
When the scope is 'o' (one hit only) do not print size information.
Since only the first hit was taken it is unlikely that contentsize was
calculated for all that bundle's includes.
I performed a quick analysis on performance of tracking the included contentsizes to see if there was much of a slowdown with this …
> Report real contentsize for swupd search bundles

- src/manifest.c
2`*`10^12 rather than 2`*`10^9
> Fix a "preposterous check

- data/swupd-update.timer
We know these are cheap and our CDN takes care of the actual
bulk of the bandwith.
Spread the update checks between 45min0sec and 1hr33mins
effectively.
> Reduce the time between version checks.

- src/clean.c
The variable contents was not being properly set when early failures
happen in read_mom_contents.
Found with clang static analyzer.
> clean: fix returning garbage in failure cases

- src/list.c
The clone of strings lists was creating a copy of the items and adding
to the list, but still keeping the old ones around. Change the
function to just clone the items. This was causing invalid reads when
doing swupd search for a term that has matches, and causing crashes
for some users.
For the record, one of the valgrind reports:
==30978== Invalid read of size 1
==30978==    at 0x51FF680: __strcmp_ssse3 (in /usr/lib64/haswell/libc-2.27.so)
==30978==    by 0x407C1B: calculate_size (search.c:194)
==30978==    by 0x407C62: calculate_size (search.c:219)
==30978==    by 0x407C62: calculate_size (search.c:219)
==30978==    by 0x4075CD: apply_size_penalty (search.c:240)
==30978==    by 0x4075CD: do_search (search.c:715)
==30978==    by 0x4075CD: search_main (search.c:898)
==30978==    by …
> list: fix cloning lists of strings

- src/clean.c
It worked because state_dir is a global, but let's follow the same
approach as other functions and take the state directory as an
argument.
> clean: fix missing argument in function

- src/globals.c
The output is milliseconds, so tv_sec needs to be multiplied by
1000. Also format the output so the names are aligned.
> Fix wrong results when printing time stats

- docs/swupd.1
- docs/swupd.1.rst
Add "swupd verify" options that were missing from the documentation
(swupd.1.rst) but listed by the tool when calling "swupd verify -h".
The order was also slightly changed to be identical to the order used
by "swupd verify -h".
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>
> Update "swupd verify" documentation to cover all options

- .gitignore
- Makefile.am
- test/documentation/manpages/test.bats
Current idea is to have the manual pages stored in the repo in nroff
format, as well as restructured test format. Users can just use the
nroff. Add test to ensure that the pages match.
Fixes #316
Fixes #425
> Add test to ensure man pages are up to date

- src/bundle.c
- src/globals.c
- src/swupd.h
- test/functional/bundleadd/bad-manifest/lines-checked
- test/functional/bundleadd/fix-missing-file/lines-checked
If content_url is local, do not attempt certain certain download
retries. I've focused on changing only the spots that caused 'make
check' to sleep as a first step. But I agree the retry logic needs
some extra care as posted in #221.
This patch reduces the time of running 'make check' in my system from
2m44s to 24s.
> Avoid retries in local downloads for manifests and packs

- src/bundle.c
- src/check_update.c
- src/curl.c
- src/manifest.c
- src/packs.c
- src/search.c
- src/swupd-error.h
- src/update.c
- src/verify.c
Add a specific printf and separate failure code to indicate SSL cert
failures. This return code (24) will be returned to telemetry as well to
indicate this specific failure.
> Return meaningful errors for SSL Cert failures

- src/mirror.c
When /etc/swupd is created to hold mirror URL override files, set the
permissions to 0755.
Fixes #437
> Set mirror override path perm to 0755

- Makefile.am
- src/mirror.c
- test/functional/mirror/createdir-negative/lines-checked
- test/functional/mirror/createdir-negative/test.bats
- test/functional/mirror/createdir/lines-checked
- test/functional/mirror/createdir/test.bats
- test/functional/swupdlib.bash
Set /etc/swupd permissions to 0777 to let the default umask policy
handle stripping bits appropriately.
> Let umask sort out mirror conf dir perms

- docs/swupd-add-pkg.4
- docs/swupd-add-pkg.4.rst
- swupd-add-pkg
Instead of doing this behind the user's back expect them to do it
themselves. This also removes the inconsistencies of running some
commands with sudo -E and others without -E. If users want to provide -E
let them do it themselves.
> swupd-add-pkg: remove sudo invocations

- src/autoupdate.c
- src/check_update.c
- src/clean.c
- src/clr_bundle_add.c
- src/clr_bundle_ls.c
- src/clr_bundle_rm.c
- src/helpers.c
- src/info.c
- src/main.c
- src/mirror.c
- src/swupd.h
- src/update.c
- src/verify.c
- test/functional/ignore-list
- test/functional/mirror/createdir-negative/lines-checked
- test/functional/mirror/createdir/lines-checked
swupd-client is properly open sourced and licensed. The copyright header
is unnecessary, confusing, and causes issues for scripts parsing output.
> Remove copyright header messages

- src/globals.c
- src/update.c
Update mixer integration to key off the .valid-mix flag file to check if
a mix exists. Also update the .clearversion filename to upstreamurl (it
has changed in upstream).
> Update mixer integration to use latest features

- .travis.yml
- scripts/findstatic.pl
- src/bundle.c
- src/helpers.c
- src/manifest.c
- src/search.c
- src/swupd.h
- src/update.c
- src/verifytime.c
Fixes #448
Make a number of functions static, and bodge around the extra symbol
that gcc adds (__gnu_lto_v1) when compiling with -flto=4
> Fix findstatic warnings

- swupd-add-pkg
swupd-client expects a .valid-mix file to exist in MIX_DIR when a valid
mix exists. Create this file after creating the mix.
> swupd-add-pkg: write valid-mix flag file

- src/manifest.c
- src/update.c
When a new upstream version is detected the new local mixer build must
be done before manifest uniqueness is checked. This is due to the fact
that os-core can change in the upstream version, so it has to be
re-built locally against the upstream content in order to avoid false
positives for file colisions.
Also add additional files are files that change on the system due to the
local mix. Add these to the ignore list for file colision checks.
Fixes #446
> Fix automatic mix updates for mixer integration

- src/update.c
If current_subs was cloned free the list structure. Free the list
and subscription data otherwise.
Fixes issue #363
> Update: Fix memory leak on subscription list

- src/search.c
Fixes #454
Added the -n/--nosigcheck parameter to search, based on the other subcommands that
already have nosigcheck.
I tested this by invalidating Swupd_Root.pem and testing the failing
and passing cases - without nosigcheck and with nosigcheck
respectively.
> search: Add --nosigcheck

- src/update.c
- test/functional/update/boot-file/lines-checked
- test/functional/update/boot-skip/lines-checked
- test/functional/update/include-old-bundle-with-tracked-file/lines-checked
- test/functional/update/include-old-bundle/lines-checked
- test/functional/update/include/lines-checked
- test/functional/update/missing-os-core/lines-checked
- test/functional/update/re-update-bad-os-release/lines-checked
- test/functional/update/re-update-required/lines-checked
- test/functional/update/skip-scripts/lines-checked
- test/functional/update/statedir-bad-hash/lines-checked
- test/functional/update/use-full-file/lines-checked
- test/functional/update/verify-fix-path-hash-mismatch/lines-checked
- test/functional/update/verify-fix-path-missing-dir/lines-checked
Message informing that the system was successfully updated should be
the last message. Having a message that looks like an error as the
last message in an update can be confusing for users.
> Update: Change log order to have a clearer output

- src/curl.c
- src/staging.c
- src/update.c
All #warnings messages on swupd code were related to tasks to be performed
in the future and not real code warnings. Using the TODO comment, that is
already used for other tasks.
It's too annoying to see warning messages on compile time and having them
makes a bit harder to noticed when we are introducing real compiler warnings.
> Remove #warnings from code. Use TODO instead

- Makefile.am
- src/curl.c
- src/delta.c
There's no way to inforce braces on single line ifs using clang-format.
Adding a grep to look for ifs without a bracket so we can at least
warn users about that.
> Enforce braces on single line ifs in make compliant

- src/bundle.c
- src/clr_bundle_rm.c
- src/swupd.h
- test/functional/bundleremove/include-nested/lines-checked
- test/functional/bundleremove/include/lines-checked
- test/functional/bundleremove/remove-file/test.bats
- test/functional/bundleremove/remove-multiple/test.bats
The current remove_bundle() function was designed to only be called
once, but for multiple bundle removals, it is currently called
multiple times.
This commit refactors this function so the bundle removal code can
handle multiple bundles at once.
Fixes #449
> Refactor bundle-remove to handle multiple bundles

- src/manifest.c
Mixin re-creates the os-core bundle when creating a local mix. This
causes the corresponding os-core-update-index bundle-info file to have
changes to the metadata listed inside. Treate this as mixin state and do
not check hashes for this file.
> Add os-core index to mixin state

- src/bundle.c
- src/globals.c
- src/helpers.c
- src/manifest.c
- src/packs.c
- src/search.c
- src/verify.c
Some people were complaining about memory leaks in swupd. I fixed the ones I found using -fsanitize=address and running the tests.
> Fixing a bunch of memory leaks

- src/verify.c
The --fix flag is not supported for mixed systems due to special
handling of some os-core files being required, which is not currently
done. Until this is done and mixer state is handled properly ignore any
mixer related state when performing a verify --fix.
Fixes #493 
@bktan8
> verify: Ignore mix state when fixing to version

- src/delta.c
When delta application failed due to swupd being unable to calculate the
hash of the from file or a hash-mismatch against what was expected print
an error message that indicates there is a corrupted file.
Fixes #469
> delta: improve delta failure message

- docs/swupd.1
- docs/swupd.1.rst
- src/swupd-error.h
Additionally remove the unused EPREP_MOUNT error code.
Fixes #296
> manpages: add return-code documentation

- src/clean.c
- src/swupd.h
- src/update.c
Separate the main statedir clean functionality into a callable function
and call it after performing an update. This helps clean up unused
files that bloat the state directory on a regular basis and helps
prevent the state directory from getting into a weird state over
updates.
Fixes #378
> clean: separate into callable function and use in update

- src/bundle.c
- src/clr_bundle_add.c
- src/globals.c
- src/swupd.h
Prevoiusly, when running bundle-add there was no check in
place to verify free storage before attempting to add the
new bundle.
Added this check, a warning message, and a flag to ignore
the message if desired.
Some functionality from search was moved out and is re-used
for calculating bundle sizes.
related to issue #266
> Add free space check before adding bundles

- docs/swupd.1
- docs/swupd.1.rst
Added a description for the new --skip-diskspace-check flag
to the bundle-add section of the swupd manpage.
Fixes #506
> manpage: Add --skip-diskspace-check to bundle-add

- test/functional/update/slow-server/test.bats
When running all tests at the same time using make -j check,
update/slow-server and check-update/slow server were trying to start
the slow server at the same port.
> test: Use different ports for tests to avoid colision

- src/autoupdate.c
It may be a violation of the user's IT policy to disable automatic
updates because of the security implications of an out-of-date system.
Print a warning when the user does this.
> autoupdate: print policy warning when disabling

- src/bundle.c
- src/extra_files.c
- src/hashdump.c
- src/helpers.c
- src/list.c
- src/manifest.c
- src/staging.c
- src/subscriptions.c
- src/update.c
- src/verify.c
- Use strdup_or_die instead of strdup + abort when possible
- Adding some aborts() on out of memory errors
- Removing unnecessary aborts().
- Improve error handling on check_manifests_uniqueness()
- Improvements on mk_full_filename()
> Aborts and error handling

- .travis.yml
- src/filedesc.c
- src/helpers.c
- src/swupd.h
- test/functional/ignore-list
The readlink call was being used inefficiently (it has a lousy api).
Close extra file descriptors that are passed in to us, so we don't
complain if they are open at the end.
> fix file descriptor leak check.

- src/manifest.c
The 'I' flag will be used to represent iterative manifests once the
feature becomes available. For now we need to ignore this flag so the
feature can be implemented in mixer before implementation here. Before
this patch manifest parsing would fail if it encountered an 'I' flag.
The iterative manifests will be published and included in the
Manifest.MoM before actually being used by client, which is why it is
important to ignore and not fail here.
> manifest: ignore I flag in manifest

- src/manifest.c
> manifest: use configuration variables not hardcoded strings

- test/functional/testlib.bash
Diff -u is used in previous test library and it has an easier to read output.
> testlib: Print the output differences using diff -u

- Makefile.am
- src/bundle.c
- src/fs.c
- src/swupd.h
- src/verify.c
This change adds some simple space checking on the new 'bundles' to
install when using verify.
This assumes that if you pass --install to verify you intend
to install all bundles to a 'new' folder (no other bundles installed).
This could warn erroneously if there are previously installed bundles or partially
installed bundles, because 'contentsize' could be more than the size
that's actually required to install those files.
Fixes #328
> verify: When --install is specified, warn on disk full

- src/version.c
Fixes #539
To find the latest version in the MIX_STATE_DIR swupd must look under
the correct directory versioned after the format number of the current
system. This is a change to mixer that auto-populates the format to the
system on which it is running if the mixer.state file does not exist.
Since mixer.state is not managed by the user when interacting with mixin
we need to use the format number on the system to find the latest
version. Old mixer behaviour was to default to 1 for the format.
> migrate: read format from file system

- Makefile.am
- test/documentation/manpages/test.bats
The manpage tests were recently removed due to occasional test failures that were raised. I spent some time debugging the issue and root caused the issue.
So, I've reverted the commit that the removed the tests and fixed the problem in the second commit.
> Re-enable manpage tests

- test/functional/README.md
- test/functional/bundleadd_v2/add-boot-file.bats
- test/functional/bundleadd_v2/add-include.bats
- test/functional/bundleadd_v2/add-verify-fix-path.bats
- test/functional/bundlelist_v2/list-deps-flat.bats
- test/functional/bundlelist_v2/list-deps-nested.bats
- test/functional/bundlelist_v2/list-has-dep-nested-not-installed.bats
- test/functional/bundlelist_v2/list-has-dep-nested-server.bats
- test/functional/bundlelist_v2/list-has-dep-nested.bats
- test/functional/bundleremove_v2/remove-boot-file.bats
- test/functional/bundleremove_v2/remove-include-nested.bats
- test/functional/bundleremove_v2/remove-include.bats
- test/functional/bundleremove_v2/remove-os-core.bats
- test/functional/ignore-list.global
- test/functional/testlib.bash
This pull request includes several bug fixes in the test library and also makes a few improvements in it.
Improvements:
- Export some more variables that are useful for some tests.
- Improves on how content size is read from a manifest.
- Allows adding dependencies to newer versions not only version 10 (default one).
- Decrease the file count and content size when removing something from a manifest.
- Updates the test template generated by the test generator with a more common output.
- Adds usage info in a couple of functions that were missing it.
- Adds the capability of creating empty test environment (with no os-core bundle).
- Removes an unnecessary directory in the creation of "default" bundles.
- Adds the capability of using existing files in the test bundles.
> Bug fixes and improvements for the test library

- test/functional/README.md
- test/functional/bundleadd_v2/add-bad-hash.bats
- test/functional/testlib.bash
This commit add the following two functions to testlib which will be used in upcoming PRs:
- add_to_pack
- update_manifest
Both functions aim to make those actions which are very common in tests in a consistent manner and less error prone.
> Adding two more functions to testlib

- test/functional/README.md
- test/functional/bundleremove_v2/remove-boot-file.bats
- test/functional/testlib.bash
Normal test environments come with a minimal version of os-core
bundle by default (only one file and the tracking file). Users
also have the option of not having os-core at all with the -e
"empty" option.
This commit adds another option "-r" for creating a test environment
that includes a more complete version of the os-core bundle,
with a couple of useful files: os-release and format. This type
of bundle can be useful when working with some type of tests like
updates.
> Ability to create environment with complex bundle

- test/functional/testlib.bash
Some functions from the test library can be used by end users to modify some object from their test environment, for example using the add_dependency_to_manifest they can add one or many dependencies to a bundle's manifest.
After modifying a bundle's manifest, a few subsequent actions need to occur in order for the objects to still be valid, the manifest's tar needs to be re-created, since the manifest's hash has changed, the MoM needs to be updated with this new hash, etc. 
To minimize the actions an end user needs to do, most of these activities are automatically performed by most library functions. However if the function is being called by another function which expects to perform many updates to the same object, it may not be the best option to be re-creating those tars and updating …
> Testlib partial updates for manifests

- docs/README.rst
- docs/swupd.1
- docs/swupd.1.rst
- src/autoupdate.c
- src/bundle.c
- src/curl.c
- src/helpers.c
- src/heuristics.c
- src/search.c
- src/verify.c
- src/xattrs.c
- src/xattrs.h
Errors reported by codespell (https://github.com/codespell-project/codespell)
> Fixing typos and orthography errors on docs and codebase

- src/search.c
Instead of reserving PATH_MAX bytes for the filename (of each result),
allocate it dinamically. This should use less memory overall, at the
cost of making more small allocations.
> search: Allocate the filename for each result dinamically

- test/functional/README.md
- test/functional/testlib.bash
This PR adds a couple of function which are very useful when working with tests that require multiple update versions of a bundle.
- update_bundle: allow users to create different kind of updates for a bundle between two versions in the server side content.
- bump_format: automatically creates an increase in the format version used in manifests, this requires two versions to be created with an update is os-core, os-core will update the os-release and format files.
> Adding functions to update bundles and bump format

- src/bundle.c
- src/swupd.h
- src/update.c
When adding included manifests during an update the add_subscriptions
function is used, this function returns a value of either add_sub_ERR=1,
or add_sub_BADNAME=4 when it fails to add a subscription, and the code
is currently considering any value > 0 to be a successful value.
This commit fixes the issue by making sure the add_subscriptions
function doesn't return a code of 1 or 4 which would mean it failed
adding a subscription.
> Return error if adding subscriptions fails

- test/functional/testlib.bash
When updating the manifest version we were replacing any line with the word
version to "version: new_version". This is a problem now that we are adding
a minversion field to the manifest. That could be a problem too when there
was a file named version.
This pull request fixes one problem that is going to be introduced by #580 and #585. If you use both commits minversions of all MoMs created used create_version will have minversion == version, unless you explicitly set the minversion
> testlib: Add guards to sed to avoid incorrect replaces

- Makefile.am
- test/functional/testlib.bash
- test/functional/update/update-minversion.bats
Soon, a minversion header field will be included in the MoM. This change
updates the test library to add a minversion header field to MoMs and adds
functions to create a minversion update. Also, the skip-verified-fullfiles
test was replaced by the update-minversion test. The update-minversion test
verifies that unchanged files with a version bump caused by a minversion
update are skipped during an update.
> Add minversion support to testlib

- src/manifest.c
This commit fixes a memory leak with the dir variable in the retrieve_manifests function.
> Fixing memory leak in retrieve_manifests

- docs/swupd.1
- docs/swupd.1.rst
- src/globals.c
- src/swupd.h
- src/update.c
- swupd.bash
After running an update, the state directory is cleaned up.
Sometimes it is useful to be able to peek at the state directory
after an update, this is specially true when testing updates,
this way tests can verify what manifests were downloaded during
the update.
This commit adds the --keepcache option to swupd update so it can
be used when writing tests for updates.
> Adding the --keepcache option when doing updates

- Makefile.am
- src/globals.c
- src/helpers.c
- src/manifest.c
- src/subscriptions.c
- src/swupd.h
- src/update.c
- swupd.bash
- test/functional/bundleadd/add-with-iterative.bats
- test/functional/testlib.bash
- test/functional/update/update-include-old-bundle-with-tracked-file.bats
- test/functional/update/update-iterative-and-full.bats
- test/functional/update/update-iterative-bad-name.bats
- test/functional/update/update-iterative-download-fail.bats
- test/functional/update/update-iterative-from-previous-version.bats
- test/functional/update/update-iterative-has-dependency.bats
- test/functional/update/update-iterative-has-new-dependency.bats
- test/functional/update/update-iterative.bats
- test/functional/update/update-missing-os-core.bats
This PR enables the use of an iterative to manifest in swupd client, which only contains the things that need to be updated, therefore reducing the download time, the amount of memory needed to load that manifest and the processing time for parsing it.
Closes #558
> Iterative manifest

- Makefile.am
- configure.ac
- src/main.c
- src/swupd-build-opts.h
- test/functional/ignore-list
When invoking swupd info or swupd --version print more information about
compile-time configuration. This feature was requested after a bug was
introduced to an unreleased Clear Linux build when swupd was built with
the wrong format ID. This allows QA to determine exactly which
compile-time options were set during runtime without inspecting the
binary.
> Add more compile options to info and --version

- src/globals.c
If the -t parameter is set for a given empty directory, then
the time queue will be empty causing that the `TAILQ_FOREACH_REVERSE`
macro segfaults.
The proposed solution is to check if the head is NULL at the beginning
of the `print_time_stats` function.
Fixes #600
Signed-off-by: Erich Cordoba <erich.cm@yandex.com>
> Avoid print time stats if the queue is empty.

- src/update.c
current_subs memory wasn't released when we had errors on version checks.
As a test for that was recently introduced we started to have errors on
travis for that.
> update: Fix memory leak in update_main()

- src/bundle.c
- src/manifest.c
- src/search.c
- src/swupd.h
- src/update.c
- src/verify.c
Delta manifests are no longer used, so removing support for them. This
change removes the try_delta_manifest_download function which was used
to download manifest deltas. After removing this function, the 'current'
and 'file' parameters were no longer used by the retrieve_manifests
function. This had a ripple effect that removed unused parameters from
a variety of other functions.
> Remove manifest delta support

- docs/swupd.1
- docs/swupd.1.rst
- src/swupd-error.h
- src/swupd.h
- test/functional/testlib.bash
Linux programs return code should be a number between 0 and 255, so 404 is an
invalid return code. Removing it from docs and from swupd-error.h file.
As it wasn't being used, this won't be a problem.
> Remove 404 from the list of possible swupd return codes

- test/functional/testlib.bash
- test/functional/verify/verify-format-mismatch-override.bats
- test/functional/verify/verify-format-mismatch.bats
- test/functional/verify/verify-picky-ghosted-missing.bats
- test/functional/verify/verify-picky-ghosted.bats
Some time ago the "-u" option of the create_test_environment and
create_version functions was renamed to "-r". Four of the verify
tests were not updated, so they were crashing during the setup,
while trying to create the test environment, so the test would not
be run since the setup failed but the teardown would still run and
the teardown would attempt to delete a non existant test environment
which would cause the destroy_test_environment to exit the script
causing an inconclusive test result.
This commit fixes the issue by doing the following actions:
- Fixes the tests by using the correct option "-r".
- Modifies the destroy_test_environment function so it does not exit
if a test environment doesn't exist, but instead it just returns a non
zero code and warns the user so the teardown …
> Fix a bug in some verify tests

- test/functional/testlib.bash
I see the checkupdate/chk-update-slow-server test fail when the `http_proxy` env variable is set, but `no_proxy` is not set.
Resolve the issue by adding "localhost" to `no_proxy` if needed, since the test web servers run on localhost.
> test: add localhost for no_proxy if not present

- Makefile.am
- test/functional/bundleadd/add-no-signature.bats
Adding missing tests for the --nosigcheck option in the
bundle-add command.
> Adding tests for bundle-add --nosigcheck

- configure.ac
- src/swupd-build-opts.h
Print the compile-time configuration systemdsystemunitdir.
Option was incorrectly removed on 74b2d526 so it didn't get into commit
that added extra information to --version (204e2a4b)
> Add systemd unitdir to swupd --version output

- src/bundle.c
- test/functional/bundleadd/add-existing.bats
- test/functional/bundleadd/add-rc.bats
Previously, the only way to get a return code of 0 (success) during
a bundle-add operation was if everything that was attempted to be
added had been successful. That means that bundle-add command was
returning EBUNDLE_INSTALL whenever it would try to add a bundle that
was already installed.
This commit changes the return code of such operation since it was
determined that it is a more appropriate behavior to consider an
attempt to add a bundle that is already added as successful, even when
no bundle was added during the operation.
Closes #510
> bundle-add to return 0 if bundle already installed

- Makefile.am
When mixing variables and targets make was attributing some variables as
targets. Because of that make install was running some tests defined in TEST
variable. Reordering all variable definitions to make sure all are defined
before first target definition.
Fix travis error in #653
> makefile: Group variables and targets

- src/filedesc.c
- src/globals.c
- src/helpers.c
- src/manifest.c
- src/search.c
- src/swupd.h
- src/verifytime.c
- src/version.c
Various functions, like strtol, were used to convert strings to numbers.
Frequently, the results of these conversion functions were stored in
variables with types that did not match the function return value. As a
result, there was a potential risk that an overflow would occur when
type casting the string conversion function result to store it in a
mismatched type.
The most common case is to convert a string to an int, so this commit
creates the strtoi_err function which converts a string to an int and
provides error handling. Also, the error checking for other string to
number conversions was improved by adding error handling with errno.
Fixes #601
> Safely convert strings to numbers

- Makefile.am
- src/extra_files.c
- src/swupd.h
- src/update.c
- src/verify.c
- test/functional/testlib.bash
- test/functional/update/update-re-update-bad-os-release.bats
- test/functional/update/update-re-update-required.bats
- test/functional/verify/verify-picky-downgrade.bats
When you do a "verify --fix --picky -m older_version", and one
or more of the currently installed bundles didn't exist back then,
a non useful error message was being used, and the verify operation
would fail.
This commit makes the following changes.
1) With this commit, if the mentioned situation happens, the verify
operation will still be stopped, but a useful message will now be
displayed to inform the user of the situation, and he/she will be
presented with an alternative to proceed using the --force option.
2) If the user uses the --force option, the user will still be warned
but the verify operation will continue and the offending bundles will
be removed from the system.
3) Fixes a bug when using verify --picky. Only files that were orphaned
were being counted as files being removed …
> Use verify --fix --picky with older versions

- test/functional/README.md
Some functionality was added to the test library to allow printing
function availability plus usage information.
This commit adds that info to the readme of the library to keep it
accurate. It also adds a table of groups for the tests which will
be useful soon when we start using IDs in the tests.
> Adding info about "Getting help" to testlib readme

- src/bundle.c
- src/verify.c
Add a timer counter to print how long run_scripts() take on verify and
bundle-add commands. Note that this is already in place for update.
> time: record time of scripts execution on verify and bundle-add

- test/functional/README.md
- test/functional/testlib.bash
- test/functional/update/update-slow-server.bats
When running tests, there is the possibility of preserving your
test environment for debugging purposes.
We were preserving the environment by skipping the execution of
the destroy_test_environment function when the DEBUG_TEST env
variable was set. This had one limitation, this was being done in
the default teardown function, so if the user would define his own
teardown then the DEBUG_TEST had no effect, the same if the user
used global_teardown instead. Another limitation the current
implementation had was that when an environment had been preserved
if the user would forget to clean it up manually before re-running
the test it would cause unexpected results in the test.
This commit removes both limitations by looking for the DEBUG_TEST
variable directly within the …
> Improvements for DEBUG_TEST in test library

- .gitignore
- test/real_content/swupd_update.bats
Tests added:
- Check if bundle-list --all is working (because this affect the next tests)
- Check if we can install an old version of clear and update interactively
until last release
- Check if we can install and old version and update to the most recent one
As this test takes a really long time to run, I'm not adding it to the
tests list to be executed to make check, but this can be used to validate
swupd before a release.
> test: Check if swupd is able to perform updates in last releases

- configure.ac
Configure was printing the error:
14:13:44 ./configure: line 14047: ]: command not found
It was harmless though.
> configure: Remove trailing ]

- Makefile.am
- test/functional/verify/verify-format-mismatch-override.bats
- test/functional/verify/verify-latest-missing.bats
The list is missing a "\" at the end of one test which is causing
a group of tests to be ignored by the makefile, therefore they are
not being run.
> Fixing a bug in the test list in Makefile

- src/verify.c
- test/functional/verify/verify-boot-file-mismatch-fix.bats
- test/functional/verify/verify-boot-file-mismatch.bats
- test/functional/verify/verify-check-missing-directory.bats
- test/functional/verify/verify-format-mismatch-override.bats
- test/functional/verify/verify-picky-downgrade.bats
There is a missing line break that shows up When running
the "swupd verify" command and there is a hash mismatch.
The output looks like this:
```
$ sudo swupd verify
Verifying version 25590
Verifying files
...1%Hash mismatch for file: /usr/bin/tmux
...100%
Inspected 292278 files
1 files did not match
Verify successful
```
This commit fixes the issue by adding a line break at the 
beginning of the output.
This PR depends on PR #670  as soon as that one merges I will rebase this one.
> Adding a missing line break in the verify command

- src/signature.c
The ERR_remove_thread_state() function is deprecated as the thread
handling and many memory management operatoins have been re-written to
be internally handled by the API. The error code should be retrieved
by the proper function now from X509 store contexts.
> [RFC] - Update signature verification for OpenSSL 1.1

- src/filedesc.c
Curl isn't closing urandom and random when using openssl 1.1. As it's something
out of our control and this won't create any resource leak problems, we're not
reporting that anymore.
This fd leak report is triggered when any https download is performed by swupd
> curl: Don't warn about curl fd leaks

- .travis.yml
- autogen.sh
- test/functional/bundleadd/add-client-certificate.bats
- test/functional/bundlelist/list-client-certificate.bats
- test/functional/bundleremove/remove-client-certificate.bats
- test/functional/checkupdate/chk-update-client-certificate.bats
- test/functional/checkupdate/chk-update-slow-server.bats
- test/functional/search/search-client-certificate.bats
- test/functional/server.py
- test/functional/testlib.bash
- test/functional/update/update-client-certificate.bats
- test/functional/update/update-slow-server.bats
- test/functional/verify/verify-client-certificate.bats
Some tests (tests using web servers) wrote files to /tmp which were hard to clean up. This change moves the files/directories that were written to /tmp to more obvious locations. The trusted certificate store is now written to the top level directory of the repo and the other files are written to their corresponding test environment directories. Also this change adds a trap to clean up tests when they are interrupted.
Fixes #650
> Test: file cleanup

- Makefile.am
- src/update.c
- test/functional/update/update-bundle-removed.bats
If a bundle happens to be removed from the content server (or mix) it
means the bundle won't be in the MoM anymore, so the bundle in the
system will look like an invalid bundle. When this happens the update
is currently stopping.
This PR fixes this so If this happens, the user is informed, and
the update continues.
Closes #624
> Continue with update when a bundle was removed upstream

- src/archives.c
Ignore function return code as we don't need to check if operation is
fatal or not at this point.
> archive: Ignore return code of function

- src/verifytime.c
We can't assume that the file wasn't deleted between the execution of a
stat and a fopen. Printing error only when fopen fails.
> verifytime: Fix TOCTOU problem

- Makefile.am
- src/extra_files.c
- src/verify.c
- test/functional/verify/verify-add-missing-directory.bats
- test/functional/verify/verify-add-missing-include-old.bats
- test/functional/verify/verify-add-missing-include.bats
- test/functional/verify/verify-boot-file-deleted.bats
- test/functional/verify/verify-boot-file-mismatch-fix.bats
- test/functional/verify/verify-boot-file-mismatch.bats
- test/functional/verify/verify-boot-skip.bats
- test/functional/verify/verify-check-missing-directory.bats
- test/functional/verify/verify-directory-tree-deleted.bats
- test/functional/verify/verify-empty-dir-deleted.bats
- test/functional/verify/verify-fix-version-mismatch-override.bats
- test/functional/verify/verify-fix.bats
- test/functional/verify/verify-format-mismatch-override.bats
- test/functional/verify/verify-ghosted.bats
- test/functional/verify/verify-install-directory.bats
- test/functional/verify/verify-install-latest-directory.bats
- test/functional/verify/verify-picky-downgrade.bats
- test/functional/verify/verify-picky-ghosted-missing.bats
- test/functional/verify/verify-picky-ghosted.bats
- test/functional/verify/verify-skip-scripts.bats
Running "swupd verify" should be a dry-run of running
"swupd verify --fix", meaning that "swupd verify" should find
the same issues to be resolved than "swupd verify --fix" but it
should just inform about them while --fix should inform + fix them.
In occasions this does not happen, for example when there are
tracked files that need to be removed from the system.
Closes #607
Closes #536 
> Add consistency between verify and verify --fix

- src/verifytime.c
Modify the set_time() function used in verifytime.c to take a single
argument instead of two. The second argument that was previously used
can easily be derived from the first and it avoids situations where
these two are not coherent (which happens to the case in the current
version of verifytime.c)
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>
> verifytime: modify set_time() to take single argument

- test/functional/testlib.bash
The check-update tests should use a group code of CHK, but the
test library was using AUT incorrectly which belongs to the autoupdate
tests.
> Correct test group code for checkupdate

- test/functional/verify/verify-install-bad.bats
- test/functional/verify/verify-install-multiple.bats
- test/functional/verify/verify-install-no-fullfile-fallbacks.bats
- test/functional/verify/verify-install-no-zero-packs.bats
- test/functional/verify/verify-install.bats
Some verify --install tests were submitted some time ago before we
started using IDs for tests, so these tests are missing the ID.
This commit add those missing IDs and make a couple of improvements
in the tests.
> Adding ID to install tests

- test/functional/update/update-slow-server.bats
There are some variables left over from commit
897f5d44c896bcd7f5a8048e262ff1c131db88fa
> Clean up unused variables from test

- Makefile.am
- src/helpers.c
- src/verifytime.c
- src/verifytime.h
- src/verifytime_main.c
Instead on counting with the verify time in the system, link swupd
with verifytime lib.
This reduces one point of failure of swupd on recovering a corrupt system.
> Link swupd with verifytime

- Makefile.am
- test/functional/bundlelist/list-all.bats
- test/functional/bundlelist/list-client-certificate.bats
- test/functional/bundlelist/list-deps-flat.bats
- test/functional/bundlelist/list-deps-invalid-bundle.bats
- test/functional/bundlelist/list-deps-nested.bats
- test/functional/bundlelist/list-has-dep-nested-not-installed.bats
- test/functional/bundlelist/list-has-dep-nested-server.bats
- test/functional/bundlelist/list-has-dep-nested.bats
- test/functional/bundlelist/list-installed.bats
- test/functional/bundlelist/list-no-deps.bats
- test/functional/bundlelist/list-none-has-deps.bats
Adding an ID to all bundle-list tests and rewording some of the
test descriptions to make it more readable.
> Adding ID to bundle-list tests

- src/bundle.c
- src/helpers.c
Swupd state dir should be masked as 700, but we can't mask all subfolders
as 700. This is particularly a problem because /var and /var/lib/ shoudn't
be 700, but /var/lib/swupd should. So creating all folders with current
umask and using chmod syscall to set only the swupd statedir diretory to
root only
Also, stop using mkdir_p where are no longer needed
Fixes #655
> helpers: Don't enforce umask on mkdir_p, just force that when needed

- src/verifytime.c
- src/verifytime_main.c
There was some confusion about shell return code and bools.
Shell returns 0 for true and bools are 0 for false.
> verifytime: Fix return value of verify_time function

- src/check_update.c
- test/functional/checkupdate/chk-update-client-certificate.bats
- test/functional/checkupdate/chk-update-new-version.bats
- test/functional/checkupdate/chk-update-no-server-content.bats
- test/functional/checkupdate/chk-update-no-target-content.bats
- test/functional/checkupdate/chk-update-slow-server.bats
- test/functional/checkupdate/chk-update-version-match.bats
When the system time is way off, the certificate validation will
fail. For this reason, many swupd commands attempt to fix the
system time if wrong. check-update was not doing this so the
command would fail in this situation.
This commit adds a verification for this so check-update attempts
to fix the system time and continue instead of failing.
Closes #678 
> Continue check-update when time is not correct

- src/timelist.c
- test/functional/bundleadd/add-install-time.bats
Changing the way time is displayed when using the --time option so it
shows as a tree view so it is easier to see what items are sub-tasks
of other tasks.
> Prettifying the --time output

- src/check_update.c
- src/clr_bundle_add.c
- src/clr_bundle_rm.c
- src/update.c
The --force option is included in bundle-add, bundle-remove,
check-update, update and verify, but it is really only used in
verify.
This commit removes the option from the commands that are not using
it so it is not misleading to users. If at some point we need to
implement somthing with --force it can be added back at that point.
Closes #636
> Removing option --force where is not needed

- src/main.c
Standard locale on C applications is C and we use in clearlinux UTF-8
for file names. Libarchive checks the program locale to convert
filenames so we need to set this.
According to setlocale documentation, setlocale(LC_ALL, "") sets the locale
to system default (in the case of ClearLinux, UTF-8).
More information on the libarchive problem:
https://github.com/libarchive/libarchive/wiki/Filenames and
https://github.com/libarchive/libarchive/issues/587
Fixes #445
> locale: Set locale to system locale

- .gitignore
- src/manifest.c
- swupd.bash
- test/real_content/swupd_update.bats
swupd copies the latest MoM to /usr/share/clear/bundles/.MoM so we
can use it for bash completion. The problem is that this directory
is tracked by clearlinux and because of that "swupd verify --picky"
will list this file as an extra file. And "swupd verify --fix --picky"
will remove that file.
This commit fixes the issue by changing the location where the .MoM
is copied to being this an untracked location, so the file won't be
removed.
Closes #632
> Move the MoM from bundles dir to /var/tmp/swupd

- src/manifest.c
- swupd.bash
As we aren't saving the MoM in a directory we were reading to look for
bundles, we don't need to save it as a hidden file.
Suggestion of @phmccarty
> Don't save the latests Manifest as a hidden file

- test/functional/testlib.bash
There was a bug defining the path for a test in the test generator
that was causing the script to fail if the command was executed from
the wrong path.
> Fix the path used by the test generator

- scripts/assert-certificate-validity.sh
Newer versions of openssl require a valid purpose so
pass this in for the cert check.
Signed-off-by: David Klimesh <david.j.klimesh@intel.com>
> Update verify to include purpose for cert check

- Makefile.am
- src/helpers.c
- src/manifest.c
- src/scripts.c
- src/staging.c
- src/swupd.h
- src/sys.c
- src/sys.h
- src/update.c
System API is a very convenient way on executing external commands, but it has
some problems for some usages. System always launches a shell to execute the
desired command, so we can be affected by environment variables (like PATH) and
shell globbing.
We can avoid most of the environment variables affecting the swupd result by
using the full path of the program being executed, but making sure the shell
won't expand all wildcards is tricky and specially dangerous for some commands
that we need to run, like cp, mkdir, etc.
So to make sure no globbing will be performed we can use fork+execve to run
commands instead of system.
> sys: Add run_command() function to replace some usages of system()

- src/manifest.c
- test/functional/bundleremove/remove-basics.bats
- test/functional/bundleremove/remove-boot-file.bats
When running bundle-remove to remove a bundle the number in "Total
deleted files" is often wrong. This is happening because when deleting
the files from a bundle sometimes we start by deleting a directory
(with all the files within it), so all the files that got deleted are not
accounted for, only one file will be counted as deleted (the directory),
this will yield to an incorrect count of deleted files.
This commit fixes this issue by printing the total number of
files that should be deleted, minus those that failed to be deleted,
instead of counting those that succeeded.
Closes #690
> Reporting of deleted files in bundle-remove

- Makefile.am
- src/mirror.c
- test/functional/mirror/mirror-createdir-negative.bats
- test/functional/testlib.bash
- test/functional/update/update-with-mirror.bats
- test/functional/update/update-with-old-mirror.bats
- test/functional/update/update-with-slightly-old-mirror.bats
- test/functional/verify/verify-fix.bats
- test/functional/verify/verify-picky-downgrade.bats
- test/functional/verify/verify-picky-ghosted-missing.bats
- test/functional/verify/verify-picky-ghosted.bats
- test/functional/verify/verify-picky-whitelist.bats
- test/functional/verify/verify-picky.bats
There are a couple of problems when the user has a mirror set up,
and tries to update. The first one is that in the case where the
user is using the -p option and a mirror, the version of the mirror
was failing to be retrieved since the path_prefix was being added
to the path twice. The second problem was that when the mirror being
used by the user was stale, the mirror was being unset but some values
had already being cached, causing the update function to fail.
This PR fixes the issues and add a few tests to validate the correct behavior.
> Fixes a bug in update when using mirrors

- Makefile.am
- src/bundle.c
- test/functional/bundleadd/add-experimental.bats
This commit adds the ability of warning the user if he/she tries
to install an experimental bundle.
> Warn user when adding an experimental bundle

- src/globals.c
- src/swupd.h
Functions set_version_url and set_content_url were recently made static
since they were not being used outside of the globals file. Another
commit was merged that was using those functions from another file.
This commit makes those functions back to public.
> Making set_version_url and set_content_url public

- test/functional/server.py
PEP8 dictates the style conventions for Python, complying with these
standards is a good practice.
This commit makes a few small changes to comply with PEP8 standards.
> Changes to comply with PEP8

- src/bundle.c
- src/clr_bundle_ls.c
- src/helpers.c
- src/swupd.h
- test/functional/bundlelist/list-experimental.bats
This PR adds the ability to show an identifier in bundles that are
marked as experimental when listing available bundles or installed
bundles:
```
swupd bundle-list --all
swupd bundle-list
```
> Distinguish experimental bundles in a bundle list

- Makefile.am
- src/bundle.c
- src/helpers.c
- src/search.c
- src/swupd.h
- test/functional/search/search-experimental.bats
This commit adds ability to show when a bundle is experimental in the
results of a swupd search.
Closes #676
> Show when a bundle is experimental in swupd search

- src/manifest.c
- test/functional/testlib.bash
There was a change of plans in the mixer side and looks like the flag
that will be used to mark a bundle as an experimental will be the 2nd
one instead of the 4th one.
This commit moves the flag to the 2nd position in the swupd client.
> Moving experimental flag from 4th to 2nd position

- test/functional/testlib.bash
When using the test generator from the testlib to create a new empty
test, it will pre-fill the user name and email from the git config in the
test if possible.
> Add git user and email by default in new tests

- test/functional/checkupdate/chk-update-slow-server.bats
- test/functional/testlib.bash
- test/functional/update/update-slow-server.bats
Every test environment gets created with a default value for versionurl
and contenturl that points to the appropriate place using the "file://"
protocol. In some occassions the user may want to change this value to
something different, for example if he/she is planning on using an http
server to host the version/content.
This PR provides a way of setting up the upstream server in the test environment.
> Provide the ability to set the upstream server in a test environment.

- test/functional/checkupdate/chk-update-slow-server.bats
- test/functional/server.py
- test/functional/testlib.bash
The server.py script is used in some functional tests to simulate
a slow content server. This commit provides a few extra options
that extend the use of this script for testing purposes.
Improvements included:
- Ability to specify what port to use for the web server (useful when running the script manually)
- Ability to make the web server reachable by other machines in the network (useful when running the script manually/debugging)
- Ability to specify the directory to serve instead of just serving the directory where the server.py file is
- Ability to hang the server on command
- Ability to fine-tune how slow the server responds by being able to specify the delay time and the number of bytes read per cycle.
- Ability to either hang the server / or make it slow after a specific number of …
> Adding options to further control server.py

- test/functional/bundleadd/add-client-certificate.bats
- test/functional/bundlelist/list-client-certificate.bats
- test/functional/bundleremove/remove-client-certificate.bats
- test/functional/checkupdate/chk-update-client-certificate.bats
- test/functional/search/search-client-certificate.bats
- test/functional/testlib.bash
- test/functional/update/update-client-certificate.bats
- test/functional/verify/verify-client-certificate.bats
The tests that attempt to verify the client certificate were using the
swupd -u option to set the url of the "upstream server". Recently a
function was added to the test library to set the default upstream
server.
This commit modifies these tests so they used the new function to set
the upstream server instead of using the -u option. This will provide
the benefit of the test environment being more similar to a prod
environment, also makes the test setup less convoluted and the tests
easier to read.
This PR is built on top of PR #739, once that PR merges this will have to be rebased.
> Setting upstream server in client cert tests

- src/update.c
The run_command calls /usr/bin/mixinbuild, but it should call
/usr/bin/mixin build.
> Add space to separate 'mixin build' command

- test/functional/testlib.bash
This PR includes the following improvements for testlib:
- Ability to create files with specific size, useful for creating bundles
with files of a known size, or really big files.
- Silencing output when starting a test web server.
- Use std out if there is no file descriptor 3 when using _print_.
> Testlib improvements

- src/curl.c
- test/functional/bundleadd/add-client-certificate.bats
- test/functional/bundlelist/list-client-certificate.bats
- test/functional/bundleremove/remove-client-certificate.bats
- test/functional/checkupdate/chk-update-client-certificate.bats
- test/functional/search/search-client-certificate.bats
- test/functional/update/update-client-certificate.bats
- test/functional/verify/verify-client-certificate.bats
If we have an ssl error we try to use a fallback capath directory. Don't warn
users for errors unless we have failed on connecting using all available
fallback paths.
Fixes: #746
> curl: Don't warn users on non critical SSL errors

- src/signature.c
- src/verifytime.c
Strtotime is safer than asctime, so prefer that. It's known that there are
implementations of asctime that doesn't handle errors very well.
> time: Use strftotime instead of asctime

- Makefile.am
- src/curl.c
- test/functional/server.py
- test/functional/update/update-non-responsive.bats
- test/functional/update/update-slow-server.bats
As part of the swupd initialization, curl is initialized, which means it
is configured and the connection is tested. When configuring curl for
this test, no timeout was being configured, which was causing curl to
hang waiting for a response from the server if the server was unresponsive.
This commit configures the curl timeouts the same way they are being
configured when downloading files, so in case we get an unresponsive
server (or mirror) it doesn't get stuck forever.
Closes #669
> Timeout for testing connection in swupd init

- Makefile.am
- src/check_update.c
- src/curl.c
- src/download.c
- src/globals.c
- src/lib/log.c
- src/lib/log.h
- src/swupd.h
I have a local code with prints I use to debug some download bugs. I didn't commit that before because it's too verbose to print it always.
This series introduce a new log API and 2 new flags (--debug and --quiet) and a commit using that to print download debug information. As those flags are experimental and are not completely finished (--quiet is far from quiet in current master) I didn't added that to the documentation or help messages.
> Log - curl downloads

- src/curl.c
- test/functional/search/search-content-check-negative.bats
- test/functional/search/search-content-check-positive.bats
- test/functional/search/search-experimental.bats
When CURLOPT_NOBODY is set to true, curl shouldn't get the body of a file,
we should get only headers. This works fine for all tested scenarios using
http and https. It's also working in most scenarios that uses file://, but
it fails on travis environment. So, add a dummy function to ignore body data
if present.
There was a hack in search tests to ignore leaked file content. Removing that
hack.
> curl: swupd_curl_query_content_size is leaking file content

- Makefile.am
Glob ** will only recurse directories if globstar is set. To avoid skipping
important files run clang-format on src/ and src/lib
> Makeifile: Check all files under src/ for code style

- Makefile.am
- src/helpers.c
- src/verify.c
- test/functional/testlib.bash
- test/functional/verify/verify-fix-unsafe-to-delete.bats
When running verify --fix, if there are files in the system that are
marked as deleted in the manifest, then they are removed from the
system. However, if a component of the path of the file is a
symbolic link, the file is determined to be unsafe to be removed and
it is left in the system, the user is warned, and the not-deleted
file count is incremented.
This commit modifies this behavior so verify just skips the file, the
user is not warned with the "Not safe to delete: <FILE>" error message,
and so the not-deleted file count is not incremented since it is really
not useful for the end user.
Closes #765
> Verify --fix skip files that are unsafe to delete without warning the user

- Makefile.am
- src/bundle.c
- src/download.c
- src/manifest.c
- src/search.c
- src/swupd.h
- src/update.c
- src/verify.c
- test/functional/bundleadd/add-bad-hash-state.bats
- test/functional/bundleadd/add-bad-hash.bats
- test/functional/bundleadd/add-boot-file.bats
- test/functional/bundleadd/add-boot-skip.bats
- test/functional/bundleadd/add-client-certificate.bats
- test/functional/bundleadd/add-include.bats
- test/functional/bundleadd/add-multiple.bats
- test/functional/bundleadd/add-no-disk-space.bats
- test/functional/bundleadd/add-skip-scripts.bats
- test/functional/bundleadd/add-verify-fix-path.bats
- test/functional/bundlelist/list-no-disk-space.bats
- test/functional/bundleremove/remove-include-nested.bats
- test/functional/bundleremove/remove-no-disk-space.bats
- test/functional/checkupdate/chk-update-no-target-content.bats
- test/functional/search/search-content-check-negative.bats
- test/functional/search/search-content-check-positive.bats
- test/functional/search/search-experimental.bats
- test/functional/search/search-no-disk-space.bats
- test/functional/testlib.bash
- test/functional/update/update-no-disk-space.bats
- test/functional/verify/verify-missing-file.bats
- test/functional/verify/verify-no-disk-space.bats
When a disk gets full on a file download during an update, we are currently scheduling up to five retries for that download, which are going to fail for sure since there is no more space on disk.
This PR changes this behavior so it only tries to download the file once if we receive an error about the disk being full so we don't waste time.
The PR includes these commits:
- A commit with the necessary updates in the test library so we can create test environments that are limited in space.
- A commit that includes tests to validate the different scenarios where the disk can get filled up during an update.
- The changes to the swupd code to abort download retries when the disk is full.
Closes #752 
> Do not retry files download if there is no more space on disk

- test/functional/testlib.bash
When in a test we create a new version and a bundle update in that new
version, we copy the latest tar for each fullfile from the previous
versions into the new version. The code currently was searching for
those tars starting with the current directory, this was working fine
when running the tests locally because tests are run serially, but this
was causing an unexpected result when running in Travis since tests are
run in parallel, so this was causing the search to sometimes find the
tar in a different test environment (from another test), which was
causing unexpected results and a race condition.
This commit fixes the issue by narrowing the search of the tars to the
web-dir of the specific test environment.
> Fixing a race condition in testlib

- test/functional/update/update-no-disk-space.bats
Two PRs that included tests for swupd update were submitted and merged
at the same time, which caused the test IDs to be inconsistent.
This commit fixes the IDs of the update tests with duplicated ID.
> Fixing IDs of update tests

- Makefile.am
- test/functional/testlib.bash
Shellcheck provides many useful recommendations for writing shell code.
This commit makes testlib.bash shellcheck compliant.
Signed-off-by: Castulo J. Martinez <castulo.martinez@intel.com>
Closes #662
> Making testlib shellcheck compliant

- src/lib/sys.c
The code was assuming that dup2 was replacing the fd, but this is not the case.
It is duplicating it, so new_fd was leaking.
> sys: Fix memory leak

- src/verify.c
> Removing useless code from get_all_files function

- src/scripts.c
- test/functional/bundleadd/add-boot-file.bats
- test/functional/update/update-boot-file.bats
- test/functional/update/update-boot-file_1.ignore-list
- test/functional/verify/verify-boot-file.bats
- test/functional/verify/verify-boot-file_2.ignore-list
When swupd needs to run a boot script it does so without checking if the
file exists in the system or not. This will cause an error to be raised
by the shell if the script does not exist.
This commit adds a check for the existance of the script before
attempting to run it.
Closes #795
> Checking if the boot script exist before running

- src/search.c
- test/functional/search/search-content-check-negative.bats
- test/functional/search/search-content-check-positive.bats
swupd search returns 0 both when something is found and when nothing
is found.
This commit makes a change so it returns 0 (SWUPD_OK) if search found
somthing and 1 (SWUPD_NO) if it didn't.
Closes #731
> Return non-0 code if search does not find entries

- .travis.yml
- src/bundle.c
- src/curl.c
- src/swupd.h
- src/update.c
- src/verify.c
- test/functional/ignore-list
- test/functional/update/update-boot-file_1.ignore-list
- test/functional/verify/verify-boot-file_2.ignore-list
Display the bytes transferred after each update in the message
that shows "took N seconds" by appending the info.
This includes total transfer bytes for verify, update, check,
bundle-add and bundle-remove.
The curl error handling function is the perfect location to
capture the bytes for each transfer, and add them to a global
counter. The global counter is then included in each telemetry
event.
> Telemetry: include `bytes transferred` wherever applicable.

- docs/swupd.1.rst
- src/globals.c
- src/swupd.h
- src/verify.c
--force/-x is specific for verify command, but documentation was stating
that it was global. Removing all references from a global --force and
adding that information to the help page of verify command.
Also moves the force variable from global to verify.
> docs: Fix documentation on --force option

- Makefile.am
- autogen.sh
- configure.ac
This commit adds an option to disable compiler optimizations which is
very useful when debugging a problem in swupd.
Note: the user would still need to make sure the optimization option is
not enabled in his/her CFLAGS variable.
> Providing option to disable compiler optimizations

- src/swupd.h
- src/update.c
- src/version.c
- test/functional/update/update-to-same-version.bats
Use similar output and same exit code used when you are already in the
last version in the case where you are updating to the same version you
already are.
i.e. if you are in version 100, both commands are going to have the same
exit code:
- swupd update
- swupd update -m 100
> update: Be consistent in exit codes when trying to update to the same version

- src/curl.c
> curl: Check for errors before using value from curl_easy_getinfo call

- src/check_update.c
- src/helpers.c
- src/verifytime.c
- src/verifytime.h
- src/verifytime_main.c
When a user is using the -p/--path option with swupd he can point to a
chroot installation of clear or a custom mount. However when swupd
checks the system time to see if it is sane it compares it with a
versionstamp hardcoded in  /usr/share/clear/versionstamp, which causes
swupd to fail in systems using -p.
This commit prepends the path_prefix to the versionstamp path so it
points to the correct file if using the --path option.
Closes #812
> Adding path_prefix for versionstamp

- src/curl.c
- src/curl_async.c
- src/swupd_curl_internal.h
When we are checking if the SSL is working and the server is up we don't care
about the server return code. We just care if the server is responding. So
we shouldn't set the curl option CURLOPT_FAILONERROR.
The major problem of this change is that some servers don't respond to GET
in '/'. So checking the connection using the version url will fail in that
cases if CURLOPT_FAILONERROR is set.
As we don't really need the other options, reverting that change back to
how it was before.
Fixes #792
> Curl: Don't set curl fail on error when checking the connection

- Makefile.am
- configure.ac
- docs/swupd.1.rst
- src/binary_loader.c
- src/lib/sys.c
- src/lib/sys.h
- src/main.c
- src/swupd_exit_codes.h
- src/swupd_internal.h
- test/functional/usability/usa-external-modules.bats
Use a binary launcher to load swupd-inspector and execute that
when swupd inspector is run.
Closes #826
> Add swupd-inspector command into swupd

- src/lib/hashmap.c
Signed-off-by: Brandon Hong <brandon.hong@intel.com>
> Fix missed dereferencing operator in string hash function

- test/functional/testlib.bash
- test/functional/update/update-minversion.bats
- test/functional/update/update-re-update-bad-os-release.bats
- test/functional/update/update-re-update-required.bats
The update_minversion and bump_format testlib functions both perform a minversion update, but with separate implementations. These implementations should be consolidated.
Closes #618
> Consolidating minversion implementations in testlib

- Makefile.am
- src/update.c
- test/functional/update/update-show-time.bats
When running an update using the flag --time/-t the user is presented
with a verbose time output of the update operations. The time collected
for those operations was wrong.
This commit fixes the issue and presents a verbose output that is
consistent with other commands like bundle-add --time.
Closes #584
> Fixing the time shown using update -t

- test/functional/testlib.bash
- test/functional/update/update-newest-deleted.bats
- test/functional/update/update-with-old-mirror.bats
Currently, testlib.bash generates delta packs for a given bundle from its most recently changed version to the latest version. This is not sufficient because the current version may be older than a bundle's most recently changed version. For instance, if an update was performed from version 10 to version 30 and a bundle has been updated in versions 20 and 30, a delta pack will be generated for that bundle from version 20 to version 30. It is expected that a delta pack for that bundle should be generated for an update from version 10 to version 30.
This PR generates delta packs for all previous version of a bundle when an update is created.
Closes #615
> Generating delta packs for all previous versions

- swupd.bash
Since search became search-legacy and there is a new search, the
autocompletion script needs to be updated.
> Add search-legacy to autocompletion script

- src/main.c
- test/functional/search/search-client-certificate.bats
- test/functional/search/search-content-check-negative.bats
- test/functional/search/search-content-check-positive.bats
- test/functional/search/search-experimental.bats
- test/functional/search/search-no-disk-space.bats
- test/functional/usability/usa-external-modules.bats
We needed on sample for external binaries, but as now we have swupd-search we
can take swupd inspector out.
Also move local search to list of external modules and fix all related tests
> modules: Take swupd-inspector out of swupd

- test/functional/usability/usa-external-modules.bats
And it fails when using current version of swupd-search.
> test: Swupd-search test was incorrect

- Makefile.am
- src/search.c
- test/functional/search/search-sort.bats
The search command uses a score system to weight the results it finds,
the purpose of this is to try and show the most relevant results to the
user on top, however since the focus of the search command is changing,
we don't need to guess what the user is looking for and just show all we
find.
This commit removes the score ordering from the search command.
> Removing search heuristics

- .travis.yml
- configure.ac
- docker/dockerrun.sh
- docs/README.rst
Signature verification was disabled as a default parameters to make it easier
for people to build the project on other distros. But this can be dangerous
as users may start using a built swupd without signature checking to
install a CL distro.
> Set signature verification enabled as default

- src/curl_async.c
- src/lib/thread_pool.c
- src/lib/thread_pool.h
If we have any errors on pipe2 syscall or in pthread creation run tasks
in main thread. Also set the max downloads in parallel to 1 to avoid timeouts
> thread_pool: Run tasks in same thread if threads are not supported

- src/bundle.c
- src/update.c
We don't use rand() in swupd so don't need to initialize the random generator.
This was a leftover from previous code that used rand() for tests purposes.
> Remove unecessary srand() calls

- .travis.yml
- Makefile.am
> Travis improvements to speed up the build

- .travis.yml
This commit includes two improvements for the build process:
- It separates the static analysis and unit test execution into its
own job in a different previous stage in the build process from the
functional testing. This will allow the build not only to run the static
analysis before the functional tests but will also only run the functional
tests if the static analysis and unit test passed. This is important
because this stage only uses one job while the functional tests use many
jobs. There is no need to waste many jobs if the build didn't pass the
static analysis.
- It groups tests in different jobs for execution in a way that most
jobs take similar time to finish. This will allow fine tuning how long
the build takes to finish by configuring number of groups and number of
tests in …
> Run static analysis in a different test stage in the build process

- .travis.yml
This commit includes two more improvements for the swupd build process:
- It balances the tests run in each one of the four test jobs so they
take approximately the same time. Before tests were being balanced per
test directory, with this commit tests are now balanced at a test file
level, which provides an even better tuning. In this case we are
splitting the update tests into 2 jobs since they are the most time
consuming.
- Instead of using bats directly for running tests, this commit uses
"make check" to run the tests but it provides a specific list for make
to override the default list so it doesn't run all tests. The advantage
of this is to still enjoy the benefits of the nice output provided by
make check which only shows a list of the tests executed and their status
and it only …
> Balance tests in jobs in Travis

- src/info.c
- src/update.c
Mostly because we need to use --path to display information about a chroot
Fixes #851
> info: Use parameters defined as global parameters

- src/hashdump.c
- test/functional/testlib.bash
Currently when calculating the hash from a file two lines are printed:
Calculating hash with xattrs for: my_file
5114e8e3cc667fa80eb5407e5825c618e6668503aba53c8cca7f8daf84cec03f
The first line goes to STDERR while the second one goes to STDOUT. The
test library uses the hash that goes to STDOUT to perform many tasks, so
it is important the output can be filtered to just print the hash.
In the near future, all messages printed with printf or fprintf will be
replaced by logger functions in all the source code which will cause both
lines to be printed to the output which will break the test library.
This commit adds the --quiet flag to the hashdump command so that only
the calculated hashdump is printed on screen.
> Adding the --quiet flag to hashdump

- docs/swupd.1.rst
- src/helpers.c
- src/lib/list.c
- src/lib/list.h
- src/search.c
- src/swupd.h
- src/verify.c
- swupd.bash
- test/functional/search/search-content-check-negative.bats
- test/functional/search/search-content-check-positive.bats
- test/functional/search/search-experimental.bats
- test/functional/search/search-no-disk-space.bats
- test/functional/search/search-sort.bats
Rewriting some functions on swupd search so we don't need to store everything in memory to be printed later. Print things as we find them. This makes search-file a lot faster and with a smaller memory footprint
Fixex #388
> Search-file rework

- src/globals.c
- src/swupd.h
- src/update.c
- test/functional/update/update-re-update-bad-os-release.bats
Note that we don't need to use run_command() (fork + exec) because
we don't need to handle any output on swupd. We can just replace current
process with the new swupd execution.
> update: use execv() instead of system() to re-execute update

- src/lib/sys.c
The default is to use the full path of the binary that is being executed and
not the basename.
> sys: First parameter in argv isn't the basename of the binary

- test/functional/bundleadd/add-json.bats
- test/functional/mirror/mirror-json.bats
- test/functional/search/search-json.bats
- test/functional/update/update-json.bats
- test/functional/verify/verify-json.bats
Disabling json tests that checks for progress because tests are unstable.
If we have any minor changes in the code that could affect how curl is called
we could have different progress reports and because of that we would have false
negatives.
> test: Disabling json tests for now

- src/helpers.c
- src/lib/archives.c
- src/lib/archives.h
At first I assumed that all tarballs would have a trailing '/' for directories
and this isn't true. But we can't assume that we won't have a trailing '/'. So
archives_check_single_file_tarball() is now ignoring trailing '/' when comparing
files. That is the same behavior of the function that
archives_check_single_file_tarball() replaced.
> archives: Don't assume tarball includes '/' for directories

- src/bundle.c
Cleaning up some code that does nothing in bundle-add.
> Removing code not used from bundle-add

- src/clean.c
- src/curl.c
- src/swupd.h
- src/update.c
We have a layer isolating curl API calls, so don't include libcurl
headers on swupd.h.
> swupd: Don't include libcurl headers

- Makefile.am
- src/globals.c
- src/helpers.c
- src/lib/macros.h
- src/manifest.c
- src/signature.c
- src/signature.h
- src/swupd.h
- test/unit/test_helper.h
- test/unit/test_signature.c
- Reorganize code to take swupd specific code from signature.c
- Add unit tests for signature verification
- Check if OCSP is set as critical and reject the certificate if so, because OCSP isn't supported on swupd yet.
> Signature - Some organization, certificate revogation and tests

- src/curl_async.c
- src/fullfile.c
- src/packs.c
- src/swupd_curl.h
We can declare the scruct in a header file and define it in a source file so
we can avoid using void pointers for the handle. It's a better approach because
compilers can trigger errors if we use a different type.
> curl: Use a struct declaration instead of void pointers

- src/lib/sys.c
> sys: Adding a missing --no-block flag on call that shouldn't block

- swupd.bash
There is a bug in the code that causes swupd bundle-add <TAB><TAB>
to list regular bundle names as well as iterative manifest names.
This commit fixes the issue by removing the iterative manifests from
the list of results.
Closes #906
> Removes iter manifests from bundle-add completion

- Makefile.am
- swupd.bash
Bash completion was adding line breaks because of that extra " on COMPREPLY
> swupd.bash" Remove extra " when setting COMPREPL

- src/curl.c
This change sets swupd client User-Agent header to PACKAGE/VERSION. This is
a standard HTTP header to identify the client that originates a request.
Signed-off-by: Alex Jaramillo <alex.v.jaramillo@intel.com>
> Set user-agent header

- .travis.yml
- Makefile.am
- docs/swupd.1.rst
- src/main.c
- src/verify.c
- swupd.bash
- test/functional/diagnose/diagnose-basics.bats
- test/functional/diagnose/diagnose-boot-file.bats
- test/functional/diagnose/diagnose-client-certificate.bats
- test/functional/diagnose/diagnose-directory-tree-deleted.bats
- test/functional/diagnose/diagnose-good.bats
- test/functional/diagnose/diagnose-json.bats
- test/functional/diagnose/diagnose-missing-file.bats
- test/functional/diagnose/diagnose-picky-downgrade.bats
- test/functional/diagnose/diagnose-picky-whitelist.bats
- test/functional/diagnose/diagnose-picky.bats
- test/functional/repair/repair-format-mismatch-overdrive.bats
- test/functional/repair/repair-format-mismatch.bats
- test/functional/testlib.bash
- test/real_content/real_content_lib.bash
- test/real_content/swupd_update.bats
- test/real_content/swupd_update_fullfiles.bats
- test/real_content/swupd_update_jump.bats
- test/real_content/swupd_verify_install.bats
This PR renames the "verify" command to "diagnose" to make it
more straightforward for the user to understand the purpose of the
command.
Closes #918
> Renaming "swupd verify" to "swupd diagnose"

- src/mirror.c
> mirror: Don't enforce root if mirror command is used in read-only mode

- src/repair.c
- src/update.c
- src/verify.c
- test/functional/diagnose/diagnose-picky-downgrade.bats
- test/functional/repair/repair-format-mismatch-overdrive.bats
- test/functional/repair/repair-format-mismatch.bats
- test/functional/repair/repair-no-disk-space.bats
- test/functional/repair/repair-picky-downgrade.bats
swupd uses the -m / --manifest flag for some commands to specify what
version to use for that specfic action. For example using "swupd verify
--install --manifest=10" will attempt to install the OS with version 10.
The problem is that this flag doesn't really hint users about what the
flag is used for, specially if the user is not familiar with swupd / mixer
internals.
This commit adds a replacement flag -V / --version that will have the
exact same functionality of -m / --manifest which will be deprecated.
The deprecated flag should be removed in 6 months time.
> Adding the -V / --version flag to swupd commands

- src/globals.c
We always append an extra '/' at the end of the URL and some webservers doesn't support
multiple slashes connected. So always removing last '/' on URLs.
> global: Remove trailing slashes on content and version URLs

- test/functional/update/update-json.bats
The update/update-json.bats functional test is giving a false positive
since one hardcoded value (time) was taking longer to run in a local
environment.
This commit fixes the issue by using a regex to accept any time value.
> Fixing false positive in a functional test

- src/fullfile.c
- src/verify.c
There was a bug with the line breaks during `swupd verify --fix` or `swupd repair` that was causing the output to look like this.
```
Verifying version 29620
Verifying files
...100%
Starting download of remaining update content. This may take a while...
...66528%Adding any missing files
...100%
Repairing modified files
```
This PR fixes that by moving the line break to the appropriate place.
> Fix a line break when running "swupd repair"

- src/main.c
This commit sorts the swupd main menu in a way that makes more sense.
> Sorting swupd main menu

- src/clr_bundle_ls.c
- src/helpers.c
- src/lib/sys.c
- src/lib/sys.h
When we changed the init swupd function we stopped supporting bundle-list as root.
Adding this back on.
> bundle-list: local bundle list should work without root

- src/curl_async.c
- src/fullfile.c
- src/manifest.c
- src/packs.c
- src/swupd.h
- src/swupd_progress.c
- src/swupd_progress.h
When the download progress of fullfiles was being calculated it was
being done considering as if the files were being downloaded serially
not in parallel. This was causing an error in the calculation of the
download progress.
This commit fixes the issue by considering the files are being downloaded
in parallel when calculating the download progress.
Closes #939
> Fix download progress for fullfiles

- src/update.c
When swupd is updating a system and it has to go over a format bump, the
update is run twice. First to get to the lower boundary of the format
bump and then it run again to go from the upper boundary of the format
bump to the desired version.
The second time the update was being run, swupd was being executed without
considering the environment, so the PATH variable was not being read,
this was causing swupd to fail to re execute itself for the second
update unless the user had run swupd specifying the full path in the
first place.
This commit fixes the issue by resolving the full path to swupd before
re executing itself.
Closes #942
> Add full path to swupd binary before re-update

- Makefile.am
A compressed distribution tarball created via
$ make dist
is missing some files needed to run the standard
sequence of build commands:
$ ./configure
$ make
$ make check
In particular, when running "make check" we get:
../../test/unit/test_signature.c:9:10: fatal error: test_helper.h: No such file or directory
9 | #include "test_helper.h"
|          ^~~~~~~~~~~~~~~
compilation terminated.
This patch modifies the distribiton tarrball by adding files/folders:
1. test/unit/test_helper.h (to fix the above build error)
2. test/unit/data  (files reference by the test/unit/ binaries
3. test/functional (files referenced by Makefile)
With this patch "make check" reports:
Testsuite summary for swupd-client 3.20.0
============================================================================ …
> Makefile.am: add files to distribution

- src/lib/progress.c
When reporting download progress, we should never have a percentage
bigger than 100%, but if for some reason we do (due to a bug), we don't
want that percentage slipping all the way to the end user.
This commit limits the percentage we display to 100 maximum.
> Adding a progress overflow protection

- swupd.zsh
I wrote a `zsh` completion function for `clearlinux/swupd-client`.
- It shows both available arguments/options and their description
- It provides URL and PATH completions for certain options
- It provides BUNDLE completion for `swupd diagnose -b|--bundles`,
`swupd repair -b|--bundles` and `swupd bundle-remove`. The list
of available bundle is dynamic, that is to say if you've already
specified a bundle, it won't appear in the list.
- Those labelled as `deprecated` are not presented in the completion.
(But you may add them.)
I also suggest the following:
- `swupd.zsh` shall be placed under `/usr/share/zsh/site-functions` and
named as `_swupd` according to `zsh` convention, if `zsh` is installed.
It will be loaded by `zsh` because this directory is in `zsh`'s `$fpath`.
- `swupd.bash` …
> Add `zsh` completion

- src/globals.c
Some of the global flags require a value and some do not. However when
printing the help for these global options, there is an inconsistency in
the way we display help, some of the flags that require values show that
they do require a value but some other do not. This makes it confusing.
This commit changes the help menu so all globals that require a value
show that they require it.
> Consistency in global options help menu

- src/extra_files.c
- src/lib/sys.c
- src/lib/sys.h
When using "diagnose --picky --picky-tree /fake/path" swupd was exiting
with error code 34 (SWUPD_OUT_OF_MEMORY_ERROR) which was incorrect.
This commit fixes the issue by returning the correct code 29
(SWUPD_COULDNT_LIST_DIR) in those situations.
> Return correct code when bad path in picky-tree

- src/lib/sys.c
Replace stdin with /dev/null for children. This addresses the issue with
hangs when running update hooks which for whatever reason may expect
interactive input.
> Prevent swupd from running interactive commands. 

- src/curl.c
- src/globals.c
- src/helpers.c
- src/mirror.c
- src/swupd.h
- swupd.bash
- test/functional/bundleadd/add-no-disk-space.bats
- test/functional/checkupdate/chk-update-slow-server.bats
- test/functional/mirror/mirror-createdir-negative.bats
- test/functional/mirror/mirror-createdir.bats
- test/functional/mirror/mirror-json.bats
- test/functional/update/update-non-responsive.bats
- test/functional/update/update-slow-server.bats
- test/functional/usability/usa-download-retries.bats
Currently users can set content and version urls based on http or https
protocols. This pose a security risk if users decide to use http.
This commit blocks swupd from working with http unless is specifically
allowed by using the --allow-insecure-http flag.
Closes #953
> Require a force flag to continue with insecure URL

- .travis.yml
- Makefile.am
- config
- configure.ac
- src/config_loader.c
- src/config_loader.h
- src/globals.c
- src/lib/config_parser.c
- src/lib/config_parser.h
- src/lib/formatter_json.c
- src/lib/formatter_json.h
- src/lib/strings.c
- src/lib/strings.h
- src/main.c
- src/mirror.c
- src/os_install.c
- src/repair.c
- src/swupd.h
- src/swupd_internal.h
- src/verify.c
- test/functional/testlib.bash
- test/functional/usability/usa-config-file.bats
swupd has many flags that can be used for fine tunning its
functionality. In some cases users may want to include a flag with every
swupd command they run.
This commit gives the ability to provide swupd flags via options in a
configuration file that swupd will read before running the command.
The configuration file is an INI style file tha  can include sections
so users can specify options that should only apply to a specific
command. The biggest advantage of this is to be able to fine tune the
flags that should apply for each command.
For example a user could set a global flag that would apply to every
swupd command, and then turn that flag off for a specific command by
unsetting it in the command's section.
Closes #952 
> Adding configuration file parser for swupd

- test/functional/testlib.bash
When running tests that use the config file, it is important to make
sure the config file from the previous test is deleted before the next
test is run. This is necessary since config files are not contained to
the test environment of each test as the rest of the test resources. So
a config file from one test can affect the output of another test if we
don't wait.
> Wait until the config file is deleted in tests

- src/mirror.c
- test/functional/mirror/mirror-allow-http.bats
- test/functional/mirror/mirror-json.bats
If a user sets a mirror that uses http, it is going to cause autoupdates
to stop working since autoupdate would need the --allow-insecure-http
flag to continue with the insecure connection. In order for autoupdate
to work the user will need to add the key/value allow-insecure-http=true
in the swupd config file.
This commit warns the user about this when setting up a mirror with http
so they can take steps to re-enable autoupdate.
> Warn user setting mirror to http

- Makefile.am
- src/bundle.c
- src/clr_bundle_add.c
- src/globals.c
- src/manifest.h
- src/manifest_parser.c
- src/swupd.h
- test/functional/bundleadd/add-include-optional.bats
- test/functional/bundleremove/remove-optional-bundles.bats
- test/functional/testlib.bash
- test/unit/data/mom2
This PR adds support in swupd for optional bundles in manifests. An optional bundle is similar to the required bundles (included bundles) but have a couple of differences.
- Optional bundles are installed by default when the main bundle that includes them is installed.
- Users have the option to skip the installation of `Optional` bundles by using the flag `--skip-optional` or `-o` with `bundle-add`.
- Optional bundles can be removed from the system even if the main bundle that installed them is still in the system.
Closes #875
> Support "optional" bundles in manifests

- src/curl.c
- src/globals.c
- src/helpers.c
- src/mirror.c
- src/swupd.h
- src/swupd_curl.h
- test/functional/update/update-non-responsive.bats
- test/functional/update/update-with-mirror.bats
- test/functional/update/update-with-old-mirror.bats
- test/functional/update/update-with-slightly-old-mirror.bats
When doing an update, we check to see if a mirror is stale, this only
needs to be done if there is a mirror set.
This commit checks to see if a mirror is set and only then it checks to
see if it is stale. This gives us the advantage of adding more detailed
messages when checking for the mirror status without polluting the output
with those extra messages when a mirror is not set.
Closes #922
> Checking mirror status only if it is set

- swupd.zsh
This fixed the `zsh` completion.
Previously some installed bundles are not shown for
`swupd bundle-remove` and `swupd diagnose --bundles=`,
it is fixed.
> Fixed: Correctly show installed bundles

- .travis.yml
Config files cannot be isolated to a test environment, they are system
wide, so those tests need to be run separatelly so they don't interfere
with other tests.
> Running config file tests separatelly

- test/functional/mirror/mirror-allow-http.bats
This test is yielding different results depending on if it is being run
in a system that has a proxy set up o there is no proxy.
This is happening because when usnig a non existing  server, if
there is a proxy set up, the proxy does respond during curl
initialization instead of the specified server, which allows swupd to
initialize only to fail further down the process when requesting the MoM
to the server. If the system where the test is run doesn't have a proxy
set up, curl fails to initialize since it gets no reply from the server,
which causes swupd to fail initialization, so swupd exits earlier in the
process and with different exit code.
This commit fixes the ambiguity of the test by not checking for an exit
code explicitelly but only making sure it does get an error code. …
> Fix bug in mirror-allow-http.bats test

- test/unit/test_signature.c
Last parameter was missing on a run_command() call and tests were breaking for some specific configurations.
> test: Add missing NULL parameter to run_command() call

- .travis.yml
- Makefile.am
- docs/swupd.1.rst
- scripts/flag_validator.bash
- src/clr_bundle_ls.c
- src/mirror.c
- src/search.c
- src/update.c
swupd supports global flags and supports local flags that are specific
to subcommands. Flags that are specific to subcommands can be reused in
a different subcommand. Global flags should be unique and should not be
reused as local flags to avoid conflicts.
This commit adds a bash script that checks that the flags currently used
in swupd are valid (have no conflicts with other flags from the same
command or with the global flags). This script will be run as part of
the build process so in case an invalid flag is found the build will be
stopped. Alternatively, the script can be used by developers to validate
a new flag during the implementation time.
> Adding flag validation to the swupd build process

- src/bundle.c
- src/update.c
- test/functional/bundleadd/add-also-add-flag.bats
- test/functional/os-install/install-also-add.bats
- test/functional/update/update-include.bats
Circular includes shoudn't exist, but we can handle that without crashing.
Also-add circular includes are common and expected. So we just add the
first occurence found.
> bundle: Support circular includes/also-adds

- src/helpers.c
The URL value must be set to lowercase to prevent support for mixed case
or uppercase HTTP strings without the --allow-insecure-http flag.
> Use lowercase URL comparison for is_url_allowed()

- config
- docs/swupd.1.rst
- src/bundle.c
- src/globals.c
- src/swupd.h
- src/update.c
- src/verify.c
- swupd.bash
- swupd.zsh
When running tasks that require to run post update scripts in swupd,
for most users we don't want to wait for the scripts to finish running,
those can be run in the background so we can finish the task faster.
However for some users like DevOps, clr-installer, and QA, it is useful
to have a way to instruct swupd to wait until these scripts have finish
running.
This commit adds a way of doing this by introducing the
--wait-for-scripts flag.
Closes #909
> Adding --wait-for-scripts flag

- src/verify.c
The help currently displayed for the "-Y" flag for the diagnose command
is not accurate since "--fix" should not be user, we encourage users to
use repair instead.
> Fix diagnose help for the "-Y" flag

- src/lib/log.c
- src/lib/progress.c
- test/functional/testlib.bash
Fix format of do_staging when reporting progress
The function do_staging is regularly used within a loop to stage all the files for a given bundle-add or update, repair, etc. However when the loop contains a progress report (with a percentage), if there are errors in the do_staging function, they get printed in the same line as the percentage, messing up the output. Like this:
...22%Warning: Update target directory does not exist: some_file...
This commit fixes that output by adding a carriage return at the beginning of each message do_staging could print so it would overlap with the percentage value effectively deleting it.
> Progress overlap

- test/functional/usability/usa-config-file.bats
config file tests require one special configuration on build time, so
skiping this unless we are running on travis.
> test: Don't run config file tests on developers machine

- src/lib/config_parser.c
Key and value are already valid strings so we can use them without
duplicating them in memory.
> config_parser: Don't allocate extra memory for key and value

- src/clean.c
This commit makes parsing the long options from the clean command
consistent with the way they are being parsed for the rest of the
swupd commands.
> Parsing "clean" long options consistently

- src/lib/log.c
- src/lib/progress.c
Debug messages need to be treated a little differently from other
messages, since they include more information, like the time, file and
line of code. So certain things like having carriage returns and
messages with only a line break should not be allowed since they would
mess up the debug output.
This commit fixes that issue
Closes #1009
> Fix logger format when printing debug messages

- swupd.bash
I tried several implementation and found this is the fastest one.
```bash
#!/usr/bin/bash
MoM=/var/tmp/swupd/Manifest.MoM
start=$(date +%s%N)
sed '1,/^$/d; s/^.*\t/ /; /.*\.I\..*/d;s/\n/ /g' "$MoM" &> /dev/null 
end=$(date +%s%N)
echo "Current" "$(expr $end - $start)"
start=$(date +%s%N)
awk '/M.../{print $4}' "$MoM" &> /dev/null
end=$(date +%s%N)
echo "awk    " "$(expr $end - $start)"
start=$(date +%s%N)
sed -e '/M\.\.\./!d;s/.*      //' "$MoM" &> /dev/null
sed '/^[^M]/d;' "$MoM" &>/dev/null 
end=$(date +%s%N)
echo "sed    " "$(expr $end - $start)"
start=$(date +%s%N)
awk '/M.../' "$MoM" | cut -f4 &> /dev/null
end=$(date +%s%N)
echo "awk|cut" "$(expr $end - $start)"
start=$(date +%s%N)
sed '/^[^M]/d' "$MoM" | cut -f4 &> /dev/null
end=$(date +%s%N)
echo "sed|cut" "$(expr $end - $start)" …
```
> swupd.bash: faster bundle-add

- swupd.zsh
This should be consistent to the `swupd` client up to 8590464
---
1.  Added bundle name completion for `swupd search FOO [--deps=|--has-deps=]`,
2.  Improved completion for `swupd search-file [-B=|-l=]`.
- For `-B`, only files in /usr/bin directory are listed
- For `-l`, only `.a` or `.so` files under `/usr/lib` or `/usr/lib64` are
listed
3.  Completions for `diagnose` and `repair` are handled separtely because of
non-trivial differences in descriptions of certain options.
4.  `--quiet` and `--debug` options of `swupd hashdump` are mutually exclusive
since only one of them takes effect when both are supplied.
5.  If `-p|--path=` option and its argument is supplied to `swupd hashdump`,
completions for the non-option argument is generated by the `zsh`'s native
`_path_files` function, …
> swupd.zsh: Multiple Improvement

- Makefile.am
Manpages are created in make dist so we should clean them only on distclean.
For example if you run:
$ make dist
$ tar xf swupd-client-version.tar.gz && cd swupd-client
$ make clean
All manpages are going to be deleted and the source files aren't available on
the tarball. So you are going to be blocked in a build.
> Makefile: Clean manpages only on distclean

- test/real_content/real_content_lib.bash
> real_tests: repair doesn't support -B anymore, so use verify --fix

- src/mirror.c
check_connection() returns an int. We shouldn't use ! before comparing it to zero.
If check_connection() return is zero it's a success.
> mirror: Removing invalid ! in check connection

- src/fullfile.c
- src/packs.c
- test/functional/bundleadd/add-no-disk-space.bats
MB stands for Megabyte and Mb stands for Megabit, so use the correct
unit.
Fixes #1044
> log: Print download sizes in MB and not Mb

- Makefile.am
- config
- docs/swupd.1.rst
- src/os_install.c
- src/swupd.h
- src/verify.c
- swupd.bash
- swupd.zsh
- test/functional/os-install/install-download.bats
- test/functional/testlib.bash
When the --download flag is set for the os-install command, update
content will be downloaded to the statedir and no content will be
installed.
> os-install: Add download flag

- src/globals.c
This is very handy for testing because we can just run:
$ swupd os-install --path testing/
And the testing/ directory will be automatically created. It's the same
behavior we have for the state dir.
> globals: If path_prefix doens't exist, creates it

- test/real_content/real_content_lib.bash
Diagnose picky behavior has changed so now we can use just one call
to swupd to verify if there's no extra file and no corruption.
> test: Don't check the hashes twice on real tests

- config
- configure.ac
- src/clr_bundle_add.c
- src/clr_bundle_ls.c
- src/config_loader.c
- src/globals.c
- src/globals.h
- src/os_install.c
- src/repair.c
- src/search.c
- src/update.c
- src/verify.c
Enable the ability to provide many paths for the configuration file and read configuration from all of them. If the same option is defined in more than one configuration file it will just be overwritten by the one last read.
> Multiple configuration files

- Makefile.am
- src/bundle.c
- test/functional/repair/repair-deleted-include-manifest.bats
- test/functional/update/update-deleted-include-manifest.bats
Previously, errors when adding included manifests were thrown away which
resulted in swupd operations that could succeed, even when failing to
load an included manifest. Now when an included manifest fails to load,
swupd will return a failure.
> bundle.c: Return included manifest loading errors

- Makefile.am
- src/check_update.c
- src/swupd.h
- src/update.c
- src/version.c
- test/functional/checkupdate/chk-update-format-bump.bats
- test/functional/testlib.bash
- test/functional/update/update-status-no-target-content.bats
- test/functional/update/update-status.bats
When running the check-update command we get the latest version for the
format we are currently in, but we really want to get the latest version
regardless of the format.
This commit fixes the issue.
Closes #482
> Show the real latest version using check-update

- Makefile.am
- config
- docs/swupd.1.rst
- src/fullfile.c
- src/globals.c
- src/globals.h
- src/helpers.c
- src/manifest.c
- src/os_install.c
- src/packs.c
- src/swupd.h
- src/verify.c
- swupd.bash
- swupd.zsh
- test/functional/os-install/install-statedir-cache-offline.bats
- test/functional/os-install/install-statedir-cache.bats
The `--statedir-cache` flag specifies a secondary statedir that will be checked before downloading files over the network. This flag is only supported for the `os-install` command.
The primary reason to use the statedir-cache is to enable the `os-install`
command to take advantage of hardlinks when installing content across
partitions. In this case, update content stored in the statedir-cache
(source partition) will be copied to the statedir (target partition) before
installing content into the target partition. Since the update content
will exist on the target partition before installation, hardlinks can be
used instead of copies.
NOTE: This PR depends on #1061 and the offline functional tests will fail due to this dependency.
> Add Support for statedir-cache

- test/functional/os-install/install-statedir-cache-offline.bats
Never use on tests fake url without specifying the protocol because proxies can
respond differently. Use https pointing to localhost in this cases.
> test: Fix tests for http proxy configuration

- .gitignore
- Makefile.am
- test/functional/generate-cert.prereq
- test/functional/signature/key-rotation.bats
- test/functional/testlib.bash
- test/unit/test_manifest.c
All files that are written by tests should be written in the directory
where the tests were executed and not the directory where code is.
Make distcheck now works fine
Fixes #343
> test: Support running tests in a different directory

- test/functional/bundleadd/add-client-certificate.bats
- test/functional/bundlelist/list-client-certificate.bats
- test/functional/bundleremove/remove-client-certificate.bats
- test/functional/checkupdate/chk-update-client-certificate.bats
- test/functional/diagnose/diagnose-client-certificate.bats
- test/functional/diagnose/diagnose-verify-flags.bats
- test/functional/generate-cert.prereq
- test/functional/search/search-client-certificate.bats
- test/functional/testlib.bash
- test/functional/update/update-client-certificate.bats
This PR includes several fixes and improvements for the swupd test library.
- It adds a `debug_msg` function to print messages for troubleshooting tests.
- It enables printing the debug messages and saving a copy of the test environment separately using two environment variables: DEBUG_TEST and KEEP_ENV.
- It add a `--force` flag to `destroy_test_environment()` to force the removal of an environment even when the `KEEP_ENV` variable is set to true. This is useful to remove leftover environments before starting a new execution.
- It fixes an issue with the logic of the library to call the `global_setup()` and `global_teardown()` functions. The functions were being called correctly when running the tests using "make check" but they were not being called when running the tests using "bats …
> Testlib fixes

- src/bundle.c
- test/functional/bundleadd/add-also-add-flag.bats
- test/functional/bundleadd/add-include.bats
When installing a bundle using bundle-add, swupd also installs any
dependency not already installed in the system (if any). When the
bundle-add operation is complete, swupd reports how many of the
requested bundles were successfully installed and how many failed, but
if there are bundles that got installed as a side effect because they
are dependencies of the requested bundle(s), they are not included in
the summary of bundle-add.
This commit adds the number of dependencies installed in the summary of
bundle-add so it provides a more accurate view of the changes in the
system.
Closes #679 
> Showing indirect bundles installed by bundle-add

- test/real_content/swupd_repair_fullfiles.bats
- test/real_content/swupd_update.bats
- test/real_content/swupd_update_jump.bats
Now 3 characters are enforced on test prefix, so renaming the real content
tests to RCT
> test: Change the prefix of real content tests

- docs/swupd.1.rst
- src/check_update.c
- src/globals.c
- src/info.c
- src/lib/log.c
- src/lib/log.h
- src/swupd.h
- src/version.c
- swupd.bash
- swupd.zsh
- test/functional/checkupdate/chk-update-format-bump.bats
- test/functional/checkupdate/chk-update-json.bats
- test/functional/mirror/mirror-json.bats
Now, we have global option
and info_verbose logging level.
For this PR, we have verbose for info,
check-update which shows format versions.
This also helps future implementations leverage
the use of a verbose option for their own need.
commands:
swupd check-update --verbose
swupd info --verbose
> Show format number

- Makefile.am
- docs/swupd.1.rst
- src/bundle.c
- src/fullfile.c
- src/helpers.c
- src/lib/list.c
- src/lib/list.h
- src/lib/strings.c
- src/lib/strings.h
- src/repair.c
- src/swupd.h
- src/update.c
- src/verify.c
- swupd.bash
- swupd.zsh
- test/functional/diagnose/diagnose-bundles.bats
- test/functional/diagnose/diagnose-flags.bats
- test/functional/os-install/install-bad.bats
- test/functional/repair/repair-bundles.bats
- test/functional/verify-legacy/verify-bundle.bats
- test/functional/verify-legacy/verify-flags.bats
The PR addresses the following things:
- This PR enables the `-B` / `--bundles` option to diagnose or repair only the specified list of bundles in a safe way.
- When using `--bundles` and a file is being marked as deleted for one of the specified bundles, it makes sure it is not needed by any of the other installed bundles before deleting it.
- Disallow the use of `--bundles` together with `--picky` or `--extra-files-only` for `diagnose` or `repair`. That combination of options is only allowed for `verify` for backward compatibility.
Closes #1035
> Enabling --bundles for diagnose and repair

- Makefile.am
- src/lib/list.c
- test/unit/test_list.c
Function list_deduplicate was not removing all duplicates when there were multiple duplicates of some element.
> Fix a bug in list_deduplicate

- src/hash.c
- src/lib/progress.c
We should fail with a correct return code on errors, instead of aborting.
> abort: Don't use abort unless is an OOM error

- src/check_update.c
- test/functional/checkupdate/chk-update-format-bump.bats
- test/functional/testlib.bash
Suggested change on check-update --verbose. Print extra line with latest version in current format.o
The only 2 cases where this will be different from latest version is in the case of a format bump or
in the case where a format is explicitly stated using -F.
Some samples:
$ swupd check-update --verbose
current os version: 31130 (format 29) 
latest server version: 31130 (format 29) 
latest version in format 29: 31130
there are no updates available
<BR>
$ swupd check-update -F staging --verbose
Current OS version: 31140 (format 29) 
Latest server version: 31130 (format 29) 
Latest version in format staging: 31140 (format 29) 
There are no updates available
<BR>
$ swupd check-update -F 28 --verbose
Current OS version: 31130 (format 29) 
Latest server version: 31130 (format 29) 
Latest …
> Suggestion: Check update

- src/check_update.c
- src/mirror.c
- src/swupd_exit_codes.h
- src/version.c
- test/functional/signature/version-sig-check.bats
Turning on again, but partially the signature check for latest version file.
- If signature is missing (i.e. older mixer was used to generate the update),
swupd will print warnings and proceed.
- If signature is wrong, swupd will print error messages and fail the operation.
This isn't suppose to happen even if users are using old mixers.
- If flag --nosigcheck is used swupd will print warnings and proceed.
> version: Turn on partially the latest signature check

- Makefile.am
- docs/RELEASE_NOTES_DRAFT
- docs/swupd.1.rst
- src/bundle_info.c
- src/helpers.c
- src/main.c
- src/swupd.h
- src/swupd_internal.h
- src/update.c
- swupd.bash
- swupd.zsh
- test/functional/bundleinfo/bundle-info-basic.bats
- test/functional/bundleinfo/bundle-info-files.bats
- test/functional/bundleinfo/bundle-info-includes.bats
- test/functional/testlib.bash
The bundle-info command shows detailed data related to a specified
bundle. Among the data currently displayed it includes:
- If the bundle is installed or not
- If the bundle is experimental or not
- If the bundle is installed, it shows if there is an existing update
for the bundle
- The latest available version of the bundle
- The size of the bundle and all its dependencies
- The size needed in disk to install a bundle if not installed
This commit also adds the following command flags:
--version: so a user can display information for a bundle in a
specific version, not only the current version.
--includes: this flag can be used to show all optional and required
bundles that are directly and indirectly included by the specified
bundle.
--files: this flag can be used to show all files that …
> Implement bundle-info command

- .travis.yml
- test/functional/bundleinfo/bundle-info-files.bats
- test/functional/bundleinfo/bundle-info-includes.bats
Adding functional tests related to the bundle-info and verify (legacy) commands to be run in Travis as part of the CI.
> Adding bundle-info and verify-legacy tests to CI

- .travis.yml
We don't need the Clearlinux certificates to run standard tests, so
don't install them anymore
> travis: Don't install clearlinux certificates on travis

- src/bundle.c
- src/bundle.h
- src/bundle_list.c
- src/swupd.h
Move functions specific from bundle_list to bundle_list.c. Keep in bundle.c only
generic bundle functions and create a bundle header file to export them.
Bundle-remove is still left to avoid rebase conflicts.
> bundle: Reorganize functions on bundle.c

- src/bundle.c
- src/bundle.h
- src/bundle_add.c
- src/helpers.c
- src/os_install.c
- src/subscriptions.c
- src/swupd.h
- src/verify.c
- test/functional/os-install/install-bad.bats
- test/functional/os-install/install-multiple.bats
- test/functional/testlib.bash
When os-install is used to install an OS and the --bundles option is used
to specify some bundles that should be installed in the system along
with the OS, the bundles specified should be tracked.
Closes #1153
> Track bundles specified in os-install

- src/bundle.c
- src/bundle_add.c
- src/curl.c
- src/hashdump.c
- src/helpers.c
- src/lib/sys.c
- src/mirror.c
- src/swupd.h
- src/update.c
- src/verify.c
mk_full_filename() and sys_path_join() does almost the same thing.
sys_path_join() was prefered because it works best with null strings and
there were problems when using mk_full_filename() for urls
> sys: Use function from sys instead of mk_full_filename

- Makefile.am
- config
- docs/swupd.1.rst
- src/os_install.c
- src/swupd.h
- src/verify.c
- swupd.bash
- swupd.zsh
- test/functional/os-install/install-no-also-add.bats
When the --skip-optional flag is set, optional (also-add) bundles will
be skipped.
Fixes: #1182
> os_install: Skip optional bundles when flag set

- .travis.yml
- Makefile.am
- configure.ac
- src/3rd_party.c
- src/3rd_party_add.c
- src/3rd_party_internal.h
- src/3rd_party_list.c
- src/3rd_party_remove.c
- src/main.c
- src/swupd_internal.h
- swupd.bash
- swupd.zsh
This PR starts the third-party repo-add, delete, list feature
for swupd. This PR also add support for configure flag
to build swupd optionally, off by default.
**Repo Add:**
sudo swupd 3rd-party add <repo_name> \<url\>
**Repo Remove:**
sudo swupd 3rd-party remove <repo_name>
**Repos List:**
sudo swupd 3rd-party list
> Add third-party skeletal features

- .github/workflows/ccpp.yml
- test/functional/testlib.bash
- test/functional/usability/usa-config-file.bats
Always save the config file in another directory so we won't have
problems on running the config tests in parallel. Before this patch
if you run the config tests in parallel with any other tests you could
end up having false-negatives.
> test: Don't conflict config tests with other tests

- .github/workflows/ccpp.yml
Github job timeout is 6 hours, but we are sure that any job will take around
20~30 minutes to run. Set a one hour timeout to make sure that hung jobs aren't
going to be blocking us for a long time.
> actions: Set a timeout of 1 hour to github jobs

- .github/workflows/ccpp.yml
- Makefile.am
- test/code_analysis/compliant.bats
Now make check is only running unit tests and a new target,
functional-check is used for bat tests. The major win on that
was that now we can use find to look for all bat tests in the
functional library and we don't need to keep the BATS list
updated.
> Makefile: Change behavior of make check

- .github/workflows/ccpp.yml
Distcheck is light now, so adding it to github actions to make sure
we aren't breaking the build on a dist package
> actions: Test make distcheck on github actions

- test/functional/testlib.bash
The commit also fixes a bug with the same tests which was causing the
test environment to be left behind.
> Fix problem when running config-file tests

- src/config_loader.c
- src/lib/config_file.c
Section and keys are case insensitive in INI files, so this commit
make changes to the config parser so it converts the sections and keys
while reading them from the file so we don't have to deal with that with
every function that uses the parser.
> Make the config parser case insensitive

- src/bundle_add.c
- src/staging.c
There is an error in the output of the bundle-add command that causes
some messages to go unnoticed when there are failures staging files.
> Fix output adding bundles with staging errors

- Makefile.am
- config
- src/3rd_party.c
- src/3rd_party_bundle_add.c
- src/3rd_party_repos.c
- src/3rd_party_repos.h
- src/bundle_add.c
- src/globals.c
- src/globals.h
- src/helpers.c
- src/swupd.h
- src/swupd_internal.h
- swupd.bash
- swupd.zsh
- test/functional/3rd-party/3rd-party-allow-http.bats
- test/functional/3rd-party/3rd-party-bundle-add-basic.bats
- test/functional/3rd-party/3rd-party-bundle-add-config-file.bats
- test/functional/3rd-party/3rd-party-bundle-add-multi-repo.bats
- test/functional/3rd-party/3rd-party-repo-add.bats
- test/functional/bundleadd/add-no-disk-space.bats
- test/functional/bundleadd/add-no-signature.bats
- test/functional/signature/no-signature.bats
- test/functional/testlib.bash
- test/functional/usability/usa-download-retries.bats
Implement a command swupd 3rd-party bundle-add that can install bundles from a 3rd party repository.
Tasks:
Closes #1177 
> Add ability to install bundles from 3rd-party repositories

- src/3rd_party_bundle_add.c
This commit adds a missing flag in the help menu of 3rd-party
bundle-add.
> Missing --repo flag to 3rd-party bundle-add help

- docs/swupd.1.rst
- src/3rd_party_bundle_add.c
- src/3rd_party_bundle_list.c
- src/swupd_exit_codes.h
- swupd.bash
- test/functional/3rd-party/3rd-party-bundle-list-basic.bats
- test/functional/testlib.bash
This commit adds the --repo flag for the 3rd-party bundle-list command
which can be used to specify the repository from which the bundles are
going to be listed.
This PR is built on top of #1216 
Closes #1179
> Implement --repo flag for 3rd-party bundle-list

- src/3rd_party_add.c
- src/3rd_party_bundle_add.c
- src/3rd_party_bundle_list.c
- src/3rd_party_repos.c
- src/3rd_party_repos.h
- src/bundle_add.c
- src/bundle_list.c
- src/swupd.h
- test/functional/3rd-party/3rd-party-allow-http.bats
- test/functional/3rd-party/3rd-party-bundle-add-basic.bats
- test/functional/3rd-party/3rd-party-bundle-add-config-file.bats
- test/functional/3rd-party/3rd-party-bundle-add-multi-repo.bats
- test/functional/3rd-party/3rd-party-bundle-list-basic.bats
- test/functional/3rd-party/3rd-party-bundle-list-deps.bats
- test/functional/3rd-party/3rd-party-repo-add-negative.bats
- test/functional/3rd-party/3rd-party-repo-add.bats
- test/functional/3rd-party/3rd-party-repo-list.bats
- test/functional/3rd-party/3rd-party-repo-remove.bats
- test/functional/testlib.bash
When using a 3rd-party repository we need to know the current version of the system related to the 3rd-party repository. This version may be different than the version related to the upstream content. The original idea of 3rd-party repositories was that this version would be tracked inside the repo.ini config file. This was not ideal cause it differ from the way swupd tracks version for upstream content. This PR makes a few updates so 3rd-party bundles are handled similarly to the way we handle upstream content.
The PR includes these updates:
- Removes all the code related to handling the version key/value in the
repo.ini file.
- When doing 3rd-party operations, instead of getting the current version of a 3rd-party repo from the repo.ini file, it will now be gotten from the os-release …
> 3rd party os core

- Makefile.am
- src/3rd_party.c
- src/3rd_party_bundle_add.c
- src/3rd_party_bundle_remove.c
- src/3rd_party_repos.c
- src/3rd_party_repos.h
- src/bundle_add.c
- src/bundle_remove.c
- src/swupd.h
- src/swupd_internal.h
- swupd.bash
- test/functional/3rd-party/3rd-party-bundle-remove-basic.bats
- test/functional/3rd-party/3rd-party-bundle-remove-multi-repo.bats
- test/functional/testlib.bash
Implementing the 3rd-party bundle-remove command
This PR adds the ability to remove 3rd-party bundles. If a repo is not specified the bundle will be searched for in all repositories. All options from the normal bundle-remove command are supported with 3rd-party bundles.
**Note:** This PR is built on top of these PRs: #1216, #1225, #1226 and #1227, so they need to be reviewed first (in that order).
> Implementing a command to remove 3rd-party bundles

- Makefile.am
- scripts/flag_validator.bash
- src/3rd_party.c
- src/3rd_party_bundle_info.c
- src/3rd_party_repos.c
- src/bundle_info.c
- src/swupd.h
- src/swupd_internal.h
- swupd.bash
- swupd.zsh
- test/functional/3rd-party/3rd-party-bundle-info-basic.bats
- test/functional/bundleinfo/bundle-info-basic.bats
This commit adds a new "3rd-party bundle-info" command which can be used to show information about a bundle from a 3rd-party repository. If no 3rd-party repository is specified, the bundle is searched for in all available repositories.
This PR is built on top of #1227 and has to be reviewed first.
> Implementation of 3rd-party bundle-info command

- docs/swupd.1.rst
- src/main.c
- src/update.c
After a grace time period, superseded or deprecated commands should be
removed from the help menu so people is not encouraged to use them. They
should continue to work though for backward compatibility.
> Removing superseded commands from the help menu

- Makefile.am
- src/3rd_party.c
- src/3rd_party_repair.c
- src/swupd_internal.h
- swupd.bash
- swupd.zsh
- test/functional/3rd-party/3rd-party-repair-basic.bats
This PR adds the ability to repair bundles from 3rd-party repos.
This PR is built on top of #1232  and has to be reviewed first.
> Implementing the "3rd-party repair" command

- Makefile.am
- src/3rd_party.c
- src/3rd_party_check_update.c
- src/swupd_internal.h
- swupd.bash
- swupd.zsh
- test/functional/3rd-party/3rd-party-check_update_basic.bats
This PR adds the ability to check for updates on 3rd-party repos.
This PR is built on top of #1232 and #1233 and have to be reviewed first.
> Implementing the "3rd-party check-update" command

- config
- scripts/flag_validator.bash
- src/3rd_party.c
- src/3rd_party_bundle_add.c
- src/3rd_party_bundle_info.c
- src/3rd_party_bundle_list.c
- src/3rd_party_bundle_remove.c
- src/3rd_party_diagnose.c
- src/3rd_party_update.c
- src/swupd_internal.h
- swupd.bash
- swupd.zsh
- test/functional/3rd-party/3rd-party-bundle-add-config-file.bats
- test/functional/3rd-party/3rd-party-bundle-info-basic.bats
Housekeeping on 3rd-party commands
This commit does some housekeeping in the 3rd-party commands:
- Initialize the function "progress" only after swupd has initialized successfully.
- Make functions that are not used outside of a file static.
- Avoid using regex or partial verifications on tests when possible.
- Add 3rd-party command flags to the default config file.
- Don't use "repo" in help menus, use the whole "repository" word.
- Add 3rd-party sub-commands to the flag_validator script.
- Add missing values from the autocompletion scripts.
This PR is built on top of #1232, #1233 and #1234 and have to be reviewed first.
> 3rd party housekeeping

- src/3rd_party_add.c
- src/3rd_party_remove.c
- src/3rd_party_repos.c
- src/3rd_party_repos.h
When adding 3rd-party repositories, errors may occur, in these cases the
operation has to be reverted completely because we don't want to be left
with an invalid repo.
> Revert operation when theres an error adding repos

- src/3rd_party_bundle_list.c
- src/bundle_list.c
- test/functional/bundlelist/list-deps-invalid-bundle.bats
- test/functional/bundlelist/list-has-dep-nested-not-installed.bats
When listing bundles using the --deps or --has-dep flags which take a BUNDLE as argument, one or more repositories may not have the specified BUNDLE, but we should not return a SWUPD_INVALID_BUNDLE error unless the bundle is not found in any repository.
This PR enforces that behavior and also modify the output of the different list options to make them more consistent with one another.
This PR is built on top of #1232, #1233, #1234 and #1235 and have to be reviewed first.
> 3rd-party: Ignoring invalid bundle error if exist in one repo

- src/3rd_party_add.c
- src/3rd_party_repos.c
- src/3rd_party_repos.h
- test/functional/3rd-party/3rd-party-repo-add-negative.bats
When adding a 3rd-party repository we need to make sure that the URL
provided by the user is not already assigned to another 3rd-arty
repository, otherwise we can end up having the same repository multiple
times, just with different names.
This commit checks the URL doesn't already exists.
> Verifying the URL of a repo doesn't exist already

- src/helpers.c
This makes sure we always deallocate memory if there was an
error after the initial global_init
> Prevent memory leak

- Makefile.am
- scripts/flag_validator.bash
- src/3rd_party.c
- src/3rd_party_clean.c
- src/clean.c
- src/swupd.h
- src/swupd_internal.h
- swupd.bash
- swupd.zsh
This commit implements the swupd clean command for the 3rd-party bundles so users are able to clean the cache on their state directories.
> Adding "3rd-party clean" command

- src/manifest.c
- src/signature.c
- src/version.c
- test/functional/bundleadd/add-no-signature.bats
- test/functional/signature/cert-chain.bats
- test/functional/signature/corrupted-certificate.bats
- test/functional/signature/corrupted-signature.bats
- test/functional/signature/invalid-certificate.bats
- test/functional/signature/key-rotation.bats
- test/functional/signature/no-signature.bats
- test/functional/signature/version-sig-check.bats
This commit enhance the consistency and readability, of the messages
shown when the signature verification is skipped or fails.
> Consistency with signature verification messages

- src/3rd_party_repos.c
- test/functional/3rd-party/3rd-party-repo-remove.bats
When we remove a 3rd-party repo from the system, we remove the directory
where all its contents got installed, but we don't remove its state
directory.
This commit removes it since we no longer need that state directory.
> Remove the state dir when removing 3rd-party repo

- src/3rd_party_add.c
- src/progress.c
This commit fixes a buffer overflow that was being triggered when adding
3rd-party repositories.
> Fix buffer overflow when adding 3rd-party repos

- src/bundle_info.c
When showing the information of a large bundle, there was a variable
that was incorrectly declared so it was overflowing, turning the size of
the bundle into a negative number.
This commit fixes the issue.
> Fix an error showing the size during bundle-info

- src/3rd_party_repos.c
- src/bundle_info.c
- src/helpers.c
- src/swupd.h
This commit adds a function to print a header in a consistent manner
accross different swupd functions.
> Function to print a header

- src/3rd_party_bundle_list.c
- src/bundle_list.c
- test/functional/3rd-party/3rd-party-bundle-list-deps.bats
- test/functional/bundlelist/list-deps-flat.bats
- test/functional/bundlelist/list-deps-invalid-bundle.bats
- test/functional/bundlelist/list-deps-nested.bats
- test/functional/bundlelist/list-has-dep-nested-server.bats
- test/functional/bundlelist/list-has-dep-nested.bats
- test/functional/bundlelist/list-json.bats
- test/functional/bundlelist/list-no-deps.bats
- test/functional/bundlelist/list-none-has-deps.bats
For some options of bundle-list, like --deps and --has-dep, we sometimes
need to download a considerable amount of manifests, if that happens
swupd just seems to hang for some time, this time could be considerably
in slow networks.
This commit enables the spinner while the manifests are baing downloaded
during a bundle-list operation so users know swupd is not hung and it is
doing some downloading.
> Show spinner when loading manifests in bundle-list

- config
- docs/swupd.1.rst
- src/search_file.c
- swupd.bash
- swupd.zsh
- test/functional/search/search-version.bats
The search-file command is restricted to looking for files in the
current version. This commit adds the --version option to the command
that can be used to seach for files in specific versions of Clear.
Closes #1155
> Add ability to search files in specific version

- src/3rd_party_repos.c
- src/3rd_party_repos.h
- src/helpers.c
- test/functional/3rd-party/3rd-party-allow-http.bats
- test/functional/3rd-party/3rd-party-bundle-add-basic.bats
- test/functional/3rd-party/3rd-party-bundle-add-config-file.bats
- test/functional/3rd-party/3rd-party-bundle-add-multi-repo.bats
- test/functional/3rd-party/3rd-party-bundle-info-basic.bats
- test/functional/3rd-party/3rd-party-bundle-remove-basic.bats
- test/functional/3rd-party/3rd-party-bundle-remove-multi-repo.bats
- test/functional/3rd-party/3rd-party-diagnose-basic.bats
- test/functional/3rd-party/3rd-party-repair-basic.bats
- test/functional/3rd-party/3rd-party-repo-add-negative.bats
- test/functional/3rd-party/3rd-party-repo-add.bats
- test/functional/3rd-party/3rd-party-repo-list.bats
- test/functional/3rd-party/3rd-party-repo-remove-negative.bats
- test/functional/3rd-party/3rd-party-repo-remove.bats
- test/functional/3rd-party/3rd-party-update-basic.bats
- test/functional/3rd-party/3rd-party-update-specific-version.bats
- test/functional/testlib.bash
The name of the 3rd-party repository directory is currently `3rd_party`, this name is incorrect and needs to be changed to `3rd-party`. This PR fixes that.
> Fix name of 3rd-party directory

- src/bundle_info.c
- src/subscriptions.c
- src/swupd.h
- test/functional/bundleinfo/bundle-info-optional.bats
- test/functional/os-install/install-also-add.bats
When using "bundle-info BUNDLE --dependencies", information regarding
BUNDLE is presented to the user, this information includes the list of
direct and indirect dependencies BUNDLE has. All direct includes that
are optional (also-add) are marked as such, while there is no way to
distiguish what indirect dependencies are optional with the provided
information.
This commit expands the information shown by the command so indirect
dependencies that are optional are shown as such along with info about
the status of that dependency.
> Show what indirect dependencies are optional

- src/bundle.c
- src/bundle.h
- src/bundle_list.c
- src/bundle_remove.c
Using the "bundle-list --has-dep BUNDLE" command shows a list of bundles
that have BUNDLE as a dependency. However this list is not considering
the bundles that have BUNDLE as an optional dependency.
This commit completes the list by including these bundles.
Closes #1159 
> Show optional includes with bundle-list --has-dep

- docs/swupd.1.rst
- src/3rd_party.c
- src/3rd_party_add.c
- src/3rd_party_bundle_add.c
- src/3rd_party_bundle_info.c
- src/3rd_party_bundle_list.c
- src/3rd_party_bundle_remove.c
- src/3rd_party_check_update.c
- src/3rd_party_diagnose.c
- src/3rd_party_list.c
- src/3rd_party_remove.c
- src/3rd_party_repair.c
- src/3rd_party_update.c
- src/autoupdate.c
- src/bundle_add.c
- src/bundle_info.c
- src/bundle_list.c
- src/bundle_remove.c
- src/check_update.c
- src/hashdump.c
- src/mirror.c
- src/os_install.c
- src/repair.c
- src/search_file.c
- src/update.c
- src/verify.c
This PR makes a couple of improvements in the swupd documentation:
- Adds a short description to all swupd commands.
- Rephrases the `--picky` related documentation to make it clearer to the user.
Closes #1205 
Closes #1108
> swupd documentation improvements

- src/3rd_party_repos.c
- src/3rd_party_repos.h
- test/functional/3rd-party/3rd-party-allow-http.bats
- test/functional/3rd-party/3rd-party-bundle-add-basic.bats
- test/functional/3rd-party/3rd-party-bundle-add-config-file.bats
- test/functional/3rd-party/3rd-party-bundle-add-multi-repo.bats
- test/functional/3rd-party/3rd-party-bundle-remove-basic.bats
- test/functional/3rd-party/3rd-party-diagnose-basic.bats
- test/functional/3rd-party/3rd-party-repair-basic.bats
- test/functional/3rd-party/3rd-party-repo-add.bats
- test/functional/3rd-party/3rd-party-repo-list.bats
- test/functional/3rd-party/3rd-party-repo-remove-negative.bats
- test/functional/3rd-party/3rd-party-repo-remove.bats
- test/functional/3rd-party/3rd-party-update-basic.bats
- test/functional/3rd-party/3rd-party-update-specific-version.bats
- test/functional/testlib.bash
This commit moves the path where the content from 3rd-party bundles is
going to be installed from opt/3rd-party/<bundle_name> to
/opt/3rd-party/bundles/<bundle_name> so bundle directories are separated
from other top level directories like bin.
> Moving the content from 3rd-party bundles

- src/3rd_party_bundle_list.c
- src/bundle_list.c
- src/subscriptions.c
- src/swupd.h
- test/functional/bundlelist/list-deps-nested.bats
Sometimes is useful to see the list of dependencies in a tree view form, for example when trying to remove bundles from a system.
This commit adds the ability of listing the dependencies of a bundle in  a tree view when --verbose is used.
Example:
```
$ sudo ./swupd bundle-list --deps vim
Loading required manifests...
Bundles included by vim:
- findutils
- lib-openssl
- libstdcpp
- os-core
- p11-kit
- perl-basic
- python3-basic
Total: 7
$ sudo ./swupd bundle-list --deps vim --verbose
Loading required manifests...
Bundles included by vim:
* vim
|-- perl-basic
|-- lib-openssl
|-- p11-kit
|-- findutils
|-- os-core
|-- os-core
|-- os-core
|-- os-core
|-- python3-basic
|-- libstdcpp
|-- os-core
|-- p11-kit
|-- findutils
|-- os-core
|-- os-core
|-- os-core
|-- os-core
Total: 7
```
Closes #929
> Implementing tree view for `bundle-list --deps`

- src/3rd_party_update.c
- test/functional/3rd-party/3rd-party-update-basic.bats
- test/functional/3rd-party/3rd-party-update-specific-version.bats
Swupd should not run post-update scripts after updating content from a
3rd-party repo since it may threaten the security of the system.
> Do not run scripts after updating from 3rd-party

- Makefile.am
- src/bundle_info.c
- src/bundle_list.c
- src/bundle_remove.c
- src/extra_files.c
- src/fullfile.c
- src/hash.c
- src/lib/comp_functions.c
- src/lib/comp_functions.h
- src/lib/list.h
- src/lib/strings.c
- src/lib/strings.h
- src/manifest.c
- src/manifest.h
- src/search_file.c
- src/subscriptions.c
- src/swupd.h
- src/swupd_comp_functions.c
- src/swupd_comp_functions.h
- src/update.c
- src/verify.c
We used compare-like functions as arguments to other functions that
filter, sort, compare data. These functions are scattered accros the
code and they are sometimes difficult to identify so there is a lot of
code duplication.
This commit organizes all the compare like functions throughout the code
in the same place and with standard naming so it is easier to find them
and reuse them.
Closes #1167
> Organizing compare-like functions

- config
- docs/swupd.1.rst
- src/3rd_party_bundle_list.c
- src/bundle_info.c
- src/bundle_list.c
- src/helpers.c
- src/search_file.c
- src/swupd.h
- swupd.bash
- swupd.zsh
- test/functional/3rd-party/3rd-party-bundle-info-basic.bats
- test/functional/bundleinfo/bundle-info-basic.bats
- test/functional/bundleinfo/bundle-info-status.bats
- test/functional/bundlelist/list-all.bats
- test/functional/bundlelist/list-experimental.bats
- test/functional/bundlelist/list-installed.bats
The "bundle-list" command can be used to show all installed bundles in the system, however, currently there is no way to know which of those installed bundles were implicitly or explicitly installed. Issue #1272 was opened to implement a way of getting this information with swupd.
This PR implements the "--status" flag for bundle-list which can be used to show which bundles were explicitly or implicitly installed.
This PR also adds this information to the installation status of the bundle-info command.
Closes #1272
> Show what bundles are explicitly installed vs implicitly installed with bundle-list

- Makefile.am
- src/3rd_party_repos.h
- src/alias.c
- src/alias.h
- src/config_loader.h
- src/swupd_comp_functions.h
- src/swupd_progress.h
- src/xattrs.h
We have a list of header files that weren't documented yet. Add them explicitly
to the check to prevent us to lower the quality of the documentation of headers
that are well documented.
Also fixing some documentation that weren't included because of incorrect style.
> docs: Explicitly adding a list of files in the doc check exclude list

- src/3rd_party_bundle_list.c
- src/3rd_party_check_update.c
- src/3rd_party_list.c
- src/3rd_party_remove.c
Some of the regular swupd commands can be run with a regular user, for
example check-update, however this is not the case for 3rd-party
commands, all of them require root privileges since they all need to at
least read data from root owned directories.
This commit enables swupd to require root privileges for all 3rd-party
commands at initialization time.
> Force to run all 3rd-party commands with root

- config
- docs/RELEASE_NOTES_DRAFT
- docs/swupd.1.rst
- src/helpers.c
- src/lib/log.h
- src/lib/sys.h
- src/repair.c
- src/staging.c
- src/swupd.h
- src/verify.c
- swupd.bash
- swupd.zsh
- test/functional/bundleadd/add-verify-fix-path.bats
- test/functional/diagnose/diagnose-path.bats
- test/functional/repair/repair-path.bats
- test/functional/update/update-verify-fix-path-hash-mismatch.bats
- test/functional/update/update-verify-fix-path-missing-dir.bats
When diagnosing/repairing a system, sometimes is useful to only diagnose/repair a
specific file or path.
This commit implements the --file option for diagnose/repair so a file or path
can be diagnosed/repaired only instead of doing it to the whole OS or a whole
bundle.
Closes #1150
> Implement --file option for diagnose and repair

- swupd.bash
The "verify" command was superceded many months ago. The command
still works and will continue to work for backward compatibility, but
users are discouraged to use it. To motivate users to use the newer
commands, all references to the legacy command has now been removed
from the swupd man page and the help menus.
This commit removes the command from the bash autocompletion script too.
This should have been done as part of PR #1231 
> Removing legacy verify command from autocompletion

- src/manifest_parser.c
- src/swupd.h
Add the 'x' to the manifest parser in the 4th column of file attributes,
this will indicate a file should be "exported".
> Add support for 'x' in the manifest parser

- src/3rd_party_add.c
- src/3rd_party_repos.c
- src/3rd_party_repos.h
- src/globals.c
- src/globals.h
When running 3rd-party operations, most of the times these need to
overwrite some of the global variables in order to reuse the code
use for normal swupd operations.
This commit add means to backup those global variables, so they can be
recovered as necessary.
> Backup global variables used by 3rd-party ops

- src/3rd_party_bundle_add.c
This commit notifies the user that the 3rd-party bundle they installed
isn't configured properly so they can know something about the quality
of the 3rd-party repository they are using.
> Warn user when a 3rd-party binary isn't executable

- src/3rd_party_repos.c
- src/globals.c
- src/globals.h
When using 3rd-party repos, swupd looks for the certificate to use
inside the repository directory, if the user specifies another location
it is just ignored.
If the user specifies a different path for the certificate, it should be
used. This commit fixes that.
> Use the user specified path for 3rd-party cert

- src/3rd_party_bundle_remove.c
- src/3rd_party_repos.c
- src/3rd_party_repos.h
- src/bundle_remove.c
- src/swupd.h
- test/functional/3rd-party/3rd-party-bundle-remove-basic.bats
- test/functional/3rd-party/3rd-party-bundle-remove-exported-bin.bats
- test/functional/3rd-party/3rd-party-bundle-remove-multi-repo.bats
When removing a 3rd-party bundle, all scripts that export the binaries of the bundle should be removed from the target system unless they are still required by another installed 3rd-party bundle.
This PR is built on top of #1303 and it has to be reviewed and merged first.
Closes #1278
> Remove exported 3rd-party binaries after bundle-remove

- src/3rd_party_bundle_remove.c
- src/3rd_party_remove.c
- src/3rd_party_repos.c
- src/3rd_party_repos.h
- src/bundle_remove.c
- src/swupd.h
- test/functional/3rd-party/3rd-party-bundle-remove-basic.bats
- test/functional/3rd-party/3rd-party-bundle-remove-exported-bin.bats
- test/functional/3rd-party/3rd-party-bundle-remove-multi-repo.bats
- test/functional/3rd-party/3rd-party-repo-remove-negative.bats
- test/functional/3rd-party/3rd-party-repo-remove.bats
When a 3rd-party repository is removed, all the content installed from it must be removed from the system. But also those exported binaries from the repo being deleted should also be deleted.
This PR is built on top of #1303 and #1304 and they have to be reviewed first in that order.
Closes #1291
> Remove all exported binaries from 3rd-party bundles when removing a repo

- data/swupd-update.service.in
Instead of creating a command and service for enabling and disabling autoupdates specifically for `3rd-party` content, this PR piggybacks into the current `swupd-update.service` to also perform an update of the 3rd-party content based on `swupd-update.timer`. This means the user will have to enable/disable autoupdate for both, the swupd upstream content and 3rd-party content.
Closes #1283
> Enabling autoupdate of 3rd-party content

- src/3rd_party_bundle_add.c
- src/3rd_party_repos.c
- src/3rd_party_repos.h
- src/3rd_party_update.c
- src/swupd.h
- src/update.c
- test/functional/3rd-party/3rd-party-update-basic.bats
- test/functional/3rd-party/3rd-party-update-exported-bin.bats
- test/functional/3rd-party/3rd-party-update-specific-version.bats
- test/functional/testlib.bash
When a 3rd-party repository is updated, if one of the updated bundles
has updated binaries, the scripts that export those binaries should also
be updated. This commit implements that update.
Closes #1279
> Update exported binaries during a "swupd 3rd-party update"

- src/3rd_party_remove.c
When removing a 3rd-party repository, if there is an error while setting
up the global variables of the repository, the error code is lost and
swupd reports as if the removal was successful even when it failed. This
commit fixes that issue.
> Fixing a bug removing a 3rd-party repo that fails

- .github/workflows/ccpp.yml
- scripts/build_ci.bash
- scripts/build_ci_style.bash
There are some build requirements that are only necessary for style check.
Reduce the build time by running them only for style check job.
> test: Reduce build time of bats test

- src/staging.c
If there are multiple symlinks to the same destination, there
will only be one file in staging for all of the symlinks, and
the current code will opportunistically try to link(2) all of
them into their final destination.
This will usually succeed, but link(2) on linux doesn't follow
symlinks.
This means all the original symlinks will be converted from
being individual files into one file with multiple hardlinks.
As an example, we get this:
```
root@host:~# ls -li /a/bin/ash /a/bin/busybox.nosuid /a/bin/cat /a/bin/date
24 lrwxrwxrwx  172 root     root            19 Mar  9  2018 /a/bin/ash -> /bin/busybox.nosuid
26 -rwxr-xr-x    1 root     root        488760 Mar  9  2018 /a/bin/busybox.nosuid
24 lrwxrwxrwx  172 root     root            19 Mar  9  2018 /a/bin/cat -> /bin/busybox.nosuid
24 …
```
> staging: don't convert symlinks to hardlinks

- .github/workflows/ccpp.yml
- test/functional/bundleadd/add-client-certificate.bats
- test/functional/bundlelist/list-client-certificate.bats
- test/functional/bundleremove/remove-client-certificate.bats
- test/functional/checkupdate/chk-update-client-certificate.bats
- test/functional/diagnose/diagnose-client-certificate.bats
- test/functional/search/search-client-certificate.bats
- test/functional/update/update-client-certificate.bats
- test/functional/update/update-non-responsive.bats
- test/functional/update/update-slow-server.bats
- test/functional/usability/usa-external-modules.bats
Rename from TRAVIS to RUNNING_IN_CI
> Rename variable used to identify if tests are running in a CI

- src/3rd_party_add.c
- src/signature.c
- src/signature.h
- src/swupd.h
- src/version.c
- test/functional/3rd-party/3rd-party-repo-add-certificate.bats
When trying to add the repository for the first time, download the public
certificate published by the 3rd party repository and with a user confirmation,
use it to install the 3rd-party os-core. After that the official certificate will
be installed for future commands.
> 3rd-party: Import certificate from 3rd-party repository on repo add

- src/3rd_party_bundle_remove.c
- src/3rd_party_repos.c
- src/bundle_remove.c
- src/helpers.c
- src/lib/list.c
- src/lib/list.h
- src/swupd.h
- test/functional/3rd-party/3rd-party-bundle-add-export-bin.bats
- test/functional/3rd-party/3rd-party-bundle-remove-exported-bin.bats
- test/functional/3rd-party/3rd-party-repo-add-certificate.bats
- test/functional/3rd-party/3rd-party-repo-add.bats
- test/functional/testlib.bash
When in a 3rd-party repository one bundle has one binary file that
is exported, and the same file is included in another bundle, only
it is not exported in this bundle, when we remove the bundle that
exports the file, the file should be unexported regardless of the file
still being installed since the bundle that is still in the system is
not exporting it.
Closes #1322
> Handle conflicting 3rd-party binaries

- src/3rd_party_add.c
- src/3rd_party_repos.c
- test/functional/3rd-party/3rd-party-allow-http.bats
- test/functional/3rd-party/3rd-party-bundle-add-basic.bats
- test/functional/3rd-party/3rd-party-bundle-add-config-file.bats
- test/functional/3rd-party/3rd-party-bundle-add-dangerous-flags.bats
- test/functional/3rd-party/3rd-party-bundle-add-export-bin.bats
- test/functional/3rd-party/3rd-party-bundle-add-multi-repo.bats
- test/functional/3rd-party/3rd-party-bundle-info-basic.bats
- test/functional/3rd-party/3rd-party-bundle-list-basic.bats
- test/functional/3rd-party/3rd-party-bundle-list-deps.bats
- test/functional/3rd-party/3rd-party-bundle-remove-basic.bats
- test/functional/3rd-party/3rd-party-bundle-remove-exported-bin.bats
- test/functional/3rd-party/3rd-party-bundle-remove-multi-repo.bats
- test/functional/3rd-party/3rd-party-check-update-basic.bats
- test/functional/3rd-party/3rd-party-diagnose-basic.bats
- test/functional/3rd-party/3rd-party-repair-basic.bats
- test/functional/3rd-party/3rd-party-repo-add-certificate.bats
- test/functional/3rd-party/3rd-party-repo-add.bats
- test/functional/3rd-party/3rd-party-repo-list.bats
- test/functional/3rd-party/3rd-party-repo-remove-negative.bats
- test/functional/3rd-party/3rd-party-repo-remove.bats
- test/functional/3rd-party/3rd-party-update-basic.bats
- test/functional/3rd-party/3rd-party-update-dangerous-flags.bats
- test/functional/3rd-party/3rd-party-update-exported-bin.bats
- test/functional/3rd-party/3rd-party-update-specific-version.bats
- test/functional/testlib.bash
The repo.ini file was being created in the swupd state directory, this
was not ideal since it prevented the state directory from being used for
multiple target paths.
This commit moves the repo.ini file out of the state directory and into
the 3rd-party content directory.
> Move 3rd-party repo.ini out of the state directory

- src/3rd_party_repos.c
If the path for the repo.ini file doesn't exist, create it.
Closes #1329
> Make sure the path for repo.ini always exist

- src/3rd_party_bundle_add.c
- test/functional/3rd-party/3rd-party-bundle-add-symlink.bats
- test/functional/testlib.bash
When a symlink is added to a 3rd-party repository it will be broken
on the statedir and stat command will fail. We need to use lstat, to
get information about the symlink and not the file that it's pointing
to.
> 3rd-party: Support adding symlinks to 3rd party repositories

- src/3rd_party_repos.c
When running an operation that should run in all the 3rd-party repos
installed, if one repo fails to set up, the process is aborted and the
operation is never performed in the repos after the failed repo.
This PR changes the proces so if one repo fails to set up it is just
skipped so the operation is attempted in the other repos.
> Multi-repo operations skip bad repo

- src/scripts.c
It's possible to create a post_update script to run ld_config, but we
had problems with this in the past, so it was decided to hardcode that
on swupd instead of relying on scripts.
> scripts: Always run ld_config before running any update scripts

- src/3rd_party_add.c
When users add a 3rd-party repository they are asked if they want to
trust the certificate, this commit makes possible to use the
--assume flag to answer that question.
> Use of --assume and --yes flags to confirm a cert

- src/3rd_party_remove.c
This extra step was causing the percentage to be printed twice:
```
$ sudo ./swupd 3rd-party remove swupd-master
Loading required manifests...
[100%]
Removing repository swupd-master...
Removing 3rd-party bundle binaries...
[100%]
[100%]
```
> Removing extra step from 3rd-party remove

- test/functional/testlib.bash
Sometimes a test fails before finisihing to create all the required
directories under the testdir. So destroy_environment thinks this is
not a valid test environment.
Touching a dot file to show that the directory is a test environment
instead on counting on its content.
Fixes bug #1135
> tests: Remove test leftovers when the directory is incomplete

- src/bundle_add.c
- test/functional/3rd-party/3rd-party-bundle-add-state.bats
- test/functional/testlib.bash
When adding an upstream bundle, we apply some heuristics to the bundle
files and based on that some files are skipped from being installed.
These heuristics don't apply to 3rd-party bundles.
This commit skips running heuristics when adding 3rd-party bundles.
Closes #1342 
> Do not apply heuristics to 3rd-party files

- config
- docs/swupd.1.rst
- src/3rd_party_remove.c
- swupd.bash
- swupd.zsh
- test/functional/3rd-party/3rd-party-repo-remove-corrupt.bats
This commit allow users to force the deletion of corrupt 3rd-party repos
which will end up deleting most of the repo's files, except for the
scripts that exported files from that repo.
Closes #1343
> Forcing the removal of corrupt 3rd-party repos

- src/verifytime.c
stime is deprecated in newer versions of glibc, so using the recommended
clock_settime() instead.
> time: stop using deprecated function stime()

- config
- src/3rd_party.c
Reordering so it matches the order of the regular swupd commands. Also
adding missing values to config file.
> Reordering 3rd-party subcommands in help

- src/3rd_party_update.c
When updating 3rd-party bundles, swupd validates the files to be updated
to make sure there were no changes in file permissions that could be
risky for the system, it uses stat to get the file permissions. The
problem is that stat follows links, and while the files are in staging,
the links are really pointing to invalid locations so stat will always
fail.
This commit fixes the problem by not following links when validating
file permissions.
> Do not follow links when validating staged files

- configure.ac
- scripts/build_ci.bash
Instead of requiring an --enable-third-party, as 3rd-party was already
released, we can make it default.
> 3rd-party: Make 3rd-party default in the build

- src/signature.c
When building swupd with --disable-signature we need to have all
signature functions with a dummy implementation that doesn't validate
the signature.
> signature: Dummy signature_verify_data() function missing

- src/swupd_build_opts.h
We print all flags selected on build time on swupd -v. This is useful
to check if an specific swupd binary has one specific feature enabled.
> build_opts: Print third party build info on swupd -v

- config
- docs/swupd.1.rst
- src/3rd_party_diagnose.c
- src/3rd_party_repair.c
- src/os_install.c
- src/repair.c
- src/verify.c
- swupd.zsh
Vi isn't a bundle anymore. Replacing all examples to vim.
Related to #1369
> docs: Replace vi with vim

- docs/swupd.1.rst
- src/os_install.c
- test/functional/os-install/install-multiple.bats
When doing a system install with "os-install --bundles" if the list of
bundles to install includes only "os-core" the install fails.
This commit fixes the issue.
Closes #1369 
> Bug fix: os-install --bundles with os-core fails

- scripts/build_and_run_tests.bash
Besides having a script that is used to run tests on github
actions CI, adding another script that can be used in any
system to build swupd with different configurations and
run all needed tests.
> scripts: Add a script to run swupd basic tests

- test/functional/mirror/mirror-allow-http.bats
On proxy envs we may need to wait for a timeout before proceeding and
this can slow tests down.
> tests: On mirror tests don't use possible real server names

- src/staging.c
- test/functional/os-install/install-hardlink-symlink.bats
- test/functional/testlib.bash
Staging: Don't create hardlinks when installing symlinks
Alternative solution to solution proposed on #1318
Instead of trying to create a link just don't try to link symlinks.
Tested patch using bsdtar and implemented automated testing to
validate solution.
> Staging: Don't create hardlinks when installing symlinks

- src/3rd_party_add.c
- src/3rd_party_repos.c
- src/3rd_party_repos.h
- src/lib/sys.c
- src/lib/sys.h
- test/functional/3rd-party/3rd-party-repo-add-certificate.bats
- test/functional/3rd-party/3rd-party-repo-add-negative.bats
When adding a 3rd-party repo, if the repo cannot be added it is reverted
back. However if a user uses an incorrect URL that hangs and the user
cancels the process, the repo add is never rolled back, which will cause
the invalid repo to be left in the system.
This commit fixes the issue by making sure the repo is reachable and
somewhat valid before adding it to the config file.
Closes #1384
> 3rd-party:bug_fix: don't add unreachable repos

- config
- docs/swupd.1.rst
- src/3rd_party_add.c
- swupd.bash
- swupd.zsh
- test/functional/3rd-party/3rd-party-repo-add-force.bats
When swupd is adding a 3rd-party repo and it finds a non empty directory
that matches the repo's name in the content path it warns the user and
aborts. This may have been caused by a corrupt repo.
This commit adds a --force flag to allow users to instruct swupd to
remove the existing directory and its conent and continue adding the
3rd-party repo.
Closes #1388
> 3rd-party: add force option to "3rd-party add"

- src/manifest.c
- test/functional/update/update-manifest-delta-recover.bats
When a manifest delta was incorrect, the full manifest was used. But in the
case of a correct delta that produces an invalid manifest, swupd was never
trying to download the full manifest.
Changing code to try to use deltas only once. On first error, always retry
downloading the full manifest.
> delta: Don't retry to use manifest deltas

- .github/workflows/ccpp.yml
- scripts/github_actions/build_ci.bash
- scripts/github_actions/build_ci_dependencies.bash
- scripts/github_actions/build_ci_style.bash
Some packages we need to build swupd are not available on ubunutu-latest
so we need to download and build from source. This process is slow and
caching can save us some significant time on build.
> actions: cache dependencies for swupd

- scripts/build_and_run_tests.bash
- scripts/github_actions/build_ci.bash
- src/globals.c
- src/helpers.c
If the path where swupd is running is removed getcwd errors will occurs, mostly
because of multiple commands swupd executes. So move to directory "/", no mather
where swupd is going to be installed, to make sure the path is always existent.
Fixes #1078
> swupd_init: Make sure swupd is always runnin in an existing path

- src/3rd_party_repos.c
- test/functional/3rd-party/3rd-party-bundle-add-export-bin.bats
When creating a wrapper for 3rd-party binaries, append relative
/usr/share and /usr/local/share to XDG_DATA_DIRS variable and /etc
to XDG_CONF_DIRS.
Fix #1411
> 3rd-party: Add 3rd-party share directories to XDG dirs

- src/3rd_party_repair.c
- src/3rd_party_repos.c
- src/3rd_party_repos.h
- src/3rd_party_update.c
- src/swupd.h
- src/verify.c
- test/functional/3rd-party/3rd-party-repair-basic.bats
- test/functional/3rd-party/3rd-party-repair-exported-bin.bats
- test/functional/3rd-party/3rd-party-update-exported-bin.bats
When updating a 3rd-party bundle, if any of its binaries is modified,
or the binary is new swupd needs to recreate the wrapper script.
During a 3rd-party repair, the wrapper scripts of all binaries verified
should be regenerated regardless of if the binary was repaired or not.
Related to #1413
> 3rd-party: regenerate the wrapper script if a binary changes during an update

- test/functional/testlib.bash
When updating a bundle using testlib, if the file is updated, and the
update includes a file type change, testlib was updating the manifest
with the correct type but was overwriting the other status flags, so if
a file was marked as 'x' (exported) before, that flag was being removed.
This commit fixes the issue by only updating the flag that relates to
the file type.
> Testlib: keep the current status on type change

- src/lib/sys.c
- src/lib/sys.h
- src/staging.c
- test/functional/update/update-type-changes-dir-to-file.bats
- test/functional/update/update-type-changes-file-to-recursive-symlink.bats
- test/functional/update/update-type-changes-file-to-symlink.bats
- test/functional/update/update-type-changes-symlink-to-file.bats
When during an update a directory was removed and replaced by a symlink to another directory that contains one or more files with the same name  as files in the directory that was removed, swupd will remove the directory from the target system and then it will try to remove each one     of the files that were contained in the directory. Since the directory is now a symlink to another existing directory, it may end up deleting the files from the other directory. swupd should not follow links when removing files during the staging process.
Closes #890
Note: for the tests in this PR to work #1380 needs to be reviewed and merged first.
> Bug_fix: Do not follow symlinks when removing files during staging or update can end up removing incorrect files

- test/functional/testlib.bash
When generating the certificate for tests, openssl is printing messages
to the terminal, we are already selecting what to print by using the
debug_msg() function, so these unwanted messages shouldnot be printed.
> Testlib: do not print the result of openssl

- src/staging.c
During staging, if a file is marked for deletion, and the path to
the file, or the file istelf is a simlink, then it is not removed. This
is incorrect, if the file itself is a symlink it is fine to remove it,
the only case when it should not be removed is when the path to it
contain a symlink.
Closes #1424
> Bug_fix: Check if directory is absolute, not file

- src/lib/sys.c
Always remove the last slash of a path when using sys_path_join().
This is needed because some functions compare different paths and the
trailing slash will lead to incorrect results.
For example:
- sys_path_is_absolute(sys_path_join("/usr/")) returns false.
> sys: Also remove trailing separators in sys_path_join()

- src/3rd_party_repos.c
- src/info.c
- test/functional/api/api-3rd-party-info.bats
- test/functional/api/api-info.bats
- test/functional/mirror/mirror-json.bats
- test/functional/testlib.bash
- swupd info
- swupd 3rd-party info
Related to #1393 
> API: output for [3rd-party] info

- src/mirror.c
We need to call globals_init (called by swupd_init) before calling any
function that uses path_prefix.
`mirror --set` using the default path is failing.
> mirror: path_prefix is not processed before trying to set the mirror

- src/3rd_party_repos.c
- src/check_update.c
- src/lib/log.c
- src/lib/log.h
- test/functional/api/api-3rd-party-checkupdate.bats
- test/functional/api/api-checkupdate.bats
- test/functional/checkupdate/chk-update-json.bats
- swupd check-update
- swupd 3rd-party check-update
> API: output for [3rd-party] check-update

- src/signature.c
- src/signature.h
- src/version.c
> signature: Use void pointer to store pointers to bytes in memory

- src/3rd_party_repos.c
- src/3rd_party_repos.h
- src/3rd_party_update.c
- src/lib/sys.c
- src/lib/sys.h
- src/manifest.c
- src/signature.c
- src/subscriptions.c
- src/version.c
- test/functional/3rd-party/3rd-party-update-basic.bats
- test/functional/3rd-party/3rd-party-update-export-template-multi-repo.bats
- test/functional/3rd-party/3rd-party-update-export-template.bats
- test/functional/3rd-party/3rd-party-update-exported-bin.bats
- test/functional/testlib.bash
When the template used for creating the wrapper scripts changes, all
exported binaries should have the scripts regenerated during updates
regardless of if the binary changed.
Closes #1413
> 3rd-party: Regenerate wrapper on template change

- src/bundle_remove.c
- test/functional/api/api-3rd-party-bundle-remove.bats
- test/functional/api/api-bundle-remove.bats
- swupd bundle-remove
- swupd 3rd-party bundle-remove
> API: output for [3rd-party] bundle-remove

- src/bundle_add.c
- test/functional/api/api-3rd-party-bundle-add.bats
- test/functional/api/api-bundle-add.bats
- swupd bundle-add
- swupd 3rd-party bundle-add
> API: output for [3rd-party] bundle-add

- test/functional/3rd-party/3rd-party-bundle-info-basic.bats
- test/functional/3rd-party/3rd-party-bundle-list-deps.bats
- test/functional/bundleinfo/bundle-info-files.bats
- test/functional/bundleinfo/bundle-info-includes.bats
- test/functional/bundleinfo/bundle-info-optional.bats
- test/functional/bundlelist/list-deps-flat.bats
- test/functional/bundlelist/list-deps-nested.bats
- test/functional/diagnose/diagnose-bundles.bats
- test/functional/diagnose/diagnose-path.bats
- test/functional/repair/repair-bundles.bats
- test/functional/repair/repair-path.bats
- test/functional/testlib.bash
- test/functional/verify-legacy/verify-bundle.bats
When creating test bundles, we are not including os-core in them by
default. This is how it works in production so we should do it so it
resembles the real production environment more accurately.
> Testlib: including os-core in test bundles

- src/bundle_list.c
- test/functional/bundlelist/list-experimental.bats
- test/functional/bundlelist/list-installed.bats
When listing bundles using "swupd bundle-list --status" we were
distinguishing bundles that were explicitly installed, by marking them
as such and since bundle-list shows only bundles tha are installed, bundles
that were not marked as explicitelly installed were assumed to be
just installed.
When we use "bundle-list --all --status" (which shows installed and
uninstalled bundles), we were marking files as "installed", "explicitly
installed" and bundles without any of these distinctions were assumed to
be not installed. This could cause confusion.
This PR changes the "bundle-list --status" so we always label bundles
as either "implicitly installed" or "installed" (even though it couls
sound a little redundant) so it is consistent with the way they are
labeled during "bundle-list --all …
> Show status for all bundles with --status

- configure.ac
- scripts/github_actions/build_ci.bash
- src/lib/macros.h
- src/target_root.c
There are several points in swupd that we find conditions that should never
happen, but we try to correct them anyway to be more reliable. Because of that
we may hide programming mistakes that are corrected later.
So, to make sure we are going to catch those problems in debug mode in our development
machines and test environment, I am suggesting a UNEXPECTED() macro that aborts swupd
if --enable-debug was used to build swupd.
I am adding some examples on what we could do with that.
What are your opinions about that?
> Suggestion WIP: Create UNEXPECTED() macro

- test/functional/testlib.bash
When a MoM contains an experimental bundle and the hashes in the MoM are
regenerated, the experimental bundles are being skipped. This commit
fixes that issue.
> Testlib: fix bug regenerating hashes in MoM

- src/bundle_list.c
- src/helpers.c
- test/functional/api/api-3rd-party-bundle-list.bats
- test/functional/api/api-bundle-list.bats
- test/functional/bundlelist/list-experimental.bats
- swupd bundle-list
- swupd 3rd-party bundle-list
> API: output for [3rd-party] bundle-list

- src/bundle.c
- src/bundle_info.c
- test/functional/api/api-3rd-party-bundle-info.bats
- test/functional/api/api-bundle-info.bats
- swupd bundle-info
- swupd 3rd-party bundle-info
> API: output for [3rd-party] bundle-info

- src/verify.c
- test/functional/repair/repair-json.bats
When dealing with extra files during a "verify" action, we cannot really
tell how far in the process we are, so we should be defining that step
as PROGRESS_UNDEFINED. Since we are using a PROGRESS_BAR, it is causing
to show an extra "[100%]" at the end of the diagnose process.
> Fixing progress type on diagnosing extra files

- src/3rd_party_repos.h
- test/functional/3rd-party/3rd-party-bundle-add-export-bin.bats
- test/functional/testlib.bash
XDG_CONFIG_DIRS variable was added with an incorrect name. XDG_CONF_DIRS was used instead.
Fixing that.
Fix #1443
> 3rd-party: xdg env variable has a wrong name

- src/3rd_party_clean.c
- src/clean.c
- test/functional/api/api-3rd-party-clean.bats
- test/functional/api/api-clean.bats
- swupd clean
- swupd 3rd-party clean
> API: output for [3rd-party] clean

- test/functional/api/api-hashdump.bats
> API: output for hashdump

- src/lib/macros.h
- src/lib/sys.c
- src/target_root.c
- test/functional/testlib.bash
- test/functional/update/update-unusual-file-names.bats
Currently we install directories and files using a tar command piped to another tar command.
There are multiple problems related to that, like:
- performance
- dependency on tar binary
- lack support on unusual characters on filenames
This pull request changes the way we install directories by creating them with mkdir and updating all attributes that we control on swupd, update directories by update all attributes and install files by using the cp binary, when link is not supported.
In some preliminary tests we got a nice improvement in installation speed, around 60~70% faster on big bundles, like desktop and os-clr-on-clr.
Related to #671 and  #640. Almost fixed and shouldn't be a problem anymore, but there are still changes required on install_dir_using_tar() and …
> Target root: Change the way we install directories and files

- src/3rd_party_add.c
- src/3rd_party_remove.c
- src/helpers.c
- src/signature.c
- test/functional/api/api-3rd-party-add.bats
- test/functional/api/api-3rd-party-list.bats
- test/functional/api/api-3rd-party-remove.bats
- test/functional/only_in_ci_system/api-3rd-party-add.bats
- swupd 3rd-party add
- swupd 3rd-party remove
- swupd 3rd-party list
> API: output for 3rd-party add, remove, list

- src/mirror.c
- test/functional/api/api-mirror.bats
> API: output for mirror

- src/heuristics.c
- src/update.c
- test/functional/update/update-boot-manager.bats
- test/functional/update/update-type-changes-file-to-recursive-symlink.bats
- test/functional/update/update-use-full-file.bats
- test/functional/update/update-verify-fix-path-hash-mismatch.bats
- test/functional/update/update-verify-fix-path-missing-dir.bats
This commit adds the following files to trigger the execution of
clr-boot-manager:
- /usr/bin/clr-boot-manager
- /usr/share/syslinux/ldlinux.c32
Closes #1415
> Updating list to run clr-boot-manager

- src/3rd_party.c
- src/telemetry.c
- src/telemetry.h
Telemetry is used to report problems to main repository, so it doesn't
make sense to create telemetry report files for 3rd-party repositories.
Closes #1358
> 3rd-party: do not report telemetry on 3rd-party

- src/3rd_party_bundle_list.c
- src/3rd_party_check_update.c
- src/3rd_party_clean.c
- src/3rd_party_diagnose.c
- src/3rd_party_info.c
- src/3rd_party_repair.c
- src/3rd_party_repos.c
- src/3rd_party_update.c
- src/progress.c
- test/functional/3rd-party/3rd-party-json-output-multirepo.bats
- test/functional/3rd-party/3rd-party-json-output.bats
Multi-repo operations can run in one or multiple repos, so that needs to
be taken in consideration when opening and closing progress steps.
Closes #1494 
> Bug_fix: In closing steps in multi-repo ops

- src/lib/sys.c
Sys_path_join is removing trailing '/', but we shouldn't remove the last
'/' if path is "/". Right now sys_path_join("/") == "" and should be "/".
> sys: sys_path_join() removes trailing '/' from "/"

- src/helpers.c
- src/swupd.h
When printing the header, print all '_' chars at once to prevent
json-output and --debug to print that in multiple lines.
> header: Print the header decoration all at once

- config
- docs/swupd.1.rst
- src/3rd_party_check_update.c
- src/3rd_party_update.c
- src/swupd.h
- src/update.c
- swupd.bash
- swupd.zsh
- test/functional/update/update-3rd-party.bats
This commit adds a flag that can be used to update content from
3rd-party repositories after updating the regular content if
successfull.
Closes #1473
> Adding a --3rd-party flag to update

- src/verify.c
- test/functional/api/api-diagnose.bats
- test/functional/api/api-repair.bats
- test/functional/diagnose/diagnose-path.bats
- test/functional/repair/repair-error.bats
- test/functional/testlib.bash
This PR fixes a couple of bugs found in the diagnose/repair functionality:
- Diagnose should not use partial matches for the `--file` option
- Swupd should still check for extra files even in no tracked files are found in the path specified by the user with the `--file` flag.
Closes #1472
> Bug_fix: Fixing bug in diagnose/repair using the `--file` option

- src/3rd_party_repos.c
- test/functional/3rd-party/3rd-party-bundle-list-basic.bats
- test/functional/3rd-party/3rd-party-bundle-list-deps.bats
- test/functional/3rd-party/3rd-party-check-update-basic.bats
- test/functional/3rd-party/3rd-party-diagnose-basic.bats
- test/functional/3rd-party/3rd-party-info.bats
- test/functional/3rd-party/3rd-party-json-output-multirepo.bats
- test/functional/3rd-party/3rd-party-repair-basic.bats
- test/functional/3rd-party/3rd-party-repair-exported-bin.bats
- test/functional/3rd-party/3rd-party-update-basic.bats
- test/functional/3rd-party/3rd-party-update-dangerous-flags.bats
- test/functional/3rd-party/3rd-party-update-export-template-multi-repo.bats
- test/functional/3rd-party/3rd-party-update-export-template.bats
- test/functional/3rd-party/3rd-party-update-exported-bin.bats
- test/functional/update/update-3rd-party.bats
Headers are printed at the beginning of the output for every repository
in operations that run in multipl repos. This header was using the word
"repo" but we are trying to use the whole "repository" word every time
we printed it to the user. This commit changes that.
> 3rd-party: using "repository" for headers

- swupd.zsh
- Added supports to 3rd-party repos.
- Added a new functionality to complete `version` number. For example
`swupd update --version=VERSION_NUMBER`
- Updated descriptions for arguments/options.
- Large amount of refactoring. Separation of data and logic.
Various completions for 3rd-party repo won't work with non-root users until we made `/var/lib/swupd/` readable.
See https://github.com/clearlinux/swupd-client/issues/1496
> swupd.zsh: Updated to support 3rd-party repo

- src/update.c
There is a configuration option to build swupd without the 3rd-party
functionality, this commit adds a guard to disable the code that adds
the "swupd update --3rd-party" flag which should be only available if
3rd-party is enabled.
> Disable "update --3rd-party" when applicable

- Makefile.am
- src/lib/sys.c
- test/unit/test_sys.c
When sys_path_join("//") was used, the result was "" instead of "/"
> sys: sys_path_join was wrong for string "//"

- test/functional/api/api-mirror.bats
- test/functional/api/api-repair.bats
- test/functional/repair/repair-error.bats
The tests in test/functional/api are going to validate the --quiet
output is rarely changed, therefore only expected output should be
validated and not warnings or error messages.
Closes #1502
> API: Do not validate error messages in API tests

- src/extra_files.c
- src/verify.c
- test/functional/api/api-3rd-party-repair.bats
- test/functional/api/api-repair.bats
- test/functional/repair/repair-error.bats
When using --quiet, there was no way of knowing if a file had been
successfully repaired or not. This commit fixes that.
Closes #1504
> Reporting if a file was fixed or not with --quiet

- src/helpers.c
Forgot to add the check after calloc
> helpers: Add check for allocation errors

- Makefile.am
- test/code_analysis/quiet_output.bats
We are aiming to provide a stable --quiet output, so forcing "make
compliant" to fail if there are changes in the test/functional/api
tests, which cover these scenarios will prevent us from unadvertedly
changing those tests.
Closes #1501
> Fail to be compliant if --quiet tests change

- src/curl.c
If for some reason swupd fails to create or append the file it will
cause a segmentation fault. This, commit prevents this from happening.
> curl: exit if the file cannot be created/appended

- test/functional/update/update-attr-change.bats
- test/functional/update/update-boot-manager.bats
- test/functional/update/update-type-changes-dir-to-file.bats
- test/functional/update/update-type-changes-file-to-symlink.bats
The show_target function shows a warning that is not applicable so this
commit ignores that warning wherever show_target is used.
> Test: show_target shellcheck warning

- src/verify.c
Print debug information for all file that is checked in repair/diagnose/os-install
> verify: Debug info for every checked file

- test/functional/bundlelist/list-all.bats
- test/functional/bundlelist/list-deps-flat.bats
- test/functional/bundlelist/list-deps-invalid-bundle.bats
- test/functional/bundlelist/list-deps-nested.bats
- test/functional/bundlelist/list-has-dep-nested-not-installed.bats
- test/functional/bundlelist/list-has-dep-nested-server.bats
- test/functional/bundlelist/list-has-dep-nested.bats
- test/functional/bundlelist/list-installed.bats
- test/functional/bundlelist/list-json.bats
- test/functional/bundlelist/list-no-deps.bats
- test/functional/bundlelist/list-none-has-deps.bats
- test/functional/bundlelist/list-quiet.bats
Use global_setup in all bundle-list tests so we can only generate the
test environment once and use it for multiple tests. The one exception
is if we need to modify the env for a specific test.
> Test: Use global_setup for bundle-list tests

- swupd.bash
- test/functional/usability/usa-completion-basic.bats
- All options and subcommands are automatically generated from help messages.
- Used `_init_completion` to set $cur, $prev, $words variables, which are
equivalent to $2, $3, $COMP_WORD, but far more readable.
- It also allows possibility to use other functions provided in
`/usr/share/bash-completion/bash_completion`, for future
- A minor change on getting current OS version via `swupd info --quiet` from
reading `/var/lib/swupd/version`, which is non-readable to non-root users
- Though MoM file is still non-readable to non-root users
- We only ship modern Bash, so the test on Bash version near the end of the
script is removed
This also closes #1520
> swupd.bash: Multiple improvements

- config
- docs/swupd.1.rst
- src/3rd_party_bundle_list.c
- src/alias.c
- src/bundle.c
- src/bundle.h
- src/bundle_list.c
- src/lib/sys.c
- src/lib/sys.h
- src/swupd.h
- src/swupd_comp_functions.c
- src/swupd_comp_functions.h
- swupd.bash
- swupd.zsh
- test/functional/3rd-party/3rd-party-bundle-list-orphans.bats
- test/functional/api/api-3rd-party-bundle-list.bats
- test/functional/api/api-bundle-list.bats
- test/functional/bundlelist/list-flags.bats
- test/functional/bundlelist/list-orphans.bats
This commit adds the `--orphans` flag to `bundle-list` and `3rd-party bundle-list`. This flag will list the bundles that are no longer required by any tracked bundles.
Closes #1530
> Add `--orphans` flag for bundle-list

- scripts/build_and_run_tests.bash
- src/lib/sys.h
- src/swupd_build_variant.h
- src/target_root.c
- test/code_analysis/warning_functions.bats
Porting code to better way on interacting with system commands using the
run_command function. As run_command don't support multi-thread for
performance reasons, we are now using a file instead of a pipe. As tar|tar
is now a fallback, this won't have any performance impacts on any case
where with no problems and errors.
Fixes #640 and #671
> target_root: Use run_commmand to execute tar|tar command

- src/lib/sys.h
To be parsed doc commend should start with **
> sys: Fixing documentation of ls_sys

- src/globals.c
CONFIG_FILE_PATH contains a list of paths not just one path. So
we shouldn't use realpath to point to it.
> config: CONFIG_FILE_PATH shouldn't be treated as a path

- src/helpers.c
- src/verifytime_main.c
If the file doesn't exist in system, we can't proceed.
> verifytime: Missed a return on ENOENT error

- src/3rd_party_repos.c
- src/alias.c
- src/binary_loader.c
- src/clean.c
- src/curl_async.c
- src/globals.c
- src/hash.c
- src/helpers.c
- src/lib/hashmap.c
- src/lib/list.c
- src/lib/macros.h
- src/lib/strings.c
- src/lib/sys.c
- src/lib/thread_pool.c
- src/lib/timelist.c
- src/manifest.c
- src/manifest_parser.c
- src/packs.c
- src/search_file.c
- src/subscriptions.c
- src/swupd.h
- src/verifytime.c
- src/version.c
- src/xattrs.c
- test/code_analysis/warning_functions.bats
Use always calloc to allocate memory and abort on errors
> macros: Create wrapper for malloc and calloc functions

- src/manifest.c
- src/swupd.h
Some manifest functions used by mixin were left behind
> mixin: Remove some mixin leftovers

- Makefile.am
- src/bundle_info.c
- src/bundle_remove.c
- src/curl.c
- src/curl_async.c
- src/progress.c
- src/signature.c
- src/subscriptions.c
- src/update.c
Make sure we are not accidently using the incorrect variable
by not allowing 2 variables with the same name.
> Makefile: Adding -Wshadow to prevent accident shadowing

- config
- docs/swupd.1.rst
- src/3rd_party/3rd_party_bundle_remove.c
- src/cmds/bundle_list.c
- src/cmds/bundle_remove.c
- src/swupd.h
- src/swupd_lib/bundle.c
- src/swupd_lib/bundle.h
- swupd.zsh
- test/functional/3rd-party/3rd-party-bundle-remove-orphans.bats
- test/functional/api/api-3rd-party-bundle-remove.bats
- test/functional/api/api-bundle-remove.bats
- test/functional/bundleremove/remove-flags.bats
- test/functional/bundleremove/remove-orphans.bats
Dependencies of orphaned bundles can cause bloat and unexpected content to be on disk.
We need to remove all bundles that are not tracked or dependency of a tracked bundle.
This option should also be available for 3rd-party.
Closes #1529
> Add command to remove orphan bundles

- Makefile.am
- src/3rd_party/3rd_party_bundle_add.c
- src/3rd_party/3rd_party_repos.c
- src/3rd_party/3rd_party_update.c
- src/cmds/bundle_remove.c
- src/cmds/clean.c
- src/cmds/os_install.c
- src/cmds/verify.c
- src/swupd.h
- src/swupd_lib/bundle.c
- src/swupd_lib/bundle.h
- src/swupd_lib/delta.c
- src/swupd_lib/fullfile.c
- src/swupd_lib/helpers.c
- src/swupd_lib/statedir.c
- src/swupd_lib/statedir.h
- src/swupd_lib/target_root.c
Create a statedir module with functions related operations exclusive to statedir, like cleaning staged dir, other cleaning operations and functions to build specific directories.
This is the first of a series of PRs aimed to complete that goal.
Relates #1538
> Creating new module statedir, to group all functions related to handling of statedir (part 1)

- src/cmds/clean.c
- src/cmds/update.c
- src/swupd_lib/delta.c
- src/swupd_lib/fullfile.c
- src/swupd_lib/hash.c
- src/swupd_lib/helpers.c
- src/swupd_lib/manifest.c
- src/swupd_lib/statedir.c
- src/swupd_lib/statedir.h
- src/swupd_lib/target_root.c
This commit continues where #1552 left off by providing more functions to handle files in directories from the statedir.
This PR includes functions to handle these directories:
- delta
- download
This PR is built on top of #1552 so that one needs to be reviewed first.
Related to #1538
> Grouping functions related to handling of statedir (part 2)

- configure.ac
- src/cmds/check_update.c
- src/cmds/update.c
- src/swupd.h
- src/swupd_lib/helpers.c
check-update was trying to create a motd in a deprecated directory and
it was always failing.
Removing code for now.
> motd: Remove motd code that was not being used

- src/3rd_party/3rd_party_repos.c
- src/cmds/bundle_add.c
- src/cmds/update.c
- src/cmds/verify.c
- src/lib/sys.c
- src/lib/sys.h
- src/swupd.h
- src/swupd_lib/globals.c
- src/swupd_lib/globals.h
- src/swupd_lib/helpers.c
- src/swupd_lib/lock.c
- src/swupd_lib/manifest.c
- src/swupd_lib/packs.c
- src/swupd_lib/statedir.c
- src/swupd_lib/statedir.h
- src/swupd_lib/telemetry.c
- src/swupd_lib/version.c
This PR adds functions to get manifest files from the statedir.
This PR is built on top of #1552 and #1557 so they need to be reviewed first.
Closes #1538
> Grouping functions related to handling of statedir (part 3)

- src/lib/thread_pool.c
Actually thread_pool supports zero threads, that means exactly running in
serial. So rolling back to what it was before the integer conversion fix of
commit 2a7f181e0093f947008f777c11f663a195e256f2.
> thread_pool: Number of threads can be zero

- src/swupd_lib/delta.c
Fixing:
- Memory leak delta.c
- Dead code in thread_pool.c
> Fixing memory leak in delta.c

- src/cmds/verify.c
- test/functional/os-install/install-var.bats
Don't run heuristics for os-install or repair --quick.
On os-install we want all files to be always installed. On repair --quick
we don't process any do_not_update files
> verify: Don't apply heuristic to os-install

- src/cmds/clean.c
- src/swupd_lib/globals.c
- src/swupd_lib/manifest.c
- src/swupd_lib/packs.c
- src/swupd_lib/statedir.c
- src/swupd_lib/statedir.h
- src/swupd_lib/target_root.c
Some of these references to statedir where left in the code, this commit
moves them to the statedir.c module so references to content of the
statedir are not hardcoded. Files in the statedir can move to different
locations freely this way.
> Moving some remaining functions to statedir.c

- src/cmds/clean.c
- src/swupd_lib/manifest.c
- src/swupd_lib/statedir.c
- src/swupd_lib/statedir.h
- test/functional/api/api-3rd-party-clean.bats
- test/functional/api/api-clean.bats
- test/functional/bundleadd/add-no-disk-space.bats
- test/functional/bundlelist/list-experimental.bats
- test/functional/bundlelist/list-no-disk-space.bats
- test/functional/bundleremove/remove-no-disk-space.bats
- test/functional/os-install/install-download.bats
- test/functional/os-install/install-statedir-cache-offline.bats
- test/functional/os-install/install-statedir-cache.bats
- test/functional/repair/repair-no-disk-space.bats
- test/functional/search/search-no-disk-space.bats
- test/functional/testlib.bash
- test/functional/update/update-no-disk-space.bats
- test/functional/update/update-search-file-index.bats
This PR groups all the manifest-related artifacts that swupd downloads under the same "manifest" directory, so we keep a better consistency within the statedir.
This PR is built on top of #1567 and it needs to be merged first.
Related to #1539
> Group manifest artifacts under the same directory in the statedir

- src/swupd_lib/delta.c
- test/functional/update/update-verify-fix-path-hash-mismatch.bats
- test/functional/update/update-verify-fix-path-missing-dir.bats
Print a more useful error when we fail to locate a file to apply a
delta. Add a suggestion for the user to run `swupd repair` and make
it clear that the problem is in their system and not in the update
content.
Fixes #1425
> delta: Improve message on delta errors

- src/cmds/clean.c
Manifest directory has moved and we need to clean manifests in previous location.
> clean: Clean manifests in deprecated location

- swupd.bash
- test/functional/usability/usa-completion-basic.bats
Clear requires that bash autocomplete scripts to be executable by sh
shell
> swupd.bash: Make swupd.bash sh compliant

- configure.ac
The `configure` script generated from configure.ac tries to run a `]`
command, but that command doesn't exist.
The root cause is a syntax issue configure.ac: there is a stray `]` on
one of the lines.
> Fix syntax error in configure.ac

- test/functional/clean/clean-grouped-manifests.bats
When checking the output of the "clean --dry-run" command in the test,
we expect the output to be shown in a specific order, but the order can
change depending on the system since readdir doesn't warranty a specific
order when reading the content of a directory.
This commit fixes the test by only checking for the files we are
intereseted in, and it checks them with separate assertions to make sure
we don't have false positives due to the order.
> Fixing a false positive in a "clean" test

- src/lib/archives.c
- src/swupd_lib/statedir.c
- test/functional/testlib.bash
- test/functional/usability/usa-cachedir-with-symlink.bats
When the path provided by a user for the --statedir (or --cachedir)
contains a symlink swupd will fail to extrar tar files since
libarchive does not support extracting files through symlinks.
This commit fixes the issue allowing users to use symlinks in the
--statediri/--cachedir path.
Closes #1581
> Allow paths that contain symlinks for cachedir

- src/swupd_lib/globals.c
- test/functional/mirror/mirror-set-unset.bats
- test/functional/os-install/install-statedir-cache-offline.bats
When using -v, -c, or -u to set alternate version or content URLs, print out a message so it's a little bit more obvious when you accidentally use the wrong option.
> Announce overrides of content and version URLs

- src/swupd_lib/packs.c
- test/functional/bundleadd/add-json.bats
- test/functional/only_in_ci_slow/update-slow-server.bats
- test/functional/only_in_ci_system/add-no-disk-space.bats
- test/functional/os-install/install-json.bats
- test/functional/os-install/install-no-fullfile-fallback.bats
- test/functional/os-install/install-no-packs.bats
- test/functional/os-install/install-statedir-cache-offline.bats
- test/functional/update/update-json.bats
There are some problems with how we are using multiplexed curl causing huge slowdowns (2-5 times slower).
For now rather than rework the multiplexed curl code, switch to using the synchronous code path.
Signed-off-by: William Douglas <william.douglas@intel.com>
> Move packs to download synchronously

- src/swupd_build_variant.h
- src/swupd_lib/curl.c
- src/swupd_lib/curl_async.c
- src/swupd_lib/filedesc.c
In cases where curl perform returns an error but is actually a 400 level response, swupd needs to check curl info to see this. If the info reveals a 400 level response, return the corresponding download status error to prevent useless download retries.
> Rework how curl errors are checked

- Makefile.am
- configure.ac
Fix build failure:
```
rst2man.py "docs/swupd.1.rst" > "docs/swupd.1.tmp" && mv -f "docs/swupd.1.tmp" "docs/swupd.1"
rst2man.py "docs/swupd-alias.7.rst" > "docs/swupd-alias.7.tmp" && mv -f "docs/swupd-alias.7.tmp" "docs/swupd-alias.7"
rst2man.py "docs/swupd-update.service.4.rst" > "docs/swupd-update.service.4.tmp" && mv -f "docs/swupd-update.service.4.tmp" "docs/swupd-update.service.4"
rst2man.py "docs/update-triggers.target.4.rst" > "docs/update-triggers.target.4.tmp" && mv -f "docs/update-triggers.target.4.tmp" "docs/update-triggers.target.4"
/bin/sh: line 1: rst2man.py: command not found
rst2man.py "docs/swupd-update.timer.4.rst" > "docs/swupd-update.timer.4.tmp" && mv -f "docs/swupd-update.timer.4.tmp" "docs/swupd-update.timer.4"
/bin/sh: line 1: rst2man.py: command not found
/bin/sh: …
```
> rst2man.py -> rst2man

- src/cmds/autoupdate.c
- test/functional/api/api-autoupdate.bats
- test/functional/testlib.bash
systemctl reports that the timer file is missing now as a return code 4 so update the unknown start number.
Also with this change SWUPD_NO is no longer always returned so add a new helper to check if a status is one of multiple options.
> Test fixups and update for newer systemd

- src/swupd_lib/curl.c
Set response explicitly in case of curl_easy_getinfo error (though in practice the response isn't modified and so program behavior is the same as before this change).
> Add error handling for curl_easy_getinfo

- src/swupd_lib/globals.c
- test/functional/mirror/mirror-set-unset.bats
- test/functional/os-install/install-statedir-cache-offline.bats
- test/functional/usability/usa-config-file.bats
- test/real_content/real_content_lib.bash
Previously, these messages were printed to STDOUT:
Overriding version and content URLs with...
Overriding content URL with...
Overriding version URL with...
But especially with --quiet, the output to STDOUT should be strictly the requested data. So print these as warnings instead.
Fix tests to match this change. Also eliminate some uses of wc -l that don't help. Take advantage of lines array to count bundles.
> Redirect URL override messages to STDERR

- test/real_content/real_content_lib.bash
We already detect and report that certain tests require at least two builds within the current format, but only one exists. Change that from a test *failure* to a *skip*.
Example:
```
We need at least 2 versions in format 38 to continue with this test
Test teardown complete.
not ok 2 RCT002: Repair a big system
#
```
becomes:
```
ok 2 RCT002: Repair a big system # skip We need at least 2 versions in format 38 to continue with this test
```
> Skip tests that require two builds in a format when there's only one

- test/functional/only_in_ci_system/api-3rd-party-add.bats
`sudo` was mistakenly omitted from the prior commit 695417dca0b39d76464fe510b8f0ff57ca21f228, nullifying the effect of the purported fix.
> Add sudo to commands to backup/restore Swupd_Root.pem

- test/functional/only_in_ci_system/add-client-certificate.bats
- test/functional/only_in_ci_system/chk-update-client-certificate.bats
- test/functional/only_in_ci_system/diagnose-client-certificate.bats
- test/functional/only_in_ci_system/list-client-certificate.bats
- test/functional/only_in_ci_system/remove-client-certificate.bats
- test/functional/only_in_ci_system/search-client-certificate.bats
- test/functional/only_in_ci_system/update-client-certificate.bats
- test/functional/server.py
The previous method for wrapping ssl was removed so update to the replacement version.
> Update server.py ssl wrapping

- src/swupd_lib/signature.c
- test/functional/signature/alt-key-rotation.bats
Enable an alternative swupd certificate location (the location of the default or given cert with an ".alt" appended to it). The purpose of this change is to allow more reliable and flexible key rotations.
If either the main cert or alt cert fails when doing content verification then the other will be tried (and be used for the next operation). In this way, as long as both certs don't fail for the same content verification, progress can be made with either cert.
> Add support for an alternative swupd certificate

- scripts/github_actions/build_ci_dependencies.bash
- test/functional/only_in_ci_system/add-no-disk-space.ignore-list
Includes needed dev packages and an ignore for error messages seen on Ubuntu's version of curl but not in Clear Linux.
> Add CI fixes for github's updated Ubuntu container

- .github/workflows/shellcheck-all.yml
- scripts/shellcheck.bash
- test/real_content/real_content_lib.bash
The mechanism used to convert bats tests to something shellcheck can verify caused a large number of failures due to the introduction of testing for if a call is possible. Given the tests aren't called in a normal shell script way, it is best to just ignore this error for bats files.
Also fix an index using '$' unnecessarily.
> Fix up shellcheck issues
