include/swupd.h
src/clr_bundle_add.c
src/manifest.c
src/signature.c
src/verify.c

Implementation of signature and certificate validation.

Signature verification

---

include/swupd-error.h
src/bundle.c
src/clr_bundle_add.c
src/globals.c
src/search.c
src/signature.c
src/staging.c
src/update.c
src/verify.c

Signed-off-by: Ikey Doherty <michael.i.doherty@intel.com>

Fix formatting issues introduced by pull request #46

---

scripts/swupd-completion.sh

Signed-off-by: Jose R Guzman <jose.r.guzman.mosqueda@intel.com>

Fix for completion when absolute path is given

---

src/helpers.c

Man 3 readdir_r states: "This function is deprecated; use readdir(3)
instead."
Further, it also reads:
```
*  In the current POSIX.1 specification (POSIX.1-2008), readdir(3) is
not required to be thread-safe.  However, in modern
implementations (including the glibc implementation), concurrent
calls to readdir(3) that specify different directory streams are
thread-safe.  Therefore, the use of readdir_r() is generally
unnecessary in multithreaded programs.  In cases where multiple
threads must read from the same directory stream, using readdir(3)
with external synchronization is still preferable to the use of
readdir_r(), for the reasons given in the points above.
```
I don't expect swupd-client to be used with anything other than
glibc at this moment, and I don't see that the current code …

Stop using readdir_r, switch to recommended readdir() instead.

---

src/curl.c

Remove certificate pinning

---

.travis.yml
configure.ac
src/curl.c
test/functional/ignore-list

This series fully enables travis-ci for running the functional test suite.

Enable travis-ci

---

include/swupd.h
src/bundle.c
src/main.c
src/telemetry.c
src/update.c
src/verify.c

- Change telemetry API - add class component. 
- Telemetry: add telemetry for bundle add, remove.

Telemetry: new API, add bundle add/remove telemetry.

---

src/telemetry.c

As it turns out, systemd is so efficient spotting new telemetry
records and spawning swupd-probe to retrieve them, that on several
occasions it does so before the entire record is written out by
printf(). This results in the server receiving an empty record from
the swupd telemetry process - it is reading the record data before
writing succeeded.
To guard against this, we atomically move (rename(2)) the record
after it was fully generated. This assures that the full record data
is present before swupd-probe can see it.
To do this safely, we mkstemp() the record outside the telemetry
spool in /var/lib/swupd, and then move it after it is complete
into /var/lib/swupd/telemetry. This requires, unfortunately, that
we use basename(3), and another string for the final file name,
since rename(2) …

Telemetry: Atomically create telemetry record.

---

src/clr_bundle_ls.c

Sort bundle-list output alphabetically.

Sort bundle-list output.

---

src/verify.c

Fixes #276
Refactor fixing a single file into its own routine, then call it in a
loop with print_progress.

Add progress updates for Verifying files

---

src/curl.c

Remove the increment left-over from changing from while to for.

Fix incorrect cycle.

---

src/manifest.c

Hopefully will drop yet another cubic operation to quadratic

More a constant time check before a O(n) check

---

Makefile.am

Fix build break for "make dist"

---

docs/swupd.1
docs/swupd.1.rst
include/swupd.h
src/extra_files.c
src/verify.c

This is needed for A/B partitioning. If you can, please review soon, because then I don't need to add unmerged patches to meta-swupd.

Extra picky

---

Makefile.am

Link libarchive into libswupd

---

src/globals.c
src/signature.c

Fix some memory leaks

---

src/swupd.c

Signed-off-by: Caio Marcelo de Oliveira Filho <caio.oliveira@intel.com>

Use same style for all the command descriptions

---

Makefile.am
docs/swupd.1
docs/swupd.1.rst
include/swupd-internal.h
src/info.c
src/swupd.c

Fixes #218.
Signed-off-by: Caio Marcelo de Oliveira Filho <caio.oliveira@intel.com>

Add info command to show OS version and URLs

---

src/scripts.c

Add a check to see if an update is being run in a container (and is
updating the rootfs) using systemd-detect-virt -c. If the update is
being run in a container skip running the clr-boot-manager update
since it will fail.

Make a container check before running clr-boot-manager

---

include/swupd.h
src/search.c
test/functional/search/content-check-posbin/test.bats
test/functional/search/content-check-posebin/test.bats
test/functional/search/content-check-posfull-path/test.bats
test/functional/search/content-check-poslib32/test.bats
test/functional/search/content-check-poslib64/test.bats

@fenrus75 wrote this patch. Opening for review.

Improve swupd search output

---

swupd-add-pkg

Update to new Mixer 4.0.*

---

src/bundle.c

Add mixer-integration awareness to bundle-list

---

src/search.c

Instead of silently truncating search results to 5 files per 5 bundles
make the default search output a full list grouped by bundle. This
output will only be sorted by increasing bundle size.
Add a -t, --top=NUM argument to tell search to truncate results at NUM
files and NUM bundles. This option attempts to display the top results
based on a set of heuristics.
When truncating results due to --top add a message when the file or
bundle results are cut off.
Add the -m, --csv flag to output all search results in CSV format:
/file/result,bundle-name
This PR is based on #399. Ignore the first commit for this patchset. Only merge this after #399 has been merged.

search: display all results by default

---

swupd-add-pkg

Fix swupd-add-pkg

---

Makefile.am
docs/swupd.1
docs/swupd.1.rst
src/globals.c
src/info.c
src/main.c
src/mirror.c
src/swupd-internal.h
src/swupd.h

Provide a mechanism and CLI subcommand to allow users to set a configurable mirror URL on their system. See individual commit messages for more details.

Provide a configurable mirror URL setting

---

src/helpers.c
src/main.c
src/swupd.h

Move copyright_header to main.c

---

src/packs.c

Report when a pack is missing using telemetry

---

src/clean.c

Instead of keeping recent content around, just delete all the files,
with exception of the latest relevant Manifests.

clean: do not keep content around

---

src/fullfile.c

String that is reused later shoudn't be freed.
Fix double free reported on issue #480

fullfile: Fix double free

---

src/clr_bundle_ls.c

As /usr/share/clear/bundles has read permissions for everyone, we can
let regular users to run "swupd bundle-list". If a path_prefix is
informed and the user don't have access to it, it will fail printing
an error message.

bundle-list: Let any user to run swupd bundle-list

---

src/swupd.h
src/version.c

Remove dev build version check

---

docs/README.rst

Notes on debugging Travis.

---

src/version.c

This check already occurred a couple lines up.

version: remove duplicated current_version check

---

test/functional/README.md
test/functional/testlib.bash

Some tests need to have not only one but two or more versions of
the server side content (web-dir).
This commit adds a function that can be used to create these new
versions.

Add function to create new test versions

---

src/bundle.c
src/download.c
src/fullfile.c
src/packs.c
src/swupd.h
src/update.c
src/verify.c
test/functional/bundleadd_v2/add-rc.bats
test/functional/update/slow-server/lines-checked
test/functional/update/slow-server/server.py
test/functional/update/slow-server/test.bats

Using parallel download API do download packs in parallel.
Closes #298

Pack downloads

---

src/bundle.c
src/clean.c
src/clr_bundle_ls.c
src/curl.c
src/helpers.c
src/lock.c
src/search.c
src/swupd.h
src/update.c
src/verify.c
src/version.c

- some clean up in swupd_init and swupd_deinit
- Don't use curl on swupd-clean command (fixes #551)

Improvements in swupd_init

---

test/functional/testlib.bash

This commit adds the iterative manifests (to-manifest and from-manifest)
when creating a bundle update. This manifests should contain only those
files that changed in the latest version.
Closes issue #557

Add iterative manifest to bundle update in testlib

---

src/download.c

When downloading from file:// curl can process all reads and writes on the
first call of curl_multi_process() and then curl_multi_wait() will set numfds
to 0 and poll_fewer_than() will return without processing the download (i.e
extracting it).
Also change a bit the poll_fewer_than() to follow the timeout approach from the
official curl_multi_wait() example (https://curl.haxx.se/libcurl/c/multi-single.html).
Fixes #582

download: Process all completed downloads in poll_fewer_than()

---

src/manifest.c

manifest: Memory leak when signature verification fails

---

src/clean.c

Fixes #484
The manifest files with their hashes appended to the filename in the
cache are used internally to prevent swupd from re-calculating manifest
hashes every time they are opened. These should only persist for the
duration of the update and should not persist afterwards to prevent
root-priveleged owners from modifying internally-used data. This patch
causes swupd to remove them by default without having to pass --all. The
files will be automatically removed upon update.

clean: remove manifest hash hints from cache

---

test/functional/testlib.bash

This commit adds a menu of the functions that are available for
users when writing tests or just using the library to create
resources to test their code.

Adding a menu of functions for testlib

---

.travis.yml
Makefile.am
test/installation/test.bats

Check if all files expected to be installed in a full installation are
really installed

test: Test if make install is installing all necessary files

---

test/functional/bundleadd/add-client-certificate.bats
test/functional/bundlelist/list-client-certificate.bats
test/functional/bundleremove/remove-client-certificate.bats
test/functional/checkupdate/chk-update-client-certificate.bats
test/functional/search/search-client-certificate.bats
test/functional/update/update-client-certificate.bats
test/functional/verify/verify-client-certificate.bats

sed s/fallback-ca-paths/with-fallback-capaths/g

test: Fix flag name on certificate tests

---

src/archives.c

Libarchive's archive_error_string() method returns a textual
error message suitable for display.
However, this method returns only "Write Failed" if libarchive
runs out of hard disk space.
Check specifically for ENOSPC and print a correct
warning message to the user.

archives: Add output for out of space errors

---

src/bundle.c

This PR fixes a bug in bundle-add --time that was causing the command to show wrong values (and duplicated)
Closes #675

Fix a bug in bundle-add --time

---

Makefile.am
test/functional/checkupdate/chk-update-client-certificate.bats
test/functional/checkupdate/chk-update-new-version.bats
test/functional/checkupdate/chk-update-no-server-content.bats
test/functional/checkupdate/chk-update-no-target-content.bats
test/functional/checkupdate/chk-update-slow-server.bats
test/functional/checkupdate/chk-update-version-match.bats

Adding ID to check-update tests and changing their description to
make it more readable.

Adding ID to check-update tests

---

Makefile.am
test/functional/bundleadd/add-install-time.bats

Adding missing tests for the -t option in the bundle-add command.

Adding missing tests for the -t option in the bundle-add command.

---

test/functional/mirror/mirror-createdir-negative.bats
test/functional/mirror/mirror-createdir.bats

Adding IDs to mirror tests and some small changes.

Adding IDs to mirror tests

---

test/functional/completion/completion-basic.bats

Adding IDs to usability tests

---

test/functional/hashdump/hashdump-file-hash.bats

Adding IDs and minor changes in hashdump tests.

Adding IDs to hashdump tests

---

test/functional/search/search-client-certificate.bats
test/functional/search/search-content-check-negative.bats
test/functional/search/search-content-check-positive.bats

Adding ID to search tests and changing the description of some of
them to make them clearer.

Adding ID to search tests

---

test/installation/test.bats

test: Add an ID to installation tests

---

test/real_content/real_content_lib.bash
test/real_content/swupd_update.bats
test/real_content/swupd_update_fullfiles.bats
test/real_content/swupd_update_jump.bats
test/real_content/swupd_verify_install.bats

I've been running those tests for currently release and they are quite stable right now. Sending for review

Real content

---

README
README.md
docs/how_to_contribute.md

Add a simple development guide for swupd. We can maintain that as long as we
add new development rules to swupd project.

Add swupd development guide

---

src/download.c
src/search.c

This commit fixes a couple of style issues found in the code.

Fixing code style issues

---

.gitignore
Makefile.am
src/helpers.c
src/lib/strings.c
src/lib/strings.h
src/swupd.h
test/unit/test_helper.h
test/unit/test_strings.c

Introducing Unit tests in swupd.

Unit tests

---

src/lib/sys.c
src/lib/sys.h
src/manifest.c
test/functional/testlib.bash
test/functional/update/update-manifest-delta.bats

update: Use manifest-deltas in swupd on update

---

src/update.c

update: Print total bytes downloaded in MB

---

src/curl.c

curl: Getting even better on message if swupd fails to connect to server

---

src/scripts.c

When swupd needs to run a post update script it does so without checking
if the file exists in the system or not. This will cause an error to be
raised by the shell if the script does not exist.
This commit adds a check for the existance of the script before
attempting to run it.
Closes #824

Checking if update scripts exist before running

---

src/globals.c
src/swupd.h
src/update.c

Left overs from global refactor

update: move variable to correct file

---

Makefile.am

Adding missing test for deltas to Makefile.am

---

src/verify.c

verify: break line in error message to make it more readable

---

src/info.c

info: Using functions from log.h instead of fprintf

---

src/globals.c
src/hashdump.c

global: Make --quiet and --debug official

---

swupd.bash
test/functional/usability/usa-completion-basic.bats

Autocompletion for --debug and --quiet

---

src/main.c

Update the copyright to 2019

---

src/lib/formatter_json.c

Print the json output to stdout instead of stderr

---

src/curl.c

To calculate the total download size of packs and fullfiles, swupd is
relying in a function that uses curl to request the server for the
download size of each file. However, when a file is not found in the
server, a size of 162 is returned by curl, which was causing the total
download size calculation to be wrong.
This commit fixes the issue by counting the file size returned by curl
only if the file exists.

Fixes a bug when calculating the download size

---

src/info.c
src/swupd.h

Return correct code when current version unknown

---

src/clean.c

Make "clean" help consistent with other commands

---

src/globals.c
src/swupd.h

Removing short option from --allow-insecure-http

---

docs/swupd_signature_verification.md

docs: Add document explaining how we do signature verification on swupd

---

Makefile.am
test/code_analysis/shellcheck-all.bats
test/code_analysis/shellcheck.bats

test: Shellcheck tests should return an error on fails

---

swupd.zsh

zsh-completion updated in accordance to
https://github.com/clearlinux/swupd-client/commit/10bc311e4cc8a44b1a13ce99c5586ec4e453a0b5

Updated swupd.zsh to reflect changes

---

src/globals.c

global: Don't check for result of void functions

---

swupd.zsh

- Added `--no-progress` and `--skip-optional` flags
- Improved on syntax, removed unecessary option exclusion rules
- Changed the ordering and wording for global options for easier maintenance, see 
commit aa361c7

swupd.zsh: Multiple Changes

---

src/search.c

Change to clarify the use of -l/-B in search-file

---

src/autoupdate.c

When determining if autoupdate is enabled, swupd should not only check
the status of swupd-update.service but has to check swupd-update.timer
as well.
Closes #968 

Test swupd-update.timer also for autoupdate status

---

src/lib/sys.c

sys: Add NULL on run_command() call

---

src/verify.c

Removing unused assignment to variable

---

src/verify.c
test/functional/repair/repair-picky-downgrade.bats

Fixing message when using repair and --picky

---

src/update.c

On updates swupd binary can be replaced so readlink will fail to get the
swudp binary path. In this case we should run that before running any update
process.
And besides that hardcode /usr/bin/swupd as the default swupd path in the case
there's something wrong with readlink
Fixes #1067
Fixes #1068

update: Save swupd binary path before executing any update process

---

src/curl.c
src/hash.c
src/telemetry.c

Fix minor code issues

---

src/globals.c

Adding missing void to functions

---

config

Values in config file should use underscores

---

src/signature.c
src/signature.h

signature: Create a helper to verify the signature on files in memory

---

Makefile.am
src/check_update.c
src/helpers.c
src/mirror.c
src/version.c
test/functional/signature/key-rotation.bats
test/functional/signature/version-sig-check.bats
test/functional/testlib.bash

Update: Perform sig check on latest files

---

src/verify.c

verify: Fix printf arguments types and quantity

---

src/lib/progress.c
test/functional/diagnose/diagnose-json.bats
test/functional/os-install/install-json.bats
test/functional/repair/repair-json.bats

Fixing missing json messages while file redirect

---

src/version.c
test/functional/signature/version-sig-check.bats

version: Make signature check optional before next FB

---

docs/RELEASE_NOTES_DRAFT

Introducing a release notes draft to help writing release notes on next releases

Release Notes Draft

---

src/binary_loader.c
src/bundle.c
src/clean.c
src/delta.c
src/extra_files.c
src/globals.c
src/hash.c
src/helpers.c
src/lib/sys.c
src/lib/sys.h
src/manifest.c
src/mirror.c
src/scripts.c
src/staging.c
src/swupd.h
src/update.c

Trying to prevent here to run stat + file operation. Prefer to run the file operation and on errors evaluate the result.

Fixes on general usages of stat

---

src/bundle_info.c

Removing unused struct from bundle-info

---

src/bundle_info.c
src/helpers.c
src/search_file.c
src/verify.c

Fixing some code errors

---

src/lib/sys.c

Earlier the output of each helper script
run through execve was redirected directly
to the standard-output or standard error.
Hence messages printed like raw strings even if
json-format was selected
This fix ensures that we redirect the output of those
scripts to swupd so that we get a chance to process them
or format them before printing
Fixes #1127

Fix: To Jsonify helper script output

---

.travis.yml
src/curl_async.c
src/extra_files.c
src/manifest.h
src/swupd_exit_codes.h
test/code_analysis/compliant.bats

Fix new reported compliant issues

---

.travis.yml
Makefile.am
src/autoupdate.c
src/lib/sys.h
swupd.bash
swupd.zsh
test/functional/README.md
test/functional/autoupdate/aup-basic.bats
test/functional/check_ids.bash
test/functional/testlib.bash

Add --path to autoupdate mechanism

---

src/3rd_party.c
src/main.c

This commit makes a few small improvements to the help menu of swupd
3rd-party.

3rd-party help menu improvements

---

test/functional/README.md

Signed-off-by: Karthik Prabhu Vinod karthik.prabhu.vinod@intel.com

Removing Extra entry for autoupdate from readme

---

.github/workflows/ccpp.yml

actions: Remove trailing whitespace in ccpp yml

---

.github/workflows/ccpp.yml
scripts/build_ci.bash
test/functional/autoupdate/aup-basic.bats
test/functional/testlib.bash

actions: Build dependencies to support swupd builds

---

src/bundle_add.c
src/bundle_info.c
src/bundle_list.c
src/bundle_remove.c
src/curl.c
src/helpers.c
src/manifest.c
src/progress.c
src/scripts.c
src/swupd.h
src/verify.c
src/version.c

Some static functions were not set as static. Setting them.

static: Make some functions static

---

src/fullfile.c

When swupd is downloading fullfiles, if it runs out of free disk space
it is exiting without freeing the curl handle. This commit fixes the
issue by  freeing it when this condition occurrs.

Fix memory leak downloading files to a full disk

---

test/functional/testlib.bash

This commit enables the use of 3rd-party repos in some of the testlib
functions.

Enabling the use of 3rd-party repos in the testlib

---

src/bundle_add.c

Fix error calculating number of files staged

---

Makefile.am
config
src/3rd_party.c
src/3rd_party_bundle_list.c
src/bundle.c
src/bundle_list.c
src/swupd.h
src/swupd_internal.h
swupd.bash
swupd.zsh
test/functional/3rd-party/3rd-party-bundle-list-basic.bats
test/functional/3rd-party/3rd-party-bundle-list-deps.bats
test/functional/bundlelist/list-all.bats
test/functional/bundlelist/list-deps-flat.bats
test/functional/bundlelist/list-deps-nested.bats
test/functional/bundlelist/list-experimental.bats
test/functional/bundlelist/list-has-dep-nested-server.bats
test/functional/bundlelist/list-has-dep-nested.bats
test/functional/bundlelist/list-installed.bats
test/functional/bundlelist/list-json.bats
test/functional/bundlelist/list-no-disk-space.bats
test/functional/bundlelist/list-quiet.bats

Implementation of the `swupd 3rd-party bundle-list` command.
Closes #1179

Implement 3rd-party bundle-list

---

scripts/flag_validator.bash

This commit makes changes to the flag_validator script so it works
properly with 3rd-party commands/subcommands.

Fixing flag_validator to work with 3rd-party

---

Makefile.am
scripts/flag_validator.bash
src/3rd_party.c
src/3rd_party_bundle_list.c
src/3rd_party_diagnose.c
src/3rd_party_repos.c
src/3rd_party_repos.h
src/3rd_party_update.c
src/bundle_list.c
src/extra_files.c
src/os_install.c
src/repair.c
src/swupd_internal.h
src/verify.c
swupd.bash
swupd.zsh
test/functional/3rd-party/3rd-party-bundle-list-basic.bats
test/functional/3rd-party/3rd-party-diagnose-basic.bats
test/functional/diagnose/diagnose-json.bats
test/functional/os-install/install-json.bats
test/functional/repair/repair-json.bats
test/functional/testlib.bash

This PR adds the ability to diagnose bundles from 3rd-party repos.

Implementing the "3rd-party diagnose" command

---

src/3rd_party_add.c
src/3rd_party_list.c
src/3rd_party_remove.c
src/3rd_party_repos.c
test/functional/3rd-party/3rd-party-allow-http.bats
test/functional/3rd-party/3rd-party-repo-add-negative.bats
test/functional/3rd-party/3rd-party-repo-add.bats
test/functional/3rd-party/3rd-party-repo-list.bats
test/functional/3rd-party/3rd-party-repo-remove-negative.bats
test/functional/3rd-party/3rd-party-repo-remove.bats

This commit makes a few small changes to the output of the commands to
make it look cleaner and to be consistent with the output of other swupd
commands.

Formating 3rd-party add,list,remove command output

---

test/functional/testlib.bash

Sometimes when a test finds a problem in the source code it is difficult
to determine what is the problem in the code, so the code needs to be
debugged. In order to do this, the test environment of the particular
test has to be created but without running the test, so we can run the
command executed by the test with the debugger.
This commit adds a function (create_test_environment_only) to create a
specific test environment based on a bats file, but without running the
test.
Closes #1166 

Testlib option to create a replica of a test env

---

.github/workflows/ccpp.yml
test/functional/info/info-basic.bats

Add functional test for info

---

src/clean.c

Showing how much space was freed when cleaning

---

scripts/build_ci.bash
test/functional/autoupdate/aup-basic.bats
test/functional/testlib.bash

Signed-off-by: Karthik Prabhu Vinod karthik.prabhu.vinod@intel.com

autoupdate: adding auto-update test back

---

src/bundle_list.c

Fix return value overwriting during bundle-list

---

.github/workflows/ccpp.yml

This PR brings back down the test execution time to about ~15 minutes.

Rebalancing tests for github actions

---

test/functional/testlib.bash

This commit makes possible the creation of bundles with exported files
in test environments. These bundles will have the 'x' in the appropriate
place in the manifest plus those bundles that are to be installed in the
environment will have the "exporting script" created in the 3rd-party
bin directory.

testlib: Adding support for exported files

---

src/curl.c

curl: Remove unused variable

---

src/main.c

Rewording the 3rd-party menu details

---

docs/RELEASE_NOTES_DRAFT

Adding draft for the 3rd-party release notes

---

Makefile.am
config
scripts/flag_validator.bash
src/3rd_party.c
src/3rd_party_info.c
src/info.c
src/swupd_internal.h
swupd.bash
swupd.zsh
test/functional/3rd-party/3rd-party-info.bats

Implementation of the 3rd-party info command to show the version of the
3rd-party repository along with the update URL.
Closes #1354

Implementing the 3rd-party info command

---

test/functional/testlib.bash

The iterative manifest effort was droped so this commit removes the
iterative manifest support from testlib.

Remove iterative manifest support from testlib

---

test/functional/README.md

Updating testlib README

---

src/lib/sys.c

sys: Improve debug when running external scripts

---

config
docs/swupd.1.rst
src/curl.c
src/globals.c
src/globals.h
src/helpers.c
src/manifest.c
src/mirror.c
src/swupd.h
src/swupd_curl.h
src/version.c
swupd.bash
swupd.zsh
test/functional/bundleadd/add-no-signature.bats
test/functional/signature/corrupted-certificate.bats
test/functional/signature/corrupted-signature.bats
test/functional/signature/invalid-certificate.bats
test/functional/signature/no-signature.bats
test/functional/signature/version-sig-check.bats
test/functional/testlib.bash
test/functional/update/update-non-responsive.bats
test/functional/update/update-with-mirror-signature.bats

Also adding more tests and other fixes

Enforcing signature verification even when signature is missing

---

test/functional/testlib.bash
test/functional/update/update-with-mirror-signature.bats

Testlib: Fixing the absolute path of a mirror test

---

src/3rd_party_add.c
src/3rd_party_repos.c
src/3rd_party_update.c
src/bundle.c
src/bundle_add.c
src/bundle_remove.c
src/clean.c
src/curl.c
src/extra_files.c
src/hashdump.c
src/helpers.c
src/lib/sys.c
src/lib/sys.h
src/mirror.c
src/os_install.c
src/update.c
src/verify.c
test/unit/test_manifest.c
test/unit/test_signature.c

Remove extra slash from path in 3rd-party funcs

---

test/functional/3rd-party/3rd-party-repo-add-force.bats

Tests: Fix path with extra "/" in tests

---

src/helpers.c
src/manifest_parser.c
src/swupd.h
src/update.c

mixin: Print deprecation warning

---

README.md

README: Update badge to use information from github actions

---

src/3rd_party_bundle_remove.c
src/helpers.c

Bug_fix: Fixing memory leaks

---

test/functional/3rd-party/3rd-party-repo-add-certificate.bats

tests: Fix shellcheck-all reported problem

---

src/scripts.c
src/verifytime.c
test/functional/os-install/install-json.bats
test/functional/repair/repair-boot-file.bats
test/functional/repair/repair-json.bats
test/functional/update/update-boot-file.bats

This commit removes the extra slash '/' from the path from:
- the update_boot function
- the verifytime script

Remove extra slash from paths

---

src/lib/sys.h

Correct the comment from sys_path_join()

---

src/staging.c

Fix memory leak during do_staging()

---

src/autoupdate.c
test/functional/api/api-autoupdate.bats
test/functional/testlib.bash

flag is used for this command:
- swupd autoupdate

API: output for autoupdate

---

.github/workflows/ccpp.yml
scripts/github_actions/run_check.bash

Validate if we are really calling make check for all tests in
test/functional directory.

actions: Validate if all tests are going to be executed

---

src/update.c
test/functional/api/api-3rd-party-update.bats
test/functional/api/api-update.bats

- swupd update
- swupd 3rd-party update

API: output for [3rd-party] update

---

test/functional/testlib.bash

Testlib: fix help menu from function

---

src/search_file.c
test/functional/api/api-search-file.bats

API: output for search-file

---

docs/swupd.1.rst
src/globals.c

swupd --quiet documentation update.

---

src/search_file.c

search_file: Don't store boolean just to be used in an if clause

---

test/functional/update/update-attr-change.bats

tests: Adding more attribute changes to test

---

src/lib/strings.h

Fixing typo in helper description

---

scripts/github_actions/build_ci_style.bash
test/code_analysis/compliant.bats

compliant: Start using clang-format-10 to check for style problems

---

docs/swupd-alias.7.rst.in
docs/swupd-update.service.4.rst
docs/swupd-update.timer.4.rst
docs/swupd.1.rst

Using a man page formating similar to what other man pages in the system
uses.
Fixes #1285

docs: Changes on man pages to make is similar to system man pages

---

swupd.zsh

- Added a new flag `feature_thirdparty` for whether `3rd-party` operations
is supported.
- Improved return code handling.
Additional notes for future references:
The test of `3rd-party` feature **solely** relies on output of `swupd --help`.
Specifically, if the help message contains `3rd-party`, it's determined that
`3rd-party` feature is supported.
So please don't mention `3rd-party` in the help message in any future updates,
or otherwise we need alternative ways for this.

zsh-completions: Only add `3rd-party` when it's supported

---

test/functional/os-install/install-hardlink-symlink.bats
test/functional/testlib.bash

This PR improves the output of testlib functions so it is easier to use the library.
Closes #1477

Testlib: Improve the help description for all testlib functions/commands

---

test/functional/testlib.bash

Instead of relying on all tests of the same group to exist in the same
directory, testlib should assume those tests could be scattered across
multiple directories.
Closes #1485

Testlib: Fixing functions that use a test ID

---

src/swupd_lib/curl.c

curl: Remove '*' character in error output

---

src/3rd_party/3rd_party_update.c

Bug_Fix: Only update templates if repos exist

---

src/cmds/clean.c

Removing dead code in clean.c

---

docs/swupd.1.rst

Fixes: https://github.com/clearlinux/distribution/issues/2189
Signed-off-by: Mark D Horn <mark.d.horn@intel.com>

Fixed typo in man page.

---

test/real_content/swupd_repair_fullfiles.bats
test/real_content/swupd_update.bats
test/real_content/swupd_update_jump.bats

Signed-off-by: William Douglas <william.r.douglas@gmail.com>

Fix shellcheck directive placement

---

docs/how_to_contribute.md

I was reading up on what Clear Linux was and found some broken links so I went ahead and fixed them :)

Fix broken links

---

src/swupd_lib/globals.c

In the case of the system default paths being set, potential errors from state_set_*_path functions were being ignored. Handle errors and exit accordingly.
Previously the directories were not attempted to be created in this code path so there was no error handling needed but with the mkdir addition, no longer handling this erro will cause segfaults later on as the mkdir failure prevents the path setting further causing uninitalized variables to be used.

Handle errors from statedir_set_*_path

---

src/swupd_lib/manifest_parser.c

Also make a mask check more consistent with the rest of the code.

Fix test errors configuring the system mask
